/**
 * SQLite → MySQL Data Migration Script
 * 
 * Prerequisites:
 * 1. Docker MySQL running: docker compose up -d mysql
 * 2. .env updated with MySQL DATABASE_URL
 * 3. Schema pushed: npx prisma db push
 * 
 * Usage:
 *   Step 1: Export from SQLite  → npx tsx prisma/_migrate-to-mysql.ts export
 *   Step 2: Switch .env to MySQL DATABASE_URL
 *   Step 3: Push schema         → npx prisma db push
 *   Step 4: Import to MySQL     → npx tsx prisma/_migrate-to-mysql.ts import
 *   Step 5: Re-seed if needed   → npx tsx prisma/seed.ts
 */

import Database from "better-sqlite3";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { PrismaClient } from "@prisma/client";
import path from "path";

const EXPORT_FILE = path.join(__dirname, "_migration-data.json");

const TABLES = [
  "User", "Subscription", "Profile", "FamilyMember",
  "Address", "Service", "MovingPlan", "Task", "MovingBox",
  "Document", "Budget", "Reminder", "Review",
  "Badge", "UserBadge", "StateRule", "ServiceProvider",
  "AuditLog", "UserSession", "UserEvent",
  "AdminUser", "AdminPermission", "AdminAuditLog",
  "NotificationPreference", "Notification", "NotificationQueue",
  "KeywordBlacklist", "ModerationStat",
  "EmailTemplate", "EmailLog",
  "ChatSession", "ChatMessage",
  "HelpArticle", "FAQ", "FeatureFlag",
  "ReferralCode", "ReferralReward",
  "IPRule", "RateLimitLog", "GDPRRequest",
];

// SQLite table names match Prisma model names
function exportFromSqlite() {
  const dbPath = path.join(__dirname, "dev.db");
  if (!existsSync(dbPath)) {
    console.error("SQLite database not found at:", dbPath);
    process.exit(1);
  }

  const db = new Database(dbPath, { readonly: true });
  const data: Record<string, any[]> = {};

  for (const table of TABLES) {
    try {
      const rows = db.prepare(`SELECT * FROM "${table}"`).all();
      if (rows.length > 0) {
        data[table] = rows;
        console.log(`  ✓ ${table}: ${rows.length} rows`);
      }
    } catch (e: any) {
      // Table might not exist
      console.log(`  - ${table}: skipped (${e.message?.slice(0, 40)})`);
    }
  }

  writeFileSync(EXPORT_FILE, JSON.stringify(data, null, 2));
  console.log(`\nExported to: ${EXPORT_FILE}`);
  console.log(`Total tables: ${Object.keys(data).length}`);
  db.close();
}

async function importToMysql() {
  if (!existsSync(EXPORT_FILE)) {
    console.error("Migration data file not found. Run 'export' first.");
    process.exit(1);
  }

  const data: Record<string, any[]> = JSON.parse(readFileSync(EXPORT_FILE, "utf-8"));
  const prisma = new PrismaClient();

  // Import order matters due to foreign keys
  const importOrder = [
    "User", "Subscription", "Profile", "FamilyMember",
    "Address", "Service", "MovingPlan", "Task", "MovingBox",
    "Document", "Budget", "Reminder", "Review",
    "Badge", "UserBadge", "StateRule", "ServiceProvider",
    "AuditLog", "UserSession", "UserEvent",
    "AdminUser", "AdminPermission", "AdminAuditLog",
    "NotificationPreference", "Notification", "NotificationQueue",
    "KeywordBlacklist", "ModerationStat",
    "EmailTemplate", "EmailLog",
    "ChatSession", "ChatMessage",
    "HelpArticle", "FAQ", "FeatureFlag",
    "ReferralCode", "ReferralReward",
    "IPRule", "RateLimitLog", "GDPRRequest",
  ];

  // Map Prisma model name to camelCase delegate name
  function toCamelCase(name: string): string {
    return name.charAt(0).toLowerCase() + name.slice(1);
  }

  for (const table of importOrder) {
    const rows = data[table];
    if (!rows || rows.length === 0) continue;

    const delegate = toCamelCase(table) as keyof PrismaClient;
    const model = prisma[delegate];
    try {
      if (!model || typeof model !== "object" || !("create" in model) || typeof model.create !== "function") {
        console.log(`  - ${table}: skipped (delegate not found)`);
        continue;
      }
      const createRecord = model.create as unknown as (args: { data: Record<string, unknown> }) => Promise<unknown>;

      // Convert SQLite integer booleans to actual booleans, and date strings to Date objects
      const converted = rows.map((row: any) => {
        const obj: any = {};
        for (const [key, value] of Object.entries(row)) {
          if (value === null || value === undefined) {
            obj[key] = value;
          } else if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value)) {
            obj[key] = new Date(value);
          } else if (typeof value === "number" && (key.startsWith("is") || key.startsWith("has") || key === "completed" || key === "ocrProcessed" || key === "autoRenewal" || key === "isPrimary" || key === "isActive" || key === "isHidden" || key === "isVerified" || key === "isChild" || key === "isRecurring" || key === "isAutoGenerated" || key === "isPacked" || key === "isUnpacked" || key === "isFragile" || key === "isDefault" || key === "isPublished" || key === "read" || key === "sent" || key === "broadcast" || key === "isRegex" || key === "enabled" || key === "claimed" || key === "blocked" || key === "canManageServices" || key === "canManageBudget" || key === "canManageBilling" || key === "canInviteMembers" || key === "canRead" || key === "canCreate" || key === "canUpdate" || key === "canDelete")) {
            obj[key] = Boolean(value);
          } else {
            obj[key] = value;
          }
        }
        return obj;
      });

      let imported = 0;
      for (const row of converted) {
        try {
          await createRecord({ data: row as Record<string, unknown> });
          imported++;
        } catch (e: any) {
          // Skip duplicates (unique constraint violations)
          if (e?.code === "P2002") continue;
          console.error(`    Error in ${table}:`, e.message?.slice(0, 80));
        }
      }
      console.log(`  ✓ ${table}: ${imported}/${rows.length} imported`);
    } catch (e: any) {
      console.error(`  ✗ ${table}: ${e.message?.slice(0, 80)}`);
    }
  }

  await prisma.$disconnect();
  console.log("\nMigration complete!");
}

// ── CLI ──────────────────────────────────────────────────────
const command = process.argv[2];

if (command === "export") {
  console.log("=== EXPORTING FROM SQLITE ===\n");
  exportFromSqlite();
} else if (command === "import") {
  console.log("=== IMPORTING TO MYSQL ===\n");
  importToMysql().catch(console.error);
} else {
  console.log(`
SQLite → MySQL Migration Tool

Usage:
  npx tsx prisma/_migrate-to-mysql.ts export   Export data from SQLite
  npx tsx prisma/_migrate-to-mysql.ts import   Import data to MySQL
  `);
}
