export const HELP_ARTICLES_ALL = [
  // Getting Started
  { slug: "getting-started", title: "Getting Started with LocateFlow", excerpt: "Learn how to set up your account and start managing your relocation.", category: "Getting Started", tags: JSON.stringify(["setup", "beginner"]), order: 1, isPublished: true,
    content: "# Getting Started with LocateFlow\n\nWelcome to LocateFlow! Here's how to get started:\n\n## 1. Add Your Address\nStart by adding your current home address. Go to **Addresses** and click **Add Address**. Fill in your street, city, state, and ZIP code.\n\n## 2. Connect Services\nOnce you have an address, add the services connected to it — utilities, insurance, subscriptions, etc. Go to **Services** and click **Add Service**.\n\n## 3. Create a Moving Plan\nWhen you're ready to move, create a **Moving Plan** with your from/to addresses and move date. LocateFlow will generate a checklist of tasks.\n\n## 4. Track Your Budget\nUse the **Budget** section to track monthly income and expenses across all your services.\n\n## 5. Explore More\n- **Documents**: Upload and organize important files\n- **Community**: Read and write reviews for service providers\n- **Badges**: Earn achievements as you use LocateFlow" },
  { slug: "add-first-address", title: "How to Add Your First Address", excerpt: "Step-by-step guide to adding an address to your account.", category: "Getting Started", tags: JSON.stringify(["address", "setup"]), order: 2, isPublished: true,
    content: "# How to Add Your First Address\n\n## Steps\n1. Navigate to **Addresses** from the sidebar\n2. Click the **Add Address** button\n3. Fill in the required fields:\n   - **Street Address** (required)\n   - **City** (required)\n   - **State** (required)\n   - **ZIP Code** (required)\n   - **Nickname** (optional, e.g. \"Home\", \"Office\")\n   - **Address Type** (Home, Apartment, Condo, etc.)\n   - **Ownership** (Own or Rent)\n   - **Start Date** (when you moved in)\n4. Click **Save**\n\n## Tips\n- You can add multiple addresses to track services at each location\n- Use nicknames to easily identify addresses\n- The start date helps track how long you've been at each address" },
  { slug: "connect-services", title: "Connecting Your Services", excerpt: "How to add and manage utility and service providers.", category: "Getting Started", tags: JSON.stringify(["services", "utilities"]), order: 3, isPublished: true,
    content: "# Connecting Your Services\n\n## What Are Services?\nServices are any recurring accounts tied to your address — utilities (electric, gas, water), internet, insurance, subscriptions, gym memberships, etc.\n\n## How to Add a Service\n1. Go to **Services** from the sidebar\n2. Click **Add Service**\n3. Select or search for a **provider** from our database\n4. Choose the **category** (Electric, Gas, Internet, etc.)\n5. Link it to one of your **addresses**\n6. Enter the **monthly cost** (optional but recommended for budgeting)\n7. Set **billing date** and **contract end date** if applicable\n\n## Service Categories\n- **Utilities**: Electric, Gas, Water, Trash\n- **Communication**: Phone, Internet, Cable\n- **Insurance**: Auto, Home, Health, Life\n- **Financial**: Bank, Credit Card, Mortgage\n- **Lifestyle**: Gym, Subscriptions\n- **Transportation**: Toll, Transit" },
  { slug: "create-moving-plan", title: "Creating a Moving Plan", excerpt: "Plan your move step by step with tasks and timelines.", category: "Getting Started", tags: JSON.stringify(["moving", "planning"]), order: 4, isPublished: true,
    content: "# Creating a Moving Plan\n\n## Overview\nA Moving Plan helps you organize everything about your move — from packing to transferring services.\n\n## Steps\n1. Go to **Moving** from the sidebar\n2. Click **Create Moving Plan**\n3. Select your **from** and **to** addresses\n4. Set your **move date**\n5. LocateFlow will auto-generate a task checklist\n\n## Managing Tasks\n- Check off tasks as you complete them\n- Add custom tasks for your specific needs\n- Tasks are organized by category (Packing, Services, Documents, etc.)\n\n## Box Tracking\n- Track boxes by room (Kitchen, Bedroom, etc.)\n- Mark boxes as packed\n- See your overall packing progress\n\n## Tips\n- Start your plan at least 4-6 weeks before your move\n- Use the task list as a checklist to avoid forgetting anything\n- Transfer or cancel services as you check them off" },

  // Managing Services
  { slug: "transfer-services", title: "How to Transfer Services When Moving", excerpt: "Guide to transferring utilities and services to your new address.", category: "Managing Services", tags: JSON.stringify(["transfer", "moving", "utilities"]), order: 1, isPublished: true,
    content: "# How to Transfer Services When Moving\n\n## Before Your Move\n1. **Review your services**: Go to Services and note which ones need to be transferred, cancelled, or replaced\n2. **Contact providers early**: Most utility companies recommend 2-4 weeks notice\n3. **Schedule disconnection**: Set a final date for your current address (usually your move-out date)\n4. **Schedule connection**: Set a start date at your new address (ideally 1-2 days before move-in)\n\n## Common Services to Transfer\n- **Electric & Gas**: Contact your current provider or find a new one at your destination\n- **Water**: Usually managed by the city/county — contact your new municipality\n- **Internet/Cable**: Check if your provider serves your new area; if not, find a new one\n- **Insurance**: Update your address with auto, home/renters, and health insurance providers\n\n## Services That Follow You\nThese typically just need an address update:\n- Phone carriers\n- Streaming subscriptions\n- Bank accounts\n- Credit cards\n- Gym memberships (check for location transfers)\n\n## Don't Forget\n- **USPS mail forwarding**: Set up at moversguide.usps.com\n- **DMV**: Update your driver's license within the required timeframe\n- **Voter registration**: Register to vote at your new address" },
  { slug: "track-costs", title: "Tracking Monthly Service Costs", excerpt: "Monitor your spending across all services and addresses.", category: "Managing Services", tags: JSON.stringify(["budget", "costs", "tracking"]), order: 2, isPublished: true,
    content: "# Tracking Monthly Service Costs\n\n## Service Cost Tracking\nWhen adding or editing a service, enter the **monthly cost** field. This allows LocateFlow to:\n- Show total monthly expenses per address\n- Display spending by category on your dashboard\n- Track cost trends over time\n\n## Budget Feature\nFor more detailed tracking, use the **Budget** section:\n1. Go to **Budget** from the sidebar\n2. Add a monthly budget entry\n3. Set planned vs. actual income and expenses\n4. View category breakdowns\n5. Compare budget vs. actual spending\n\n## Dashboard Widgets\nYour dashboard includes several cost-related widgets:\n- **Spending by Address**: See how much each address costs monthly\n- **Expenses by Category**: Pie chart of where your money goes\n- **Upcoming Bills**: Bills due in the next 30 days\n- **Top Spending**: Your most expensive services" },
  { slug: "compare-providers", title: "Comparing Service Providers", excerpt: "Find and compare service providers for your area.", category: "Managing Services", tags: JSON.stringify(["providers", "comparison"]), order: 3, isPublished: true,
    content: "# Comparing Service Providers\n\n## Provider Database\nLocateFlow maintains a comprehensive database of service providers across all 50 states, including:\n- Utility companies (electric, gas, water)\n- Internet and cable providers\n- Insurance companies\n- Phone carriers\n- And many more\n\n## How Providers Work\n- **Federal providers** are available nationwide (e.g., AT&T, GEICO)\n- **State providers** serve specific states (e.g., PG&E in California)\n\n## Community Reviews\nBefore choosing a provider, check out community reviews:\n1. Go to **Community** from the sidebar\n2. Search for a provider by name\n3. Read reviews from other LocateFlow users\n4. See average ratings and sub-ratings\n\n## Writing Reviews\nHelp others by sharing your experience:\n1. Click **Write a Review** in the Community section\n2. Select the provider\n3. Rate your experience (1-5 stars)\n4. Add optional sub-ratings (customer service, pricing, reliability)\n5. Write your review\n6. Reviews are moderated for quality before publishing" },

  // Moving
  { slug: "moving-checklist", title: "Complete Moving Checklist", excerpt: "Everything you need to do before, during, and after your move.", category: "Moving", tags: JSON.stringify(["checklist", "moving"]), order: 1, isPublished: true,
    content: "# Complete Moving Checklist\n\n## 6-8 Weeks Before\n- [ ] Create a moving plan in LocateFlow\n- [ ] Research moving companies or rent a truck\n- [ ] Start decluttering — sell, donate, or discard items you don't need\n- [ ] Begin collecting packing supplies\n\n## 4-6 Weeks Before\n- [ ] Notify your landlord (if renting)\n- [ ] Set up USPS mail forwarding\n- [ ] Transfer or cancel utilities\n- [ ] Update address with banks, insurance, employers\n- [ ] Schedule movers or reserve truck\n\n## 2-4 Weeks Before\n- [ ] Start packing non-essential items\n- [ ] Label boxes by room\n- [ ] Confirm moving arrangements\n- [ ] Plan travel to new home\n\n## 1 Week Before\n- [ ] Pack essentials box (first-night items)\n- [ ] Finish packing\n- [ ] Clean current home\n- [ ] Confirm utility activation at new address\n\n## Moving Day\n- [ ] Do a final walkthrough of your old home\n- [ ] Take meter readings\n- [ ] Hand over keys\n- [ ] Supervise loading/unloading\n\n## After Moving\n- [ ] Update driver's license at your new state's DMV\n- [ ] Register to vote\n- [ ] Explore your new neighborhood\n- [ ] Update LocateFlow with your new address and services" },
  { slug: "packing-tips", title: "Packing Tips & Box Management", excerpt: "Efficient packing strategies and how to use box tracking.", category: "Moving", tags: JSON.stringify(["packing", "boxes"]), order: 2, isPublished: true,
    content: "# Packing Tips & Box Management\n\n## General Packing Tips\n- **Start early**: Begin packing rooms you use least\n- **Label everything**: Mark boxes with room name and contents\n- **Pack heavy items in small boxes**: Books, tools, etc.\n- **Pack light items in large boxes**: Pillows, linens, etc.\n- **Use towels and linens as padding**: Save on packing materials\n- **Keep essentials separate**: Pack a first-night box with toiletries, chargers, change of clothes, snacks\n\n## Box Tracking in LocateFlow\nYour moving plan includes box management:\n1. Open your moving plan\n2. Add boxes with a label and room assignment\n3. Mark boxes as packed as you go\n4. Track your overall packing progress\n\n## Room-by-Room Strategy\n- **Kitchen**: Wrap dishes individually, pack glasses upright\n- **Bedroom**: Use wardrobe boxes for hanging clothes\n- **Bathroom**: Seal liquids in zip-lock bags\n- **Office**: Back up electronics, label cables\n- **Garage**: Drain gas from power tools" },
  { slug: "moving-timeline", title: "Moving Timeline: Week by Week", excerpt: "A structured timeline to keep your move on track.", category: "Moving", tags: JSON.stringify(["timeline", "planning"]), order: 3, isPublished: true,
    content: "# Moving Timeline: Week by Week\n\n## 8 Weeks Out\n- Research your new area's service providers\n- Get moving quotes from 3+ companies\n- Create your moving plan in LocateFlow\n\n## 6 Weeks Out\n- Book your mover or reserve a truck\n- Start notifying service providers of your move\n- Begin decluttering\n\n## 4 Weeks Out\n- Start packing non-essential rooms\n- Set up USPS mail forwarding\n- Transfer or set up new utilities\n- Update address with financial institutions\n\n## 2 Weeks Out\n- Confirm all moving arrangements\n- Pack most rooms\n- Arrange childcare/pet care for moving day\n- Get cash for tips\n\n## 1 Week Out\n- Finish packing\n- Prepare essentials box\n- Clean and photograph old home\n- Confirm utility disconnection/connection dates\n\n## Moving Day\n- Final walkthrough and meter readings\n- Supervise movers\n- Hand over keys\n\n## Week After\n- Unpack essentials first\n- Update DMV, voter registration\n- Explore your new neighborhood\n- Update LocateFlow with new services" },

  // Account & Billing
  { slug: "manage-subscription", title: "Managing Your Subscription", excerpt: "How to view, upgrade, or change your LocateFlow plan.", category: "Account & Billing", tags: JSON.stringify(["subscription", "billing"]), order: 1, isPublished: true,
    content: "# Managing Your Subscription\n\n## Available Plans\n- **Free**: Basic features, limited addresses and services\n- **Pro**: Unlimited addresses, services, and documents. Family sharing.\n- **Enterprise**: All Pro features plus priority support and API access.\n\n## How to Change Your Plan\n1. Go to **Settings** > **Subscription**\n2. View your current plan and usage\n3. Click **Upgrade** or **Downgrade**\n4. Confirm your selection\n\n## Billing\n- Plans are billed monthly or annually (save 20% with annual)\n- You can cancel anytime\n- Downgrading takes effect at the end of your billing cycle\n- No refunds for partial months" },
  { slug: "family-sharing", title: "Family Sharing & Permissions", excerpt: "Invite family members and manage their access.", category: "Account & Billing", tags: JSON.stringify(["family", "sharing", "permissions"]), order: 2, isPublished: true,
    content: "# Family Sharing & Permissions\n\n## Overview\nFamily Sharing lets multiple people collaborate on managing addresses, services, and moving plans.\n\n## How to Invite Family Members\n1. Go to **Family** from the sidebar\n2. Click **Invite Member**\n3. Enter their email address\n4. Choose a role: **Admin**, **Editor**, or **Viewer**\n5. Set specific permissions for what they can access\n\n## Roles\n- **Admin**: Full access — can add, edit, and delete everything\n- **Editor**: Can add and edit, but cannot delete or manage members\n- **Viewer**: Read-only access to shared data\n\n## Permissions\nYou can grant granular access to:\n- Addresses\n- Services\n- Moving Plans\n- Budget\n- Documents" },
  { slug: "export-data", title: "Exporting Your Data", excerpt: "Download your data for backup or transfer.", category: "Account & Billing", tags: JSON.stringify(["export", "data", "backup"]), order: 3, isPublished: true,
    content: "# Exporting Your Data\n\n## How to Export\n1. Go to **Settings** > **Data Export**\n2. Choose what to export:\n   - Addresses\n   - Services\n   - Moving Plans\n   - Documents\n   - Budget data\n3. Select format (CSV or JSON)\n4. Click **Export**\n5. Download will start automatically\n\n## What's Included\n- All your personal data\n- Service details and costs\n- Moving plan tasks and progress\n- Budget entries\n- Document metadata (not the files themselves)\n\n## Data Portability\nYou have the right to your data at any time. Exports are available in standard formats that can be imported into spreadsheet applications." },

  // Privacy & Security
  { slug: "data-privacy", title: "Your Data Privacy Rights", excerpt: "How we protect your data and your rights.", category: "Privacy & Security", tags: JSON.stringify(["privacy", "gdpr", "data"]), order: 1, isPublished: true,
    content: "# Your Data Privacy Rights\n\n## Our Commitment\nLocateFlow is committed to protecting your personal data. We follow industry best practices and comply with applicable privacy laws.\n\n## Your Rights\n- **Access**: View all data we have about you\n- **Correction**: Update any incorrect information\n- **Deletion**: Request complete deletion of your account and data\n- **Export**: Download your data in standard formats\n- **Opt-out**: Control notification and marketing preferences\n\n## Data We Collect\n- Account information (name, email)\n- Addresses and service details\n- Usage data for improving the experience\n- We do NOT sell your data to third parties\n\n## Security Measures\n- All data encrypted in transit (TLS) and at rest\n- Regular security audits\n- Role-based access controls\n- Automated threat detection" },
  { slug: "delete-account", title: "How to Delete Your Account", excerpt: "Steps to permanently delete your account and data.", category: "Privacy & Security", tags: JSON.stringify(["delete", "account", "privacy"]), order: 2, isPublished: true,
    content: "# How to Delete Your Account\n\n## Before You Delete\n- Export your data first (Settings > Data Export)\n- This action is **permanent** and cannot be undone\n- All your data will be deleted including addresses, services, documents, and moving plans\n\n## Steps\n1. Go to **Settings**\n2. Scroll to the **Danger Zone** section\n3. Click **Delete Account**\n4. Confirm by typing 'DELETE' in the confirmation dialog\n5. Your account and all data will be permanently removed\n\n## What Happens\n- All personal data is deleted immediately\n- Your reviews will be anonymized (not deleted)\n- Shared family data will no longer be accessible to you\n- You will be signed out and redirected to the home page\n\n## Need Help?\nIf you're having issues with your account, consider reaching out to support first — we may be able to help resolve your concerns without deleting your account." },
];

export const FAQS_ALL = [
  // Account
  { question: "How do I create an account?", answer: "Click 'Get Started' on the landing page and sign up with your email address. You can also sign up using Google or other social providers through our authentication system.", category: "Account", order: 1, isPublished: true },
  { question: "How do I change my email address?", answer: "Go to Settings > Profile and update your email address. You'll need to verify your new email before the change takes effect.", category: "Account", order: 2, isPublished: true },
  { question: "Can I have multiple accounts?", answer: "We recommend using a single account with Family Sharing to manage multiple addresses. Each person should have their own account.", category: "Account", order: 3, isPublished: true },
  { question: "How do I reset my password?", answer: "Click 'Forgot Password' on the login page. Enter your email address and we'll send you a password reset link.", category: "Account", order: 4, isPublished: true },
  { question: "Is my data secure?", answer: "Yes. All data is encrypted in transit and at rest. We use industry-standard security practices including regular audits, role-based access controls, and secure authentication.", category: "Account", order: 5, isPublished: true },

  // Services
  { question: "How do I add a new service provider?", answer: "Go to Services > Add Service, then search our database of 300+ providers. If your provider isn't listed, you can add a custom entry.", category: "Services", order: 1, isPublished: true },
  { question: "Can I track services at multiple addresses?", answer: "Yes! Add as many addresses as you need and link services to each one. Your dashboard will show a combined view of all your services.", category: "Services", order: 2, isPublished: true },
  { question: "How do bill reminders work?", answer: "When you set a billing date on a service, LocateFlow will send you reminders via email and in-app notifications before the bill is due. You can customize reminder timing in Settings > Notifications.", category: "Services", order: 3, isPublished: true },
  { question: "What service categories are available?", answer: "We support 20+ categories including: Electric, Gas, Water, Internet, Phone, Cable/TV, Insurance (Auto, Home, Health), Mortgage/Rent, Gym, Subscriptions, and more.", category: "Services", order: 4, isPublished: true },

  // Moving
  { question: "How far in advance should I create a moving plan?", answer: "We recommend creating your plan 6-8 weeks before your move date. This gives you enough time to handle all the tasks like transferring services, packing, and notifying providers.", category: "Moving", order: 1, isPublished: true },
  { question: "Can I share my moving plan with family?", answer: "Yes! Use Family Sharing to invite members who can view or help manage the moving plan. Each person can check off their assigned tasks.", category: "Moving", order: 2, isPublished: true },
  { question: "What tasks does LocateFlow auto-generate?", answer: "Based on your addresses and services, we generate tasks for: USPS mail forwarding, DMV updates, voter registration, utility transfers, insurance updates, and more. You can also add custom tasks.", category: "Moving", order: 3, isPublished: true },
  { question: "Can I have multiple active moving plans?", answer: "Yes, you can create and manage multiple moving plans simultaneously. This is useful if you're managing moves for different family members or properties.", category: "Moving", order: 4, isPublished: true },

  // Billing
  { question: "What's included in the free plan?", answer: "The free plan includes: up to 2 addresses, 10 services, 1 moving plan, basic budget tracking, and community access. Upgrade to Pro for unlimited everything.", category: "Billing", order: 1, isPublished: true },
  { question: "How do I cancel my subscription?", answer: "Go to Settings > Subscription and click 'Cancel Plan'. Your access continues until the end of your billing period. You can resubscribe anytime.", category: "Billing", order: 2, isPublished: true },
  { question: "Do you offer refunds?", answer: "We offer a 14-day money-back guarantee on annual plans. Monthly plans are non-refundable but you can cancel anytime to stop future charges.", category: "Billing", order: 3, isPublished: true },

  // Privacy
  { question: "How do I delete my account?", answer: "Go to Settings > Danger Zone > Delete Account. This permanently removes all your data. We recommend exporting your data first from Settings > Data Export.", category: "Privacy", order: 1, isPublished: true },
  { question: "Do you sell my data?", answer: "No, never. We do not sell, rent, or share your personal data with third parties for marketing purposes. Your data is only used to provide the LocateFlow service.", category: "Privacy", order: 2, isPublished: true },
  { question: "Can I export my data?", answer: "Yes! Go to Settings > Data Export to download your addresses, services, moving plans, and budget data in CSV or JSON format.", category: "Privacy", order: 3, isPublished: true },
  { question: "How long do you keep my data?", answer: "We keep your data as long as you have an active account. If you delete your account, all data is permanently removed within 30 days. Anonymized analytics data may be retained.", category: "Privacy", order: 4, isPublished: true },
];
