type CoverageModel = "state" | "zip_prefix" | "polygon" | "live_address";

type SeedProviderRecord = {
  name: string;
  slug: string;
  category: string;
  description: string;
  website: string;
  scope: "STATE";
  states: string[];
  zipCodes?: string[];
  popularityScore: number;
  tags: string[];
};

export interface StateProviderCatalogEntry {
  providerName: string;
  states: string[];
  category: string;
  officialUrl: string;
  coverageModel: CoverageModel;
  note: string;
  legacyNames?: string[];
  seedRecord?: SeedProviderRecord;
}

function stateSeed(record: Omit<SeedProviderRecord, "scope">): SeedProviderRecord {
  return {
    ...record,
    scope: "STATE",
  };
}

type Batch2AUtilityCategory = "UTILITY_WATER" | "UTILITY_SEWER";

type Batch2AUtilityAccountInput = {
  providerName: string;
  state: string;
  category: Batch2AUtilityCategory;
  officialUrl: string;
  slug: string;
  zipCodes: string[];
  popularityScore: number;
  localTags: string[];
};

const BATCH2A_UTILITY_DESCRIPTION_BY_CATEGORY: Record<Batch2AUtilityCategory, string> = {
  UTILITY_WATER: "Local water utility customer account and service-address support",
  UTILITY_SEWER: "Local wastewater/sewer utility customer account and service-address support",
};

const BATCH2A_UTILITY_TAG_BY_CATEGORY: Record<Batch2AUtilityCategory, string> = {
  UTILITY_WATER: "water",
  UTILITY_SEWER: "sewer",
};

function batch2AUtilityAccountEntry(input: Batch2AUtilityAccountInput): StateProviderCatalogEntry {
  const serviceTag = BATCH2A_UTILITY_TAG_BY_CATEGORY[input.category];

  return {
    providerName: input.providerName,
    states: [input.state],
    category: input.category,
    officialUrl: input.officialUrl,
    coverageModel: "zip_prefix",
    note: "Batch 2A water/sewer utility customer account provider; ZIP-prefix scoped and address confirmation required before acting.",
    seedRecord: stateSeed({
      name: input.providerName,
      slug: input.slug,
      category: input.category,
      description: BATCH2A_UTILITY_DESCRIPTION_BY_CATEGORY[input.category],
      website: input.officialUrl,
      states: [input.state],
      zipCodes: input.zipCodes,
      popularityScore: input.popularityScore,
      tags: [serviceTag, "utility", ...input.localTags, "address-check"],
    }),
  };
}

const PROVIDER_ADDITIONS_V1_BATCH1_CATALOG: StateProviderCatalogEntry[] = [
  {
    providerName: "Anton Anderson Memorial Tunnel / Whittier Tunnel",
    states: ["AK"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://dot.alaska.gov/creg/whittiertunnel/index.shtml",
    coverageModel: "zip_prefix",
    note: "Batch 1 toll facility addition; corridor-scoped and not a statewide Alaska toll recommendation.",
    seedRecord: stateSeed({
      name: "Anton Anderson Memorial Tunnel / Whittier Tunnel",
      slug: "whittier-tunnel-ak",
      category: "TRANSPORTATION_TOLL",
      description: "Whittier tunnel toll and vehicle access account/payment surface",
      website: "https://dot.alaska.gov/creg/whittiertunnel/index.shtml",
      states: ["AK"],
      zipCodes: ["996"],
      popularityScore: 58,
      tags: ["toll", "driving", "whittier", "address-check"],
    }),
  },
  {
    providerName: "Alabama Department of Revenue Motor Vehicle Division",
    states: ["AL"],
    category: "GOVERNMENT_DMV",
    officialUrl: "https://www.revenue.alabama.gov/division/motor-vehicle/",
    coverageModel: "state",
    note: "Official Alabama motor vehicle registration and tax surface; complements the existing driver-license DMV row.",
    seedRecord: stateSeed({
      name: "Alabama Department of Revenue Motor Vehicle Division",
      slug: "alabama-dor-motor-vehicle",
      category: "GOVERNMENT_DMV",
      description: "Official Alabama motor vehicle registration and address/account action surface",
      website: "https://www.revenue.alabama.gov/division/motor-vehicle/",
      states: ["AL"],
      popularityScore: 78,
      tags: ["dmv", "vehicle-registration", "government", "alabama"],
    }),
  },
  {
    providerName: "Alabama Freedom Pass",
    states: ["AL"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://freedompass.americanroads.com",
    coverageModel: "state",
    note: "Real toll pass account provider; state-scoped because the batch did not include reliable facility ZIPs.",
    seedRecord: stateSeed({
      name: "Alabama Freedom Pass",
      slug: "alabama-freedom-pass",
      category: "TRANSPORTATION_TOLL",
      description: "Alabama toll pass account for transponder, vehicle, payment, and mailing details",
      website: "https://freedompass.americanroads.com",
      states: ["AL"],
      popularityScore: 62,
      tags: ["toll", "transponder", "driving", "alabama"],
    }),
  },
  {
    providerName: "91 Express Lanes",
    states: ["CA"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.91expresslanes.com",
    coverageModel: "zip_prefix",
    note: "Real toll account provider; modeled only around the corridor ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "91 Express Lanes",
      slug: "91-express-lanes",
      category: "TRANSPORTATION_TOLL",
      description: "91 Express Lanes toll account for transponder, vehicle, payment, and mailing details",
      website: "https://www.91expresslanes.com",
      states: ["CA"],
      zipCodes: ["925", "928"],
      popularityScore: 70,
      tags: ["toll", "express-lanes", "transponder", "southern-california"],
    }),
  },
  {
    providerName: "Metro ExpressLanes",
    states: ["CA"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.metroexpresslanes.net",
    coverageModel: "zip_prefix",
    note: "Real toll account provider; modeled only around Los Angeles corridor ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "Metro ExpressLanes",
      slug: "metro-expresslanes",
      category: "TRANSPORTATION_TOLL",
      description: "Metro ExpressLanes toll account for transponder, vehicle, payment, and mailing details",
      website: "https://www.metroexpresslanes.net",
      states: ["CA"],
      zipCodes: ["900", "905", "907"],
      popularityScore: 72,
      tags: ["toll", "express-lanes", "transponder", "los-angeles"],
    }),
  },
  {
    providerName: "The Toll Roads",
    states: ["CA"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.thetollroads.com",
    coverageModel: "zip_prefix",
    note: "Real toll account provider; modeled only around Orange County corridor ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "The Toll Roads",
      slug: "the-toll-roads-orange-county",
      category: "TRANSPORTATION_TOLL",
      description: "Orange County toll road account for transponder, vehicle, payment, and mailing details",
      website: "https://www.thetollroads.com",
      states: ["CA"],
      zipCodes: ["926", "927"],
      popularityScore: 74,
      tags: ["toll", "transponder", "orange-county"],
    }),
  },
  {
    providerName: "E-470 Public Highway Authority",
    states: ["CO"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.e-470.com",
    coverageModel: "zip_prefix",
    note: "Real toll account provider; modeled only around Denver-area corridor ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "E-470 Public Highway Authority",
      slug: "e-470",
      category: "TRANSPORTATION_TOLL",
      description: "E-470 toll account for license plates, vehicles, payments, and mailing details",
      website: "https://www.e-470.com",
      states: ["CO"],
      zipCodes: ["800", "801", "802"],
      popularityScore: 70,
      tags: ["toll", "license-plate", "denver"],
    }),
  },
  {
    providerName: "Northwest Parkway",
    states: ["CO"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.nwpky.com",
    coverageModel: "zip_prefix",
    note: "Real toll road account surface; modeled only around corridor ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "Northwest Parkway",
      slug: "northwest-parkway",
      category: "TRANSPORTATION_TOLL",
      description: "Northwest Parkway toll account and payment surface for vehicle and mailing details",
      website: "https://www.nwpky.com",
      states: ["CO"],
      zipCodes: ["800", "803"],
      popularityScore: 62,
      tags: ["toll", "license-plate", "broomfield"],
    }),
  },
  {
    providerName: "Access Health CT",
    states: ["CT"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://www.accesshealthct.com",
    coverageModel: "zip_prefix",
    note: "Official Connecticut health marketplace account surface, modeled with Connecticut ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Access Health CT",
      slug: "access-health-ct",
      category: "GOVERNMENT_HEALTH",
      description: "Official Connecticut health marketplace account and address update portal",
      website: "https://www.accesshealthct.com",
      states: ["CT"],
      zipCodes: ["060", "061", "062", "063", "064", "065", "066", "067", "068", "069"],
      popularityScore: 82,
      tags: ["health", "marketplace", "government", "connecticut"],
    }),
  },
  {
    providerName: "HUSKY Health",
    states: ["CT"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://portal.ct.gov/HUSKY",
    coverageModel: "zip_prefix",
    note: "Official Connecticut Medicaid/HUSKY health account surface, modeled with Connecticut ZIP prefixes.",
    seedRecord: stateSeed({
      name: "HUSKY Health",
      slug: "husky-health-ct",
      category: "GOVERNMENT_HEALTH",
      description: "Official Connecticut Medicaid and HUSKY Health account/address surface",
      website: "https://portal.ct.gov/HUSKY",
      states: ["CT"],
      zipCodes: ["060", "061", "062", "063", "064", "065", "066", "067", "068", "069"],
      popularityScore: 78,
      tags: ["medicaid", "health", "government", "connecticut"],
    }),
  },
  {
    providerName: "Connecticut Department of Revenue Services",
    states: ["CT"],
    category: "GOVERNMENT_TAX",
    officialUrl: "https://portal.ct.gov/DRS",
    coverageModel: "zip_prefix",
    note: "Official Connecticut tax account/address surface, modeled with Connecticut ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Connecticut Department of Revenue Services",
      slug: "ct-drs",
      category: "GOVERNMENT_TAX",
      description: "Official Connecticut tax account and address update surface",
      website: "https://portal.ct.gov/DRS",
      states: ["CT"],
      zipCodes: ["060", "061", "062", "063", "064", "065", "066", "067", "068", "069"],
      popularityScore: 74,
      tags: ["tax", "government", "connecticut"],
    }),
  },
  {
    providerName: "DC Health Link",
    states: ["DC"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://www.dchealthlink.com",
    coverageModel: "zip_prefix",
    note: "Official DC health marketplace account surface, modeled with District ZIP prefixes.",
    seedRecord: stateSeed({
      name: "DC Health Link",
      slug: "dc-health-link",
      category: "GOVERNMENT_HEALTH",
      description: "Official DC health marketplace account and address update portal",
      website: "https://www.dchealthlink.com",
      states: ["DC"],
      zipCodes: ["200", "202", "203", "204", "205"],
      popularityScore: 80,
      tags: ["health", "marketplace", "government", "dc"],
    }),
  },
  {
    providerName: "District Direct",
    states: ["DC"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://districtdirect.dc.gov",
    coverageModel: "zip_prefix",
    note: "Official DC benefits account portal, modeled with District ZIP prefixes.",
    seedRecord: stateSeed({
      name: "District Direct",
      slug: "dc-district-direct",
      category: "GOVERNMENT_HEALTH",
      description: "Official DC benefits and health account portal for profile and address updates",
      website: "https://districtdirect.dc.gov",
      states: ["DC"],
      zipCodes: ["200", "202", "203", "204", "205"],
      popularityScore: 78,
      tags: ["benefits", "health", "medicaid", "government", "dc"],
    }),
  },
  {
    providerName: "MyTax.DC.gov",
    states: ["DC"],
    category: "GOVERNMENT_TAX",
    officialUrl: "https://mytax.dc.gov",
    coverageModel: "zip_prefix",
    note: "Official DC tax account portal, modeled with District ZIP prefixes.",
    seedRecord: stateSeed({
      name: "MyTax.DC.gov",
      slug: "mytax-dc",
      category: "GOVERNMENT_TAX",
      description: "Official DC tax account and mailing address update portal",
      website: "https://mytax.dc.gov",
      states: ["DC"],
      zipCodes: ["200", "202", "203", "204", "205"],
      popularityScore: 76,
      tags: ["tax", "government", "dc"],
    }),
  },
  {
    providerName: "Delaware Medicaid / ASSIST",
    states: ["DE"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://assist.dhss.delaware.gov",
    coverageModel: "zip_prefix",
    note: "Official Delaware benefits and Medicaid account surface, modeled with Delaware ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Delaware Medicaid / ASSIST",
      slug: "delaware-medicaid-assist",
      category: "GOVERNMENT_HEALTH",
      description: "Official Delaware Medicaid and benefits account/address portal",
      website: "https://assist.dhss.delaware.gov",
      states: ["DE"],
      zipCodes: ["197", "198", "199"],
      popularityScore: 76,
      tags: ["medicaid", "benefits", "health", "government", "delaware"],
    }),
  },
  {
    providerName: "Delaware Taxpayer Portal",
    states: ["DE"],
    category: "GOVERNMENT_TAX",
    officialUrl: "https://tax.delaware.gov",
    coverageModel: "zip_prefix",
    note: "Official Delaware taxpayer account surface, modeled with Delaware ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Delaware Taxpayer Portal",
      slug: "delaware-taxpayer-portal",
      category: "GOVERNMENT_TAX",
      description: "Official Delaware taxpayer account and address update portal",
      website: "https://tax.delaware.gov",
      states: ["DE"],
      zipCodes: ["197", "198", "199"],
      popularityScore: 74,
      tags: ["tax", "government", "delaware"],
    }),
  },
  {
    providerName: "Delaware E-ZPass",
    states: ["DE"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.ezpassde.com",
    coverageModel: "zip_prefix",
    note: "Real Delaware toll account provider; US 301 toll-by-plate row is folded into this account surface.",
    seedRecord: stateSeed({
      name: "Delaware E-ZPass",
      slug: "delaware-ezpass",
      category: "TRANSPORTATION_TOLL",
      description: "Delaware E-ZPass toll account for transponder, vehicle, payment, and mailing details",
      website: "https://www.ezpassde.com",
      states: ["DE"],
      zipCodes: ["197", "198", "199"],
      popularityScore: 72,
      tags: ["toll", "ezpass", "transponder", "delaware"],
    }),
  },
  {
    providerName: "Florida KidCare",
    states: ["FL"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://www.floridakidcare.org",
    coverageModel: "zip_prefix",
    note: "Official Florida child health insurance account surface, modeled with Florida ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "Florida KidCare",
      slug: "florida-kidcare",
      category: "GOVERNMENT_HEALTH",
      description: "Official Florida child health insurance account and address update surface",
      website: "https://www.floridakidcare.org",
      states: ["FL"],
      zipCodes: ["320", "321", "322", "323", "324", "325", "326", "327", "328", "329", "330", "331", "332", "333", "334", "335", "336", "337", "338", "339", "341", "342", "344", "346", "347", "349"],
      popularityScore: 78,
      tags: ["health", "children", "government", "florida"],
    }),
  },
  {
    providerName: "Florida Medicaid / MyACCESS",
    states: ["FL"],
    category: "GOVERNMENT_HEALTH",
    officialUrl: "https://myaccess.myflfamilies.com",
    coverageModel: "zip_prefix",
    note: "Official Florida benefits/Medicaid account surface, modeled with Florida ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "Florida Medicaid / MyACCESS",
      slug: "florida-myaccess-medicaid",
      category: "GOVERNMENT_HEALTH",
      description: "Official Florida benefits and Medicaid account/address portal",
      website: "https://myaccess.myflfamilies.com",
      states: ["FL"],
      zipCodes: ["320", "321", "322", "323", "324", "325", "326", "327", "328", "329", "330", "331", "332", "333", "334", "335", "336", "337", "338", "339", "341", "342", "344", "346", "347", "349"],
      popularityScore: 82,
      tags: ["medicaid", "benefits", "health", "government", "florida"],
    }),
  },
  {
    providerName: "Florida DOR e-Services",
    states: ["FL"],
    category: "GOVERNMENT_TAX",
    officialUrl: "https://floridarevenue.com",
    coverageModel: "zip_prefix",
    note: "Official Florida tax e-services account surface, modeled with Florida ZIP prefixes from Batch 1.",
    seedRecord: stateSeed({
      name: "Florida DOR e-Services",
      slug: "florida-dor-eservices",
      category: "GOVERNMENT_TAX",
      description: "Official Florida Department of Revenue tax e-services account portal",
      website: "https://floridarevenue.com",
      states: ["FL"],
      zipCodes: ["320", "321", "322", "323", "324", "325", "326", "327", "328", "329", "330", "331", "332", "333", "334", "335", "336", "337", "338", "339", "341", "342", "344", "346", "347", "349"],
      popularityScore: 76,
      tags: ["tax", "government", "florida"],
    }),
  },
  {
    providerName: "E-PASS / Central Florida Expressway Authority",
    states: ["FL"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.cfxway.com",
    coverageModel: "zip_prefix",
    note: "Real Central Florida toll account provider; modeled around Batch 1 corridor ZIP prefixes.",
    seedRecord: stateSeed({
      name: "E-PASS / Central Florida Expressway Authority",
      slug: "epass-cfx",
      category: "TRANSPORTATION_TOLL",
      description: "Central Florida E-PASS toll account for transponder, vehicle, payment, and mailing details",
      website: "https://www.cfxway.com",
      states: ["FL"],
      zipCodes: ["327", "328", "347"],
      popularityScore: 76,
      tags: ["toll", "epass", "transponder", "central-florida"],
    }),
  },
  {
    providerName: "Greater Miami Expressway Agency",
    states: ["FL"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.gmx-way.com",
    coverageModel: "zip_prefix",
    note: "Real Miami-area toll account/payment provider; modeled around Batch 1 corridor ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Greater Miami Expressway Agency",
      slug: "greater-miami-expressway-agency",
      category: "TRANSPORTATION_TOLL",
      description: "Miami-area toll account and payment surface for vehicle and mailing details",
      website: "https://www.gmx-way.com",
      states: ["FL"],
      zipCodes: ["330", "331", "332"],
      popularityScore: 68,
      tags: ["toll", "miami", "expressway"],
    }),
  },
  {
    providerName: "I-4 Express",
    states: ["FL"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://i4express.com",
    coverageModel: "zip_prefix",
    note: "Real I-4 Express toll account/payment provider; modeled around Batch 1 corridor ZIP prefixes.",
    seedRecord: stateSeed({
      name: "I-4 Express",
      slug: "i4-express",
      category: "TRANSPORTATION_TOLL",
      description: "I-4 Express toll account and payment surface for vehicle and mailing details",
      website: "https://i4express.com",
      states: ["FL"],
      zipCodes: ["327", "328"],
      popularityScore: 66,
      tags: ["toll", "express-lanes", "orlando"],
    }),
  },
  {
    providerName: "Tampa Hillsborough Expressway Authority",
    states: ["FL"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.tampa-xway.com",
    coverageModel: "zip_prefix",
    note: "Real Tampa-area toll account/payment provider; modeled around Batch 1 corridor ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Tampa Hillsborough Expressway Authority",
      slug: "tampa-hillsborough-expressway-authority",
      category: "TRANSPORTATION_TOLL",
      description: "Tampa-area expressway toll account and payment surface for vehicle and mailing details",
      website: "https://www.tampa-xway.com",
      states: ["FL"],
      zipCodes: ["335", "336"],
      popularityScore: 66,
      tags: ["toll", "tampa", "expressway"],
    }),
  },
  {
    providerName: "Alaska Electric Light and Power",
    states: ["AK"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.aelp.com",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with Juneau-area ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Alaska Electric Light and Power",
      slug: "alaska-electric-light-power",
      category: "UTILITY_ELECTRIC",
      description: "Juneau-area electric utility account; confirm service availability by address",
      website: "https://www.aelp.com",
      states: ["AK"],
      zipCodes: ["998"],
      popularityScore: 66,
      tags: ["electric", "utility", "juneau", "address-check"],
    }),
  },
  {
    providerName: "Golden Valley Electric Association",
    states: ["AK"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.gvea.com",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with cautious AK 997 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Golden Valley Electric Association",
      slug: "golden-valley-electric-association",
      category: "UTILITY_ELECTRIC",
      description: "Interior Alaska electric utility account; confirm service availability by address",
      website: "https://www.gvea.com",
      states: ["AK"],
      zipCodes: ["997"],
      popularityScore: 70,
      tags: ["electric", "utility", "fairbanks", "address-check"],
    }),
  },
  {
    providerName: "Homer Electric Association",
    states: ["AK"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.homerelectric.com",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with cautious AK 996 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Homer Electric Association",
      slug: "homer-electric-association",
      category: "UTILITY_ELECTRIC",
      description: "Kenai Peninsula electric utility account; confirm service availability by address",
      website: "https://www.homerelectric.com",
      states: ["AK"],
      zipCodes: ["996"],
      popularityScore: 68,
      tags: ["electric", "utility", "kenai", "address-check"],
    }),
  },
  {
    providerName: "Ketchikan Public Utilities Electric",
    states: ["AK"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.ketchikan.gov/ketchikan-public-utilities",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with Ketchikan-area ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Ketchikan Public Utilities Electric",
      slug: "ketchikan-public-utilities-electric",
      category: "UTILITY_ELECTRIC",
      description: "Ketchikan municipal electric utility account; confirm service availability by address",
      website: "https://www.ketchikan.gov/ketchikan-public-utilities",
      states: ["AK"],
      zipCodes: ["999"],
      popularityScore: 62,
      tags: ["electric", "municipal-utility", "ketchikan", "address-check"],
    }),
  },
  {
    providerName: "Matanuska Electric Association",
    states: ["AK"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.mea.coop",
    coverageModel: "zip_prefix",
    note: "Real electric cooperative; modeled with cautious AK 995/996 ZIP prefixes and address confirmation language.",
    seedRecord: stateSeed({
      name: "Matanuska Electric Association",
      slug: "matanuska-electric-association",
      category: "UTILITY_ELECTRIC",
      description: "Matanuska-Susitna electric utility account; confirm service availability by address",
      website: "https://www.mea.coop",
      states: ["AK"],
      zipCodes: ["995", "996"],
      popularityScore: 70,
      tags: ["electric", "cooperative", "matanuska", "address-check"],
    }),
  },
  {
    providerName: "Interior Gas Utility",
    states: ["AK"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.interiorgas.com",
    coverageModel: "zip_prefix",
    note: "Real gas utility; modeled with cautious AK 997 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Interior Gas Utility",
      slug: "interior-gas-utility",
      category: "UTILITY_GAS",
      description: "Interior Alaska natural gas utility account; confirm service availability by address",
      website: "https://www.interiorgas.com",
      states: ["AK"],
      zipCodes: ["997"],
      popularityScore: 64,
      tags: ["gas", "utility", "fairbanks", "address-check"],
    }),
  },
  {
    providerName: "Decatur Utilities Electric",
    states: ["AL"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.decaturutilities.com",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with Decatur-area ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Decatur Utilities Electric",
      slug: "decatur-utilities-electric",
      category: "UTILITY_ELECTRIC",
      description: "Decatur municipal electric utility account; confirm service availability by address",
      website: "https://www.decaturutilities.com",
      states: ["AL"],
      zipCodes: ["356"],
      popularityScore: 62,
      tags: ["electric", "municipal-utility", "decatur", "address-check"],
    }),
  },
  {
    providerName: "Huntsville Utilities Electric",
    states: ["AL"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.hsvutil.org",
    coverageModel: "zip_prefix",
    note: "Real municipal utility; gas duplicate is folded into this single provider row.",
    seedRecord: stateSeed({
      name: "Huntsville Utilities",
      slug: "huntsville-utilities-electric",
      category: "UTILITY_ELECTRIC",
      description: "Huntsville electric, gas, and water utility account; confirm service availability by address",
      website: "https://www.hsvutil.org",
      states: ["AL"],
      zipCodes: ["357", "358"],
      popularityScore: 72,
      tags: ["electric", "gas", "water", "municipal-utility", "huntsville", "address-check"],
    }),
  },
  {
    providerName: "Southeast Gas",
    states: ["AL"],
    category: "UTILITY_GAS",
    officialUrl: "https://southeastgas.com",
    coverageModel: "live_address",
    note: "Real gas utility from Batch 1, but the candidate had unknown territory; catalog-only until ZIP/service-area confirmation.",
  },
  {
    providerName: "Conway Corp Electric",
    states: ["AR"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.conwaycorp.com",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with Conway-area ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Conway Corp Electric",
      slug: "conway-corp-electric",
      category: "UTILITY_ELECTRIC",
      description: "Conway municipal electric utility account; confirm service availability by address",
      website: "https://www.conwaycorp.com",
      states: ["AR"],
      zipCodes: ["720"],
      popularityScore: 64,
      tags: ["electric", "municipal-utility", "conway", "address-check"],
    }),
  },
  {
    providerName: "North Little Rock Electric",
    states: ["AR"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://nlrelectric.com",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with North Little Rock ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "North Little Rock Electric",
      slug: "north-little-rock-electric",
      category: "UTILITY_ELECTRIC",
      description: "North Little Rock municipal electric utility account; confirm service availability by address",
      website: "https://nlrelectric.com",
      states: ["AR"],
      zipCodes: ["721"],
      popularityScore: 62,
      tags: ["electric", "municipal-utility", "north-little-rock", "address-check"],
    }),
  },
  {
    providerName: "Southwestern Electric Power Company (SWEPCO)",
    states: ["AR"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.swepco.com",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with cautious Arkansas ZIP prefixes and address confirmation language.",
    seedRecord: stateSeed({
      name: "Southwestern Electric Power Company (SWEPCO)",
      slug: "swepco-ar",
      category: "UTILITY_ELECTRIC",
      description: "SWEPCO electric utility account in Arkansas; confirm service availability by address",
      website: "https://www.swepco.com",
      states: ["AR"],
      zipCodes: ["718", "727"],
      popularityScore: 70,
      tags: ["electric", "utility", "swepco", "address-check"],
    }),
  },
  {
    providerName: "Arkansas Oklahoma Gas",
    states: ["AR"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.aogc.com",
    coverageModel: "zip_prefix",
    note: "Real gas utility; modeled with cautious western Arkansas ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Arkansas Oklahoma Gas",
      slug: "arkansas-oklahoma-gas",
      category: "UTILITY_GAS",
      description: "Arkansas Oklahoma Gas account; confirm service availability by address",
      website: "https://www.aogc.com",
      states: ["AR"],
      zipCodes: ["729"],
      popularityScore: 64,
      tags: ["gas", "utility", "western-arkansas", "address-check"],
    }),
  },
  {
    providerName: "Summit Utilities Arkansas",
    states: ["AR"],
    category: "UTILITY_GAS",
    officialUrl: "https://summitutilities.com",
    coverageModel: "live_address",
    note: "Real gas utility from Batch 1, but the candidate had unknown territory; catalog-only until ZIP/service-area confirmation.",
  },
  {
    providerName: "Tucson Electric Power",
    states: ["AZ"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.tep.com",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with Tucson-area ZIP prefixes and address confirmation language.",
    seedRecord: stateSeed({
      name: "Tucson Electric Power",
      slug: "tucson-electric-power",
      category: "UTILITY_ELECTRIC",
      description: "Tucson-area electric utility account; confirm service availability by address",
      website: "https://www.tep.com",
      states: ["AZ"],
      zipCodes: ["856", "857"],
      popularityScore: 78,
      tags: ["electric", "utility", "tucson", "address-check"],
    }),
  },
  {
    providerName: "UniSource Energy Services Electric",
    states: ["AZ"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.uesaz.com",
    coverageModel: "zip_prefix",
    note: "Real utility account provider; gas duplicate is folded into this single provider row.",
    seedRecord: stateSeed({
      name: "UniSource Energy Services",
      slug: "unisource-electric-az",
      category: "UTILITY_ELECTRIC",
      description: "UniSource electric and natural gas utility account; confirm service availability by address",
      website: "https://www.uesaz.com",
      states: ["AZ"],
      zipCodes: ["856", "864"],
      popularityScore: 72,
      tags: ["electric", "gas", "utility", "arizona", "address-check"],
    }),
  },
  {
    providerName: "Sacramento Municipal Utility District",
    states: ["CA"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.smud.org",
    coverageModel: "zip_prefix",
    note: "Real electric utility; modeled with cautious Sacramento-area ZIP prefixes and address confirmation language.",
    seedRecord: stateSeed({
      name: "Sacramento Municipal Utility District",
      slug: "smud",
      category: "UTILITY_ELECTRIC",
      description: "Sacramento-area electric utility account; confirm service availability by address",
      website: "https://www.smud.org",
      states: ["CA"],
      zipCodes: ["956", "957", "958"],
      popularityScore: 84,
      tags: ["electric", "municipal-utility", "sacramento", "address-check"],
    }),
  },
  {
    providerName: "Jewett City Department of Public Utilities",
    states: ["CT"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.jewettcitydpu.com",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with CT 063 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Jewett City Department of Public Utilities",
      slug: "jewett-city-dpu-electric",
      category: "UTILITY_ELECTRIC",
      description: "Jewett City municipal electric utility account; confirm service availability by address",
      website: "https://www.jewettcitydpu.com",
      states: ["CT"],
      zipCodes: ["063"],
      popularityScore: 54,
      tags: ["electric", "municipal-utility", "jewett-city", "address-check"],
    }),
  },
  {
    providerName: "Norwich Public Utilities",
    states: ["CT"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://norwichpublicutilities.com",
    coverageModel: "zip_prefix",
    note: "Real municipal utility; modeled with CT 063 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Norwich Public Utilities",
      slug: "norwich-public-utilities-electric",
      category: "UTILITY_ELECTRIC",
      description: "Norwich municipal utility account; confirm service availability by address",
      website: "https://norwichpublicutilities.com",
      states: ["CT"],
      zipCodes: ["063"],
      popularityScore: 60,
      tags: ["electric", "municipal-utility", "norwich", "address-check"],
    }),
  },
  {
    providerName: "Wallingford Electric Division",
    states: ["CT"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.wallingfordct.gov/government/departments/electric-division/",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with CT 064 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Wallingford Electric Division",
      slug: "wallingford-electric-division",
      category: "UTILITY_ELECTRIC",
      description: "Wallingford municipal electric utility account; confirm service availability by address",
      website: "https://www.wallingfordct.gov/government/departments/electric-division/",
      states: ["CT"],
      zipCodes: ["064"],
      popularityScore: 58,
      tags: ["electric", "municipal-utility", "wallingford", "address-check"],
    }),
  },
  {
    providerName: "City of Dover Electric Department",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.cityofdover.gov/Public-Utilities/",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Dover ZIPs from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "City of Dover Electric Department",
      slug: "city-of-dover-electric",
      category: "UTILITY_ELECTRIC",
      description: "Dover municipal electric utility account; confirm service availability by address",
      website: "https://www.cityofdover.gov/Public-Utilities/",
      states: ["DE"],
      zipCodes: ["19901", "19904"],
      popularityScore: 62,
      tags: ["electric", "municipal-utility", "dover", "address-check"],
    }),
  },
  {
    providerName: "City of Milford Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.cityofmilford.com",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Milford ZIP from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "City of Milford Electric",
      slug: "city-of-milford-electric",
      category: "UTILITY_ELECTRIC",
      description: "Milford municipal electric utility account; confirm service availability by address",
      website: "https://www.cityofmilford.com",
      states: ["DE"],
      zipCodes: ["19963"],
      popularityScore: 58,
      tags: ["electric", "municipal-utility", "milford", "address-check"],
    }),
  },
  {
    providerName: "City of Newark Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://newarkde.gov/18/Electrical-Engineering",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Newark ZIPs from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "City of Newark Electric",
      slug: "city-of-newark-electric",
      category: "UTILITY_ELECTRIC",
      description: "Newark municipal electric utility account; confirm service availability by address",
      website: "https://newarkde.gov/18/Electrical-Engineering",
      states: ["DE"],
      zipCodes: ["19711", "19713", "19716", "19717"],
      popularityScore: 62,
      tags: ["electric", "municipal-utility", "newark", "address-check"],
    }),
  },
  {
    providerName: "Delaware Electric Cooperative",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.delaware.coop",
    coverageModel: "zip_prefix",
    note: "Real electric cooperative; modeled with cautious DE 199 ZIP prefix and address confirmation language.",
    seedRecord: stateSeed({
      name: "Delaware Electric Cooperative",
      slug: "delaware-electric-cooperative",
      category: "UTILITY_ELECTRIC",
      description: "Delaware Electric Cooperative account; confirm service availability by address",
      website: "https://www.delaware.coop",
      states: ["DE"],
      zipCodes: ["199"],
      popularityScore: 70,
      tags: ["electric", "cooperative", "delaware", "address-check"],
    }),
  },
  {
    providerName: "Lewes Board of Public Works Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.lewesbpwde.gov",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Lewes ZIP from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "Lewes Board of Public Works Electric",
      slug: "lewes-bpw-electric",
      category: "UTILITY_ELECTRIC",
      description: "Lewes Board of Public Works electric account; confirm service availability by address",
      website: "https://www.lewesbpwde.gov",
      states: ["DE"],
      zipCodes: ["19958"],
      popularityScore: 56,
      tags: ["electric", "municipal-utility", "lewes", "address-check"],
    }),
  },
  {
    providerName: "Municipal Services Commission of the City of New Castle Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://newcastlemsc.delaware.gov",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact New Castle ZIP from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "Municipal Services Commission of the City of New Castle Electric",
      slug: "new-castle-msc-electric",
      category: "UTILITY_ELECTRIC",
      description: "New Castle municipal electric account; confirm service availability by address",
      website: "https://newcastlemsc.delaware.gov",
      states: ["DE"],
      zipCodes: ["19720"],
      popularityScore: 56,
      tags: ["electric", "municipal-utility", "new-castle", "address-check"],
    }),
  },
  {
    providerName: "Town of Middletown Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.middletown.delaware.gov",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Middletown ZIPs from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "Town of Middletown Electric",
      slug: "town-of-middletown-electric",
      category: "UTILITY_ELECTRIC",
      description: "Middletown municipal electric account; confirm service availability by address",
      website: "https://www.middletown.delaware.gov",
      states: ["DE"],
      zipCodes: ["19709", "19734"],
      popularityScore: 58,
      tags: ["electric", "municipal-utility", "middletown", "address-check"],
    }),
  },
  {
    providerName: "Town of Smyrna Electric",
    states: ["DE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://smyrna.delaware.gov",
    coverageModel: "zip_prefix",
    note: "Real municipal electric utility; modeled with exact Smyrna ZIP from Batch 1 and address confirmation language.",
    seedRecord: stateSeed({
      name: "Town of Smyrna Electric",
      slug: "town-of-smyrna-electric",
      category: "UTILITY_ELECTRIC",
      description: "Smyrna municipal electric account; confirm service availability by address",
      website: "https://smyrna.delaware.gov",
      states: ["DE"],
      zipCodes: ["19977"],
      popularityScore: 56,
      tags: ["electric", "municipal-utility", "smyrna", "address-check"],
    }),
  },
  {
    providerName: "Florida City Gas",
    states: ["FL"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.floridacitygas.com",
    coverageModel: "zip_prefix",
    note: "Real gas utility; modeled with cautious South Florida ZIP prefixes and address confirmation language.",
    seedRecord: stateSeed({
      name: "Florida City Gas",
      slug: "florida-city-gas",
      category: "UTILITY_GAS",
      description: "South Florida natural gas utility account; confirm service availability by address",
      website: "https://www.floridacitygas.com",
      states: ["FL"],
      zipCodes: ["330", "331", "332", "333", "334", "349"],
      popularityScore: 70,
      tags: ["gas", "utility", "south-florida", "address-check"],
    }),
  },
];

const PROVIDER_ADDITIONS_V1_BATCH2A_CATALOG: StateProviderCatalogEntry[] = [
  batch2AUtilityAccountEntry({
    providerName: "City and Borough of Juneau Water Utility",
    state: "AK",
    category: "UTILITY_WATER",
    officialUrl: "https://juneau.org",
    slug: "juneau-water-utility",
    zipCodes: ["998"],
    popularityScore: 58,
    localTags: ["juneau", "alaska"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "College & Golden Heart Utilities Water",
    state: "AK",
    category: "UTILITY_WATER",
    officialUrl: "https://www.mywater.us/alaska/about-us-menu",
    slug: "college-golden-heart-utilities-water",
    zipCodes: ["997"],
    popularityScore: 58,
    localTags: ["fairbanks", "alaska"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Huntsville Water Pollution Control",
    state: "AL",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.huntsvilleal.gov",
    slug: "huntsville-water-pollution-control",
    zipCodes: ["357", "358"],
    popularityScore: 62,
    localTags: ["wastewater", "huntsville", "alabama"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Jefferson County Environmental Services Department",
    state: "AL",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.jeffcoes.org",
    slug: "jefferson-county-environmental-services",
    zipCodes: ["350", "351", "352"],
    popularityScore: 64,
    localTags: ["wastewater", "jefferson-county", "alabama"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Tuscaloosa Water",
    state: "AL",
    category: "UTILITY_WATER",
    officialUrl: "https://www.tuscaloosa.com",
    slug: "tuscaloosa-water",
    zipCodes: ["354"],
    popularityScore: 62,
    localTags: ["tuscaloosa", "alabama"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Madison County Water Department",
    state: "AL",
    category: "UTILITY_WATER",
    officialUrl: "https://www.madisoncountyal.gov/departments/water-department",
    slug: "madison-county-water",
    zipCodes: ["357", "358"],
    popularityScore: 62,
    localTags: ["madison-county", "alabama"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Mobile Area Water and Sewer System Water",
    state: "AL",
    category: "UTILITY_WATER",
    officialUrl: "https://www.mawss.com",
    slug: "mawss-water",
    zipCodes: ["366"],
    popularityScore: 64,
    localTags: ["mobile", "alabama"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Little Rock Water Reclamation Authority",
    state: "AR",
    category: "UTILITY_SEWER",
    officialUrl: "https://lrwra.com",
    slug: "little-rock-water-reclamation",
    zipCodes: ["722"],
    popularityScore: 64,
    localTags: ["wastewater", "little-rock", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Springdale Water Utilities Wastewater",
    state: "AR",
    category: "UTILITY_SEWER",
    officialUrl: "https://springdalewater.com",
    slug: "springdale-water-utilities-wastewater",
    zipCodes: ["727"],
    popularityScore: 60,
    localTags: ["wastewater", "springdale", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Bentonville Water Utilities",
    state: "AR",
    category: "UTILITY_WATER",
    officialUrl: "https://www.bentonvillear.com",
    slug: "bentonville-water-utilities",
    zipCodes: ["727"],
    popularityScore: 60,
    localTags: ["bentonville", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Fayetteville Water and Sewer",
    state: "AR",
    category: "UTILITY_WATER",
    officialUrl: "https://www.fayetteville-ar.gov",
    slug: "fayetteville-water",
    zipCodes: ["727"],
    popularityScore: 62,
    localTags: ["fayetteville", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Fort Smith Utilities Water",
    state: "AR",
    category: "UTILITY_WATER",
    officialUrl: "https://www.fortsmithar.gov",
    slug: "fort-smith-water",
    zipCodes: ["729"],
    popularityScore: 62,
    localTags: ["fort-smith", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Jonesboro City Water and Light Water",
    state: "AR",
    category: "UTILITY_WATER",
    officialUrl: "https://www.jonesborocwl.org",
    slug: "jonesboro-cwl-water",
    zipCodes: ["724"],
    popularityScore: 60,
    localTags: ["jonesboro", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Rogers Water Utilities",
    state: "AR",
    category: "UTILITY_WATER",
    officialUrl: "https://www.rwu.org",
    slug: "rogers-water-utilities",
    zipCodes: ["727"],
    popularityScore: 60,
    localTags: ["rogers", "arkansas"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Pima County Regional Wastewater Reclamation Department",
    state: "AZ",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.pima.gov/wastewater",
    slug: "pima-county-wastewater",
    zipCodes: ["856", "857"],
    popularityScore: 64,
    localTags: ["wastewater", "pima-county", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Chandler Water",
    state: "AZ",
    category: "UTILITY_WATER",
    officialUrl: "https://www.chandleraz.gov/residents/water",
    slug: "chandler-water",
    zipCodes: ["852"],
    popularityScore: 62,
    localTags: ["chandler", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Tempe Water Services",
    state: "AZ",
    category: "UTILITY_WATER",
    officialUrl: "https://www.tempe.gov",
    slug: "tempe-water-services",
    zipCodes: ["852"],
    popularityScore: 62,
    localTags: ["tempe", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Glendale Water Services",
    state: "AZ",
    category: "UTILITY_WATER",
    officialUrl: "https://www.glendaleaz.com/live/city_services/water_services",
    slug: "glendale-water-services",
    zipCodes: ["853"],
    popularityScore: 62,
    localTags: ["glendale", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Scottsdale Water",
    state: "AZ",
    category: "UTILITY_WATER",
    officialUrl: "https://www.scottsdaleaz.gov/water",
    slug: "scottsdale-water",
    zipCodes: ["852"],
    popularityScore: 62,
    localTags: ["scottsdale", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Town of Gilbert Water",
    state: "AZ",
    category: "UTILITY_WATER",
    officialUrl: "https://www.gilbertaz.gov/departments/public-works/water",
    slug: "gilbert-water",
    zipCodes: ["852"],
    popularityScore: 62,
    localTags: ["gilbert", "arizona"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Fresno Utilities Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.fresno.gov/publicutilities/",
    slug: "fresno-water",
    zipCodes: ["937"],
    popularityScore: 66,
    localTags: ["fresno", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Sacramento Department of Utilities Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.cityofsacramento.gov/utilities",
    slug: "sacramento-water",
    zipCodes: ["958"],
    popularityScore: 66,
    localTags: ["sacramento", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of San Diego Public Utilities Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.sandiego.gov/public-utilities",
    slug: "san-diego-public-utilities-water",
    zipCodes: ["919", "920", "921"],
    popularityScore: 70,
    localTags: ["san-diego", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "East Bay Municipal Utility District Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.ebmud.com",
    slug: "ebmud-water",
    zipCodes: ["945", "946", "947", "948"],
    popularityScore: 70,
    localTags: ["east-bay", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Long Beach Utilities Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.longbeach.gov/utilityservices/",
    slug: "long-beach-utilities-water",
    zipCodes: ["908"],
    popularityScore: 66,
    localTags: ["long-beach", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "San Jose Water",
    state: "CA",
    category: "UTILITY_WATER",
    officialUrl: "https://www.sjwater.com",
    slug: "san-jose-water",
    zipCodes: ["951"],
    popularityScore: 68,
    localTags: ["san-jose", "california"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Aurora Water",
    state: "CO",
    category: "UTILITY_WATER",
    officialUrl: "https://www.auroragov.org/residents/water",
    slug: "aurora-water",
    zipCodes: ["800", "801"],
    popularityScore: 64,
    localTags: ["aurora", "colorado"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "City of Boulder Water Utilities",
    state: "CO",
    category: "UTILITY_WATER",
    officialUrl: "https://bouldercolorado.gov/services/water-utilities",
    slug: "boulder-water-utilities",
    zipCodes: ["803"],
    popularityScore: 62,
    localTags: ["boulder", "colorado"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Colorado Springs Utilities Water",
    state: "CO",
    category: "UTILITY_WATER",
    officialUrl: "https://www.csu.org",
    slug: "colorado-springs-utilities-water",
    zipCodes: ["809"],
    popularityScore: 66,
    localTags: ["colorado-springs", "colorado"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Fort Collins Utilities Water",
    state: "CO",
    category: "UTILITY_WATER",
    officialUrl: "https://www.fcgov.com/utilities",
    slug: "fort-collins-utilities-water",
    zipCodes: ["805"],
    popularityScore: 62,
    localTags: ["fort-collins", "colorado"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Bridgeport Water Pollution Control Authority",
    state: "CT",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.bridgeportct.gov/government/departments/water-pollution-control-authority-wpca",
    slug: "bridgeport-wpca",
    zipCodes: ["066"],
    popularityScore: 60,
    localTags: ["wastewater", "bridgeport", "connecticut"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Greater New Haven Water Pollution Control Authority",
    state: "CT",
    category: "UTILITY_SEWER",
    officialUrl: "https://gnhwpca.com",
    slug: "gnhwpca",
    zipCodes: ["064", "065"],
    popularityScore: 62,
    localTags: ["wastewater", "new-haven", "connecticut"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Stamford Water Pollution Control Authority",
    state: "CT",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.stamfordct.gov/government/operations/water-pollution-control-authority",
    slug: "stamford-wpca",
    zipCodes: ["069"],
    popularityScore: 60,
    localTags: ["wastewater", "stamford", "connecticut"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Metropolitan District Commission",
    state: "CT",
    category: "UTILITY_WATER",
    officialUrl: "https://themdc.org",
    slug: "mdc-ct-water",
    zipCodes: ["060", "061"],
    popularityScore: 64,
    localTags: ["hartford", "connecticut"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "South Central Connecticut Regional Water Authority",
    state: "CT",
    category: "UTILITY_WATER",
    officialUrl: "https://www.rwater.com",
    slug: "regional-water-authority-ct",
    zipCodes: ["064", "065"],
    popularityScore: 64,
    localTags: ["new-haven", "connecticut"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Kent County Wastewater Division",
    state: "DE",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.kentcountyde.gov/My-Government/Departments/Public-Works",
    slug: "kent-county-wastewater",
    zipCodes: ["199"],
    popularityScore: 58,
    localTags: ["wastewater", "kent-county", "delaware"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "New Castle County Sewer",
    state: "DE",
    category: "UTILITY_SEWER",
    officialUrl: "https://www.newcastlede.gov",
    slug: "new-castle-county-sewer",
    zipCodes: ["197", "198"],
    popularityScore: 62,
    localTags: ["wastewater", "new-castle-county", "delaware"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Sussex County Environmental Services",
    state: "DE",
    category: "UTILITY_SEWER",
    officialUrl: "https://sussexcountyde.gov/sewer-water",
    slug: "sussex-county-sewer",
    zipCodes: ["199"],
    popularityScore: 58,
    localTags: ["wastewater", "sussex-county", "delaware"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Wilmington Water Utility",
    state: "DE",
    category: "UTILITY_WATER",
    officialUrl: "https://www.wilmingtondewater.gov",
    slug: "wilmington-water-utility",
    zipCodes: ["198"],
    popularityScore: 60,
    localTags: ["wilmington", "delaware"],
  }),
  batch2AUtilityAccountEntry({
    providerName: "Hillsborough County Water Resources",
    state: "FL",
    category: "UTILITY_WATER",
    officialUrl: "https://hcfl.gov",
    slug: "hillsborough-county-water",
    zipCodes: ["335", "336"],
    popularityScore: 66,
    localTags: ["hillsborough-county", "florida"],
  }),
];

export const STATE_PROVIDER_COMPLETENESS_CATALOG: StateProviderCatalogEntry[] = [
  {
    providerName: "MAX Transit",
    states: ["AL"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://maxtransit.org",
    coverageModel: "zip_prefix",
    note: "Birmingham-area transit provider missing from the seed; modeled with Birmingham metro ZIP prefixes.",
    seedRecord: stateSeed({
      name: "MAX Transit",
      slug: "max-transit-al",
      category: "TRANSPORTATION_TRANSIT",
      description: "Birmingham-Jefferson County MAX bus transit service",
      website: "https://maxtransit.org",
      states: ["AL"],
      zipCodes: ["350", "351", "352"],
      popularityScore: 66,
      tags: ["transit", "bus", "birmingham"],
    }),
  },
  {
    providerName: "People Mover",
    states: ["AK"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.muni.org/Departments/transit/PeopleMover/pages/mapsandstops.aspx",
    coverageModel: "zip_prefix",
    note: "Anchorage People Mover is the largest public transit provider in Alaska and was not in seed.",
    seedRecord: stateSeed({
      name: "People Mover",
      slug: "people-mover-ak",
      category: "TRANSPORTATION_TRANSIT",
      description: "Municipality of Anchorage public transit service",
      website: "https://www.muni.org/Departments/transit/PeopleMover/pages/mapsandstops.aspx",
      states: ["AK"],
      zipCodes: ["995"],
      popularityScore: 68,
      tags: ["transit", "bus", "anchorage"],
    }),
  },
  {
    providerName: "Alaska Communications",
    states: ["AK"],
    category: "UTILITY_INTERNET",
    officialUrl: "https://www.alaskacommunications.com/Residential",
    coverageModel: "live_address",
    note: "Alaska Communications is a major Alaska ISP/voice provider. The official surface is address-qualified rather than ZIP-complete.",
    legacyNames: ["ACS"],
  },
  {
    providerName: "Valley Metro",
    states: ["AZ"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.valleymetro.org/maps-schedules",
    coverageModel: "zip_prefix",
    note: "Phoenix-area Valley Metro was absent from seed and is modeled with core metro ZIP prefixes.",
    seedRecord: stateSeed({
      name: "Valley Metro",
      slug: "valley-metro-az",
      category: "TRANSPORTATION_TRANSIT",
      description: "Phoenix metro bus and light rail transit network",
      website: "https://www.valleymetro.org/maps-schedules",
      states: ["AZ"],
      zipCodes: ["850", "851", "852", "853"],
      popularityScore: 78,
      tags: ["transit", "bus", "rail", "phoenix"],
    }),
  },
  {
    providerName: "Entergy Arkansas",
    states: ["AR"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.entergy-arkansas.com",
    coverageModel: "state",
    note: "Major Arkansas electric utility identified in state rules but missing from seed.",
    seedRecord: stateSeed({
      name: "Entergy Arkansas",
      slug: "entergy-ar",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving much of Arkansas",
      website: "https://www.entergy-arkansas.com",
      states: ["AR"],
      popularityScore: 84,
      tags: ["electric", "utility"],
    }),
  },
  {
    providerName: "San Diego Gas & Electric",
    states: ["CA"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.sdge.com/landservices",
    coverageModel: "zip_prefix",
    note: "SDG&E serves San Diego County and parts of southern Orange County; modeled conservatively with southern California ZIP prefixes.",
    seedRecord: stateSeed({
      name: "San Diego Gas & Electric",
      slug: "sdge",
      category: "UTILITY_ELECTRIC",
      description: "Electric and gas utility for San Diego County and nearby coastal communities",
      website: "https://www.sdge.com",
      states: ["CA"],
      zipCodes: ["919", "920", "921"],
      popularityScore: 86,
      tags: ["electric", "gas", "utility", "san-diego"],
    }),
  },
  {
    providerName: "RTD Denver",
    states: ["CO"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.rtd-denver.com/system-map",
    coverageModel: "zip_prefix",
    note: "Regional Transportation District is the core transit provider for Denver metro.",
    seedRecord: stateSeed({
      name: "RTD Denver",
      slug: "rtd-denver",
      category: "TRANSPORTATION_TRANSIT",
      description: "Regional Transportation District bus and rail service in Denver metro",
      website: "https://www.rtd-denver.com/system-map",
      states: ["CO"],
      zipCodes: ["800", "801", "802", "803", "804"],
      popularityScore: 76,
      tags: ["transit", "bus", "rail", "denver"],
    }),
  },
  {
    providerName: "United Illuminating",
    states: ["CT"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.uinet.com/ourcompany/whoweare/servicearea",
    coverageModel: "zip_prefix",
    note: "United Illuminating covers southern Connecticut and is a material seed gap for CT.",
    seedRecord: stateSeed({
      name: "United Illuminating",
      slug: "ui-ct",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving southern Connecticut communities",
      website: "https://www.uinet.com",
      states: ["CT"],
      zipCodes: ["064", "065", "066", "067", "068"],
      popularityScore: 78,
      tags: ["electric", "utility", "connecticut"],
    }),
  },
  {
    providerName: "Connecticut Natural Gas",
    states: ["CT"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.cngcorp.com",
    coverageModel: "zip_prefix",
    note: "Connecticut Natural Gas is a real utility account provider, but remains catalog-only until cleaner service-area ZIPs are confirmed.",
  },
  {
    providerName: "DART First State",
    states: ["DE"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://dartfirststate.com/map/",
    coverageModel: "state",
    note: "DART First State operates statewide bus and paratransit service in Delaware.",
    seedRecord: stateSeed({
      name: "DART First State",
      slug: "dart-first-state",
      category: "TRANSPORTATION_TRANSIT",
      description: "Statewide Delaware bus and paratransit network",
      website: "https://dartfirststate.com",
      states: ["DE"],
      popularityScore: 74,
      tags: ["transit", "bus", "delaware"],
    }),
  },
  {
    providerName: "DC Streetcar",
    states: ["DC"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://dcstreetcar.com",
    coverageModel: "zip_prefix",
    note: "DC Streetcar adds a district-specific transit option beyond WMATA.",
    seedRecord: stateSeed({
      name: "DC Streetcar",
      slug: "dc-streetcar",
      category: "TRANSPORTATION_TRANSIT",
      description: "District streetcar transit service on the H Street/Benning corridor",
      website: "https://dcstreetcar.com",
      states: ["DC"],
      zipCodes: ["200"],
      popularityScore: 62,
      tags: ["transit", "streetcar", "dc"],
    }),
  },
  {
    providerName: "Tampa Electric",
    states: ["FL"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.tampaelectric.com/economicdevelopment/serviceareaandreliability/",
    coverageModel: "zip_prefix",
    note: "Tampa Electric is a major missing Florida electric provider with a clear Tampa Bay service area.",
    seedRecord: stateSeed({
      name: "Tampa Electric",
      slug: "tampa-electric",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving the Tampa Bay area",
      website: "https://www.tampaelectric.com",
      states: ["FL"],
      zipCodes: ["335", "336", "337", "338", "346"],
      popularityScore: 80,
      tags: ["electric", "utility", "tampa"],
    }),
  },
  {
    providerName: "Atlanta Gas Light",
    states: ["GA"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.atlantagaslight.com",
    coverageModel: "state",
    note: "Atlanta Gas Light remains a key Georgia gas infrastructure provider missing from seed.",
    seedRecord: stateSeed({
      name: "Atlanta Gas Light",
      slug: "atlanta-gas-light",
      category: "UTILITY_GAS",
      description: "Georgia natural gas distribution utility and pipeline operator",
      website: "https://www.atlantagaslight.com",
      states: ["GA"],
      popularityScore: 78,
      tags: ["gas", "utility", "georgia"],
    }),
  },
  {
    providerName: "Skyline",
    states: ["HI"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.honolulu.gov/skyline",
    coverageModel: "zip_prefix",
    note: "Honolulu Skyline adds a rail-specific transit surface beyond TheBus.",
    seedRecord: stateSeed({
      name: "Skyline",
      slug: "skyline-hi",
      category: "TRANSPORTATION_TRANSIT",
      description: "Honolulu rail transit service on Oahu",
      website: "https://www.honolulu.gov/skyline",
      states: ["HI"],
      zipCodes: ["968"],
      popularityScore: 64,
      tags: ["transit", "rail", "honolulu"],
    }),
  },
  {
    providerName: "Idaho Power",
    states: ["ID"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.idahopower.com",
    coverageModel: "state",
    note: "Idaho Power is the dominant investor-owned electric utility in southern Idaho and a major catalog gap.",
    seedRecord: stateSeed({
      name: "Idaho Power",
      slug: "idaho-power",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving southern Idaho and eastern Oregon",
      website: "https://www.idahopower.com",
      states: ["ID"],
      popularityScore: 84,
      tags: ["electric", "utility", "idaho"],
    }),
  },
  {
    providerName: "Ameren Illinois",
    states: ["IL"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.ameren.com/illinois/about",
    coverageModel: "state",
    note: "Ameren Illinois is the major downstate Illinois electric utility and was not represented directly in seed.",
    seedRecord: stateSeed({
      name: "Ameren Illinois",
      slug: "ameren-il",
      category: "UTILITY_ELECTRIC",
      description: "Electric and gas utility serving central and southern Illinois",
      website: "https://www.ameren.com/illinois",
      states: ["IL"],
      popularityScore: 82,
      tags: ["electric", "gas", "utility", "illinois"],
    }),
  },
  {
    providerName: "Indiana Michigan Power",
    states: ["IN"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.indianamichiganpower.com",
    coverageModel: "zip_prefix",
    note: "Indiana Michigan Power is a large AEP utility missing from Indiana coverage.",
    seedRecord: stateSeed({
      name: "Indiana Michigan Power",
      slug: "indiana-michigan-power",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving northern and eastern Indiana",
      website: "https://www.indianamichiganpower.com",
      states: ["IN"],
      zipCodes: ["460", "461", "463", "465", "466", "467", "468", "469"],
      popularityScore: 76,
      tags: ["electric", "utility", "indiana"],
    }),
  },
  {
    providerName: "Alliant Energy",
    states: ["IA", "WI"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.alliantenergy.com/who-we-are/communities-we-serve",
    coverageModel: "state",
    note: "Alliant Energy is a major Iowa/Wisconsin utility called out in state rules but missing from seed.",
    seedRecord: stateSeed({
      name: "Alliant Energy",
      slug: "alliant-energy",
      category: "UTILITY_ELECTRIC",
      description: "Electric and gas utility serving Iowa and Wisconsin communities",
      website: "https://www.alliantenergy.com",
      states: ["IA", "WI"],
      popularityScore: 82,
      tags: ["electric", "gas", "utility"],
    }),
  },
  {
    providerName: "RideKC",
    states: ["KS", "MO"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://ridekc.org/rider-guide/system-map",
    coverageModel: "zip_prefix",
    note: "Kansas City regional transit system missing from both Kansas and Missouri seed surfaces.",
    seedRecord: stateSeed({
      name: "RideKC",
      slug: "ridekc",
      category: "TRANSPORTATION_TRANSIT",
      description: "Kansas City regional bus and streetcar transit network",
      website: "https://ridekc.org",
      states: ["KS", "MO"],
      zipCodes: ["640", "641", "660", "661", "662"],
      popularityScore: 72,
      tags: ["transit", "bus", "streetcar", "kansas-city"],
    }),
  },
  {
    providerName: "Louisville Gas & Electric",
    states: ["KY"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://lge-ku.com",
    coverageModel: "zip_prefix",
    note: "LG&E is the core Louisville-area utility and was missing from Kentucky coverage.",
    seedRecord: stateSeed({
      name: "Louisville Gas & Electric",
      slug: "lge-ky",
      category: "UTILITY_ELECTRIC",
      description: "Electric and gas utility serving Louisville and surrounding Kentucky communities",
      website: "https://lge-ku.com",
      states: ["KY"],
      zipCodes: ["400", "401", "402"],
      popularityScore: 80,
      tags: ["electric", "gas", "utility", "louisville"],
    }),
  },
  {
    providerName: "Capital Area Transit System",
    states: ["LA"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.brcats.com",
    coverageModel: "zip_prefix",
    note: "Baton Rouge CATS expands Louisiana transit beyond the New Orleans region already in seed.",
    legacyNames: ["CATS Baton Rouge"],
    seedRecord: stateSeed({
      name: "Capital Area Transit System",
      slug: "cats-la",
      category: "TRANSPORTATION_TRANSIT",
      description: "Baton Rouge bus transit network",
      website: "https://www.brcats.com",
      states: ["LA"],
      zipCodes: ["707", "708"],
      popularityScore: 64,
      tags: ["transit", "bus", "baton-rouge"],
    }),
  },
  {
    providerName: "Greater Portland METRO",
    states: ["ME"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://gpmetro.org",
    coverageModel: "zip_prefix",
    note: "Greater Portland METRO adds a missing Maine transit provider with a compact service footprint.",
    seedRecord: stateSeed({
      name: "Greater Portland METRO",
      slug: "gpmetro-me",
      category: "TRANSPORTATION_TRANSIT",
      description: "Greater Portland bus transit network",
      website: "https://gpmetro.org",
      states: ["ME"],
      zipCodes: ["040", "041"],
      popularityScore: 64,
      tags: ["transit", "bus", "portland-maine"],
    }),
  },
  {
    providerName: "MTA Maryland",
    states: ["MD"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.mta.maryland.gov/transit-maps",
    coverageModel: "zip_prefix",
    note: "Maryland Transit Administration adds a missing Baltimore-centric transit surface.",
    seedRecord: stateSeed({
      name: "MTA Maryland",
      slug: "mta-md",
      category: "TRANSPORTATION_TRANSIT",
      description: "Maryland Transit Administration local, light rail, subway, MARC, and commuter bus network",
      website: "https://www.mta.maryland.gov",
      states: ["MD"],
      zipCodes: ["206", "207", "208", "209", "210", "211", "212", "214", "217"],
      popularityScore: 74,
      tags: ["transit", "bus", "rail", "maryland"],
    }),
  },
  {
    providerName: "Massachusetts Water Resources Authority",
    states: ["MA"],
    category: "UTILITY_WATER",
    officialUrl: "https://www.mwra.com",
    coverageModel: "zip_prefix",
    note: "MWRA covers Boston-region wholesale water/sewer service and adds a missing Massachusetts water surface.",
    legacyNames: ["MWRA"],
    seedRecord: stateSeed({
      name: "Massachusetts Water Resources Authority",
      slug: "mwra-ma",
      category: "UTILITY_WATER",
      description: "Boston-region water and wastewater authority",
      website: "https://www.mwra.com",
      states: ["MA"],
      zipCodes: ["017", "018", "019", "020", "021", "022", "023", "024", "027"],
      popularityScore: 68,
      tags: ["water", "utility", "boston"],
    }),
  },
  {
    providerName: "SMART",
    states: ["MI"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.smartbus.org/Routes-Schedules/System-Map",
    coverageModel: "zip_prefix",
    note: "Suburban Mobility Authority for Regional Transportation adds the Detroit suburban network missing from seed.",
    seedRecord: stateSeed({
      name: "SMART",
      slug: "smart-mi",
      category: "TRANSPORTATION_TRANSIT",
      description: "Detroit suburban bus transit network",
      website: "https://www.smartbus.org",
      states: ["MI"],
      zipCodes: ["480", "481", "482", "483"],
      popularityScore: 72,
      tags: ["transit", "bus", "detroit"],
    }),
  },
  {
    providerName: "Minnesota Energy Resources",
    states: ["MN"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.minnesotaenergyresources.com",
    coverageModel: "state",
    note: "Minnesota Energy Resources adds a missing statewide gas utility surface beyond CenterPoint.",
    seedRecord: stateSeed({
      name: "Minnesota Energy Resources",
      slug: "mn-energy-resources",
      category: "UTILITY_GAS",
      description: "Natural gas utility serving Minnesota communities",
      website: "https://www.minnesotaenergyresources.com",
      states: ["MN"],
      popularityScore: 74,
      tags: ["gas", "utility", "minnesota"],
    }),
  },
  {
    providerName: "Coast Transit Authority",
    states: ["MS"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://coasttransit.com",
    coverageModel: "zip_prefix",
    note: "Mississippi Gulf Coast transit provider missing from seed.",
    seedRecord: stateSeed({
      name: "Coast Transit Authority",
      slug: "coast-transit-ms",
      category: "TRANSPORTATION_TRANSIT",
      description: "Mississippi Gulf Coast regional bus transit service",
      website: "https://coasttransit.com",
      states: ["MS"],
      zipCodes: ["395"],
      popularityScore: 60,
      tags: ["transit", "bus", "gulf-coast"],
    }),
  },
  {
    providerName: "Mountain Line",
    states: ["MT"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://mountainline.com/system-map/",
    coverageModel: "zip_prefix",
    note: "Missoula-area transit addition for Montana.",
    seedRecord: stateSeed({
      name: "Mountain Line",
      slug: "mountain-line-mt",
      category: "TRANSPORTATION_TRANSIT",
      description: "Missoula urban transit district bus service",
      website: "https://mountainline.com",
      states: ["MT"],
      zipCodes: ["598"],
      popularityScore: 58,
      tags: ["transit", "bus", "missoula"],
    }),
  },
  {
    providerName: "Omaha Public Power District",
    states: ["NE"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.oppd.com/about/service-area/",
    coverageModel: "zip_prefix",
    note: "OPPD is a major Nebraska public-power provider missing from seed.",
    legacyNames: ["OPPD"],
    seedRecord: stateSeed({
      name: "Omaha Public Power District",
      slug: "oppd-ne",
      category: "UTILITY_ELECTRIC",
      description: "Public electric utility serving Omaha and eastern Nebraska",
      website: "https://www.oppd.com",
      states: ["NE"],
      zipCodes: ["680", "681"],
      popularityScore: 78,
      tags: ["electric", "utility", "omaha"],
    }),
  },
  {
    providerName: "RTC Washoe",
    states: ["NV"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://rtcwashoe.com/public-transportation/system-map/",
    coverageModel: "zip_prefix",
    note: "RTC Washoe adds northern Nevada transit coverage beyond Las Vegas-area service already in seed.",
    seedRecord: stateSeed({
      name: "RTC Washoe",
      slug: "rtc-washoe",
      category: "TRANSPORTATION_TRANSIT",
      description: "Reno-Sparks regional bus transit network",
      website: "https://rtcwashoe.com",
      states: ["NV"],
      zipCodes: ["894", "895"],
      popularityScore: 62,
      tags: ["transit", "bus", "reno", "sparks"],
    }),
  },
  {
    providerName: "COAST",
    states: ["NH"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://coastbus.org/schedules",
    coverageModel: "zip_prefix",
    note: "COAST adds a New Hampshire transit provider for the Seacoast region.",
    seedRecord: stateSeed({
      name: "COAST",
      slug: "coast-nh",
      category: "TRANSPORTATION_TRANSIT",
      description: "Seacoast regional fixed-route and regional bus transit service",
      website: "https://coastbus.org",
      states: ["NH"],
      zipCodes: ["038"],
      popularityScore: 58,
      tags: ["transit", "bus", "new-hampshire", "seacoast"],
    }),
  },
  {
    providerName: "PATCO Speedline",
    states: ["NJ", "PA"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.drpa.org/patco/index.html",
    coverageModel: "zip_prefix",
    note: "PATCO adds a missing NJ/PA rail corridor provider between South Jersey and Philadelphia.",
    legacyNames: ["PATCO"],
    seedRecord: stateSeed({
      name: "PATCO Speedline",
      slug: "patco",
      category: "TRANSPORTATION_TRANSIT",
      description: "Rapid transit line between South Jersey and Center City Philadelphia",
      website: "https://www.drpa.org/patco/index.html",
      states: ["NJ", "PA"],
      zipCodes: ["080", "081", "191"],
      popularityScore: 74,
      tags: ["transit", "rail", "philadelphia", "south-jersey"],
    }),
  },
  {
    providerName: "ABQ RIDE",
    states: ["NM"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.cabq.gov/transit/routes-and-schedules/system-map",
    coverageModel: "zip_prefix",
    note: "Albuquerque transit addition for New Mexico.",
    seedRecord: stateSeed({
      name: "ABQ RIDE",
      slug: "abq-ride",
      category: "TRANSPORTATION_TRANSIT",
      description: "Albuquerque bus rapid transit and local bus service",
      website: "https://www.cabq.gov/transit",
      states: ["NM"],
      zipCodes: ["870", "871"],
      popularityScore: 64,
      tags: ["transit", "bus", "albuquerque"],
    }),
  },
  {
    providerName: "PSEG Long Island",
    states: ["NY"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.psegliny.com",
    coverageModel: "zip_prefix",
    note: "Long Island electric utility surface missing from the seed's New York coverage.",
    legacyNames: ["PSEG"],
    seedRecord: stateSeed({
      name: "PSEG Long Island",
      slug: "pseg-li",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility service for Nassau and Suffolk counties",
      website: "https://www.psegliny.com",
      states: ["NY"],
      zipCodes: ["117", "118", "119"],
      popularityScore: 80,
      tags: ["electric", "utility", "long-island"],
    }),
  },
  {
    providerName: "Piedmont Natural Gas",
    states: ["NC", "SC"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.piedmontng.com",
    coverageModel: "state",
    note: "Piedmont Natural Gas is a major Carolinas utility missing from the seed surface.",
    seedRecord: stateSeed({
      name: "Piedmont Natural Gas",
      slug: "piedmont-carolinas",
      category: "UTILITY_GAS",
      description: "Natural gas utility serving North Carolina and South Carolina communities",
      website: "https://www.piedmontng.com",
      states: ["NC", "SC"],
      popularityScore: 82,
      tags: ["gas", "utility", "carolinas"],
    }),
  },
  {
    providerName: "Montana-Dakota Utilities",
    states: ["ND", "SD", "WY"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.montana-dakota.com",
    coverageModel: "state",
    note: "Montana-Dakota Utilities closes a multi-state utility gap across the northern plains.",
    legacyNames: ["MDU"],
    seedRecord: stateSeed({
      name: "Montana-Dakota Utilities",
      slug: "mdu",
      category: "UTILITY_GAS",
      description: "Gas and electric utility serving parts of the Dakotas and Wyoming",
      website: "https://www.montana-dakota.com",
      states: ["ND", "SD", "WY"],
      popularityScore: 78,
      tags: ["gas", "electric", "utility"],
    }),
  },
  {
    providerName: "Ohio Turnpike E-ZPass",
    states: ["OH"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.ezpassoh.com",
    coverageModel: "polygon",
    note: "Ohio toll coverage is corridor-driven rather than ZIP-clean, so this remains catalog-only until polygon modeling lands.",
  },
  {
    providerName: "EMBARK",
    states: ["OK"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://embarkok.com/system-map/",
    coverageModel: "zip_prefix",
    note: "Oklahoma City EMBARK adds a missing Oklahoma transit provider.",
    seedRecord: stateSeed({
      name: "EMBARK",
      slug: "embark-ok",
      category: "TRANSPORTATION_TRANSIT",
      description: "Oklahoma City metro transit network",
      website: "https://embarkok.com",
      states: ["OK"],
      zipCodes: ["730", "731"],
      popularityScore: 64,
      tags: ["transit", "bus", "oklahoma-city"],
    }),
  },
  {
    providerName: "Pacific Power",
    states: ["OR"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.pacificpower.net/about.html",
    coverageModel: "state",
    note: "Pacific Power is a major Oregon utility missing from seed.",
    seedRecord: stateSeed({
      name: "Pacific Power",
      slug: "pacific-power-or",
      category: "UTILITY_ELECTRIC",
      description: "Electric utility serving Oregon communities outside the Portland General Electric footprint",
      website: "https://www.pacificpower.net",
      states: ["OR"],
      popularityScore: 82,
      tags: ["electric", "utility", "oregon"],
    }),
  },
  {
    providerName: "Columbia Gas of Pennsylvania",
    states: ["PA"],
    category: "UTILITY_GAS",
    officialUrl: "https://www.columbiagaspa.com",
    coverageModel: "state",
    note: "Major Pennsylvania gas utility called out in state rules but missing from seed.",
    seedRecord: stateSeed({
      name: "Columbia Gas of Pennsylvania",
      slug: "columbia-gas-pa",
      category: "UTILITY_GAS",
      description: "Natural gas utility serving Pennsylvania communities",
      website: "https://www.columbiagaspa.com",
      states: ["PA"],
      popularityScore: 78,
      tags: ["gas", "utility", "pennsylvania"],
    }),
  },
  {
    providerName: "RIPTA",
    states: ["RI"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://ripta.com/statewide-system-map/",
    coverageModel: "state",
    note: "RIPTA provides statewide Rhode Island transit service and should exist explicitly in seed.",
    seedRecord: stateSeed({
      name: "RIPTA",
      slug: "ripta",
      category: "TRANSPORTATION_TRANSIT",
      description: "Rhode Island statewide public transit authority",
      website: "https://ripta.com",
      states: ["RI"],
      popularityScore: 76,
      tags: ["transit", "bus", "rhode-island"],
    }),
  },
  {
    providerName: "CARTA",
    states: ["SC"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://ridecarta.com",
    coverageModel: "zip_prefix",
    note: "Charleston Area Regional Transportation Authority adds a South Carolina transit option beyond utility-only coverage.",
    seedRecord: stateSeed({
      name: "CARTA",
      slug: "carta-sc",
      category: "TRANSPORTATION_TRANSIT",
      description: "Charleston-area regional bus transit service",
      website: "https://www.ridecarta.com",
      states: ["SC"],
      zipCodes: ["294"],
      popularityScore: 60,
      tags: ["transit", "bus", "charleston"],
    }),
  },
  {
    providerName: "Sioux Area Metro",
    states: ["SD"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.siouxfalls.gov/sam",
    coverageModel: "zip_prefix",
    note: "Sioux Falls transit surface for South Dakota.",
    seedRecord: stateSeed({
      name: "Sioux Area Metro",
      slug: "sioux-area-metro",
      category: "TRANSPORTATION_TRANSIT",
      description: "Sioux Falls fixed-route bus transit system",
      website: "https://www.siouxfalls.gov/sam",
      states: ["SD"],
      zipCodes: ["570", "571"],
      popularityScore: 58,
      tags: ["transit", "bus", "sioux-falls"],
    }),
  },
  {
    providerName: "Memphis Light, Gas and Water",
    states: ["TN"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.mlgw.com",
    coverageModel: "zip_prefix",
    note: "MLGW is a major missing Memphis-area multi-utility provider.",
    seedRecord: stateSeed({
      name: "Memphis Light, Gas and Water",
      slug: "mlgw",
      category: "UTILITY_ELECTRIC",
      description: "Memphis-area electric, gas, and water utility",
      website: "https://www.mlgw.com",
      states: ["TN"],
      zipCodes: ["380", "381"],
      popularityScore: 78,
      tags: ["electric", "gas", "water", "utility", "memphis"],
    }),
  },
  {
    providerName: "North Texas Tollway Authority",
    states: ["TX"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.ntta.org",
    coverageModel: "zip_prefix",
    note: "NTTA adds a Dallas-Fort Worth toll corridor provider beyond statewide Texas toll tags.",
    legacyNames: ["NTTA"],
    seedRecord: stateSeed({
      name: "North Texas Tollway Authority",
      slug: "ntta",
      category: "TRANSPORTATION_TOLL",
      description: "North Texas regional toll road authority and toll account provider",
      website: "https://www.ntta.org",
      states: ["TX"],
      zipCodes: ["750", "751", "752", "753", "754", "760", "761", "762"],
      popularityScore: 72,
      tags: ["toll", "driving", "dallas-fort-worth"],
    }),
  },
  {
    providerName: "Oncor Electric Delivery",
    states: ["TX"],
    category: "UTILITY_ELECTRIC",
    officialUrl: "https://www.oncor.com",
    coverageModel: "polygon",
    note: "Oncor is a critical Texas delivery utility, but its territory should be polygon-modeled rather than blindly state-scoped.",
  },
  {
    providerName: "Express Pass",
    states: ["UT"],
    category: "TRANSPORTATION_TOLL",
    officialUrl: "https://www.expresspass.utah.gov",
    coverageModel: "polygon",
    note: "Utah Express Pass is corridor-based toll coverage and remains catalog-only until toll polygons land.",
  },
  {
    providerName: "Green Mountain Transit",
    states: ["VT"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://ridegmt.com",
    coverageModel: "zip_prefix",
    note: "Green Mountain Transit adds a Vermont transit provider beyond utility-only coverage.",
    seedRecord: stateSeed({
      name: "Green Mountain Transit",
      slug: "gmt-vt",
      category: "TRANSPORTATION_TRANSIT",
      description: "Central and northwestern Vermont regional transit service",
      website: "https://ridegmt.com",
      states: ["VT"],
      zipCodes: ["054", "056", "057"],
      popularityScore: 60,
      tags: ["transit", "bus", "vermont"],
    }),
  },
  {
    providerName: "Hampton Roads Transit",
    states: ["VA"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://gohrt.com/routes/",
    coverageModel: "zip_prefix",
    note: "HRT expands Virginia transit coverage beyond DC-region rail providers.",
    seedRecord: stateSeed({
      name: "Hampton Roads Transit",
      slug: "hrt-va",
      category: "TRANSPORTATION_TRANSIT",
      description: "Hampton Roads regional bus, ferry, and light rail transit service",
      website: "https://gohrt.com",
      states: ["VA"],
      zipCodes: ["233", "234", "235", "236"],
      popularityScore: 64,
      tags: ["transit", "bus", "light-rail", "hampton-roads"],
    }),
  },
  {
    providerName: "King County Metro",
    states: ["WA"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://kingcounty.gov/en/dept/metro",
    coverageModel: "zip_prefix",
    note: "King County Metro adds the largest Washington transit network beyond Seattle-only utilities.",
    seedRecord: stateSeed({
      name: "King County Metro",
      slug: "king-county-metro",
      category: "TRANSPORTATION_TRANSIT",
      description: "Seattle and King County bus transit network",
      website: "https://kingcounty.gov/en/dept/metro",
      states: ["WA"],
      zipCodes: ["980", "981"],
      popularityScore: 78,
      tags: ["transit", "bus", "seattle"],
    }),
  },
  {
    providerName: "Mountain Line Transit Authority",
    states: ["WV"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://busride.org/routes/",
    coverageModel: "zip_prefix",
    note: "West Virginia transit addition centered on Morgantown.",
    seedRecord: stateSeed({
      name: "Mountain Line Transit Authority",
      slug: "mlta-wv",
      category: "TRANSPORTATION_TRANSIT",
      description: "Morgantown-area fixed-route and regional bus transit",
      website: "https://busride.org",
      states: ["WV"],
      zipCodes: ["265"],
      popularityScore: 56,
      tags: ["transit", "bus", "morgantown"],
    }),
  },
  {
    providerName: "Cheyenne Transit Program",
    states: ["WY"],
    category: "TRANSPORTATION_TRANSIT",
    officialUrl: "https://www.cheyennecity.org/Your-Government/Departments/Public-Works/Transit/Fixed-Route-Service",
    coverageModel: "zip_prefix",
    note: "Cheyenne Transit Program adds a Wyoming public transit surface beyond utilities.",
    seedRecord: stateSeed({
      name: "Cheyenne Transit Program",
      slug: "cheyenne-transit",
      category: "TRANSPORTATION_TRANSIT",
      description: "Cheyenne local bus transit service",
      website: "https://www.cheyennecity.org/Your-Government/Departments/Public-Works/Transit/Fixed-Route-Service",
      states: ["WY"],
      zipCodes: ["820"],
      popularityScore: 54,
      tags: ["transit", "bus", "cheyenne"],
    }),
  },
  ...PROVIDER_ADDITIONS_V1_BATCH1_CATALOG,
  ...PROVIDER_ADDITIONS_V1_BATCH2A_CATALOG,
];

export const STATE_PROVIDER_EXPANSIONS = STATE_PROVIDER_COMPLETENESS_CATALOG.flatMap((entry) =>
  entry.seedRecord ? [entry.seedRecord] : []
);
