UPDATE `MoveTask` mt
JOIN `MovingPlan` mp ON mp.`id` = mt.`movingPlanId`
SET mt.`dueDate` = CASE
  WHEN
    CASE mt.`actionType`
      WHEN 'GOVERNMENT_UPDATE' THEN DATE_ADD(mp.`moveDate`, INTERVAL 10 DAY)
      WHEN 'VERIFY_AVAILABILITY' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
      WHEN 'SHOP_PROVIDER' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
      WHEN 'FIND_REPLACEMENT' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
      WHEN 'START_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
      WHEN 'TRANSFER_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
      WHEN 'INSURANCE_REQUOTE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
      WHEN 'MAIL_FORWARDING' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
      WHEN 'STOP_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
      WHEN 'CANCEL_OR_CLOSE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
      WHEN 'UPDATE_ADDRESS' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
      ELSE DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
    END < CURRENT_DATE()
    AND mp.`moveDate` >= CURRENT_DATE()
  THEN CURRENT_DATE()
  ELSE CASE mt.`actionType`
    WHEN 'GOVERNMENT_UPDATE' THEN DATE_ADD(mp.`moveDate`, INTERVAL 10 DAY)
    WHEN 'VERIFY_AVAILABILITY' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
    WHEN 'SHOP_PROVIDER' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
    WHEN 'FIND_REPLACEMENT' THEN DATE_SUB(mp.`moveDate`, INTERVAL 21 DAY)
    WHEN 'START_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
    WHEN 'TRANSFER_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
    WHEN 'INSURANCE_REQUOTE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
    WHEN 'MAIL_FORWARDING' THEN DATE_SUB(mp.`moveDate`, INTERVAL 14 DAY)
    WHEN 'STOP_SERVICE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
    WHEN 'CANCEL_OR_CLOSE' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
    WHEN 'UPDATE_ADDRESS' THEN DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
    ELSE DATE_SUB(mp.`moveDate`, INTERVAL 7 DAY)
  END
END
WHERE mt.`dueDate` IS NULL
  AND mt.`deletedAt` IS NULL
  AND mt.`status` NOT IN ('COMPLETED', 'DISMISSED')
  AND mt.`actionType` <> 'NO_ACTION'
  AND mp.`deletedAt` IS NULL;
