export type ProviderCoverageModel = "state" | "zip_prefix" | "polygon" | "live_address";

export interface ProviderCoveragePoint {
  latitude: number;
  longitude: number;
}

export interface ProviderCoveragePolygon {
  label: string;
  points: ProviderCoveragePoint[];
}

export interface ProviderCoverageMetadata {
  slug: string;
  coverageModel: ProviderCoverageModel;
  officialUrl: string;
  note: string;
  source: "catalog" | "research";
  polygons?: ProviderCoveragePolygon[];
}

function polygon(label: string, coordinates: Array<[number, number]>): ProviderCoveragePolygon {
  return {
    label,
    points: coordinates.map(([latitude, longitude]) => ({ latitude, longitude })),
  };
}

function rectangle(
  label: string,
  north: number,
  west: number,
  south: number,
  east: number
): ProviderCoveragePolygon {
  return polygon(label, [
    [north, west],
    [north, east],
    [south, east],
    [south, west],
  ]);
}

const CURATED_RESEARCH_MODELS: ProviderCoverageMetadata[] = [
  {
    slug: "xfinity",
    coverageModel: "live_address",
    officialUrl: "https://www.xfinity.com",
    note: "Availability is confirmed by address rather than a stable public ZIP territory list.",
    source: "research",
  },
  {
    slug: "att-fiber",
    coverageModel: "live_address",
    officialUrl: "https://www.att.com/internet/availability/",
    note: "AT&T Fiber serviceability is address-qualified on the official availability checker.",
    source: "research",
  },
  {
    slug: "verizon-fios",
    coverageModel: "live_address",
    officialUrl: "https://www.verizon.com/coverage-map/",
    note: "Verizon Fios availability is exposed as an address-level coverage check.",
    source: "research",
  },
  {
    slug: "frontier",
    coverageModel: "live_address",
    officialUrl: "https://frontier.com/local",
    note: "Frontier serviceability varies by address and local buildout.",
    source: "research",
  },
  {
    slug: "google-fiber",
    coverageModel: "live_address",
    officialUrl: "https://fiber.google.com",
    note: "Google Fiber availability is city and address specific.",
    source: "research",
  },
  {
    slug: "gci-ak",
    coverageModel: "live_address",
    officialUrl: "https://www.gci.com/business/support/coverage-map",
    note: "GCI coverage is ultimately address-qualified across Alaska markets.",
    source: "research",
  },
  {
    slug: "ugi",
    coverageModel: "live_address",
    officialUrl: "https://www.ugi.com/about-us/geographic-footprint/",
    note: "UGI's Pennsylvania gas and electric footprint is fragmented and should be confirmed with the official address lookup.",
    source: "research",
  },
  {
    slug: "aqua-pa",
    coverageModel: "live_address",
    officialUrl: "https://www.aquawater.com/about/states-we-serve/pennsylvania/index.php",
    note: "Aqua Pennsylvania water and wastewater availability depends on municipal service territory and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "pa-american-water",
    coverageModel: "live_address",
    officialUrl: "https://www.amwater.com/paaw/about-us",
    note: "Pennsylvania American Water serves many non-contiguous Pennsylvania communities; account setup should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "dmv-ct",
    coverageModel: "state",
    officialUrl: "https://portal.ct.gov/dmv/licenses-permits-ids/change-driver-license",
    note: "Connecticut DMV address changes and vehicle registration transfers are statewide relocation workflows.",
    source: "research",
  },
  {
    slug: "eversource",
    coverageModel: "live_address",
    officialUrl: "https://www.eversource.com/residential/about/our-company/service-territory",
    note: "Eversource's Massachusetts and Connecticut electric/gas territories should be confirmed by service address despite ZIP prefilters.",
    source: "research",
  },
  {
    slug: "ui-ct",
    coverageModel: "live_address",
    officialUrl: "https://www.uinet.com/moving",
    note: "United Illuminating serves a defined greater New Haven and Bridgeport electric territory; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "socogas-ct",
    coverageModel: "live_address",
    officialUrl: "https://www.soconngas.com/moving",
    note: "Southern Connecticut Gas natural gas service is city/town-specific and should be confirmed by service address or gas locator.",
    source: "research",
  },
  {
    slug: "aquarion-ct",
    coverageModel: "live_address",
    officialUrl: "https://www.aquarionwater.com/customer-care/start-or-stop-service",
    note: "Aquarion Connecticut water and wastewater availability depends on the specific service address.",
    source: "research",
  },
  {
    slug: "mdc-ct-water",
    coverageModel: "live_address",
    officialUrl: "https://themdc.org/",
    note: "The Metropolitan District is a Hartford-area regional water and sewer authority; confirm service by property address.",
    source: "catalog",
  },
  {
    slug: "regional-water-authority-ct",
    coverageModel: "live_address",
    officialUrl: "https://www.rwater.com/customer-care/start-or-stop-service",
    note: "South Central Connecticut RWA serves listed New Haven-area communities; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "norwich-public-utilities-electric",
    coverageModel: "live_address",
    officialUrl: "https://norwichpublicutilities.com",
    note: "Norwich Public Utilities is a municipal multi-utility; exact ZIPs are city prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "wallingford-electric-division",
    coverageModel: "live_address",
    officialUrl: "https://www.wallingfordct.gov/government/departments/electric-division/",
    note: "Wallingford Electric Division serves Wallingford and part of Northford; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "groton-utilities",
    coverageModel: "live_address",
    officialUrl: "https://grotonutilities.com/221/Start-or-Stop-Service",
    note: "Groton Utilities is a municipal electric and water provider; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "connecticut-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.cngcorp.com/moving",
    note: "Connecticut Natural Gas serves central Connecticut and Greenwich gas territories; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "connecticut-water-company",
    coverageModel: "live_address",
    officialUrl: "https://www.ctwater.com/service-billing/your-service/developer-projects-and-new-service-connections/",
    note: "Connecticut Water Company serves many non-contiguous water systems; confirm service by address.",
    source: "catalog",
  },
  {
    slug: "national-grid-ma",
    coverageModel: "live_address",
    officialUrl: "https://www.mass.gov/info-details/find-my-electric-gas-and-water-company",
    note: "National Grid Massachusetts service varies by municipality and commodity; use the DPU or provider address workflow to confirm service.",
    source: "research",
  },
  {
    slug: "unitil-ma",
    coverageModel: "live_address",
    officialUrl: "https://unitil.com/electric-gas-service/service-areas",
    note: "Unitil Massachusetts includes partial community service areas and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "berkshire-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.berkshiregas.com/w/service-area",
    note: "Berkshire Gas serves selected western Massachusetts communities with moratorium constraints in some towns; confirm by service address.",
    source: "research",
  },
  {
    slug: "liberty-ma-gas",
    coverageModel: "live_address",
    officialUrl: "https://massachusetts.libertyutilities.com/fall-river/residential/my-account/moving.html",
    note: "Liberty Massachusetts Gas serves localized Fall River and Blackstone-area territories and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "aquarion-ma",
    coverageModel: "live_address",
    officialUrl: "https://www.mass.gov/info-details/water-distribution-companies",
    note: "Aquarion Water Company of Massachusetts serves selected partial communities and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "eversource-nh",
    coverageModel: "live_address",
    officialUrl: "https://www.eversource.com/residential/services/communities-we-serve",
    note: "Eversource New Hampshire electric service covers many, but not all, NH communities; ZIP prefixes are a prefilter and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "liberty-nh",
    coverageModel: "live_address",
    officialUrl: "https://libertyutilities.com/residential/about/what-we-do/electricity.html",
    note: "Liberty New Hampshire electric territory includes selected towns and small partial-town service areas; confirm by service address.",
    source: "research",
  },
  {
    slug: "unitil-nh",
    coverageModel: "live_address",
    officialUrl: "https://unitil.com/electric-gas-service/service-areas",
    note: "Unitil/Northern Utilities natural gas service is available only in selected New Hampshire communities and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "pennichuck-nh",
    coverageModel: "live_address",
    officialUrl: "https://pennichuck.com/my-water-system/",
    note: "Pennichuck water systems are town and system specific across southern New Hampshire; confirm the water system by service address.",
    source: "research",
  },
  {
    slug: "unitil-nh-electric",
    coverageModel: "live_address",
    officialUrl: "https://unitil.com/electric-gas-service/service-areas",
    note: "Unitil New Hampshire electric service includes partial community service areas and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "new-hampshire-electric-cooperative",
    coverageModel: "live_address",
    officialUrl: "https://www.nhec.com/request-service/",
    note: "NHEC serves many rural New Hampshire communities; exact ZIPs are only a prefilter and membership/service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "liberty-nh-gas",
    coverageModel: "live_address",
    officialUrl: "https://libertyutilities.com/residential/about/what-we-do/natural-gas.html",
    note: "Liberty New Hampshire gas service includes selected and small partial-town service areas; confirm by service address.",
    source: "research",
  },
  {
    slug: "aquarion-nh",
    coverageModel: "live_address",
    officialUrl: "https://www.aquarionwater.com/about/communities-we-serve",
    note: "Aquarion Water Company of New Hampshire serves selected communities and systems; confirm by address before acting.",
    source: "research",
  },
  {
    slug: "hampstead-area-water",
    coverageModel: "live_address",
    officialUrl: "https://www.hampsteadwater.com/my-water-service",
    note: "Hampstead Area Water Company serves selected southern New Hampshire towns and systems; confirm service by address.",
    source: "research",
  },
  {
    slug: "dmv-ga",
    coverageModel: "state",
    officialUrl: "https://dds.georgia.gov/georgia-licenseid/existing-licenseid/how-do-i-update-license",
    note: "Georgia DDS is the statewide driver license, permit, ID, and driver-record address-change surface.",
    source: "research",
  },
  {
    slug: "ga-dor-motor-vehicles",
    coverageModel: "state",
    officialUrl: "https://dor.georgia.gov/change-address-registration",
    note: "Georgia DOR Motor Vehicle Division handles statewide vehicle title, registration, license plate, and registration-address workflows.",
    source: "catalog",
  },
  {
    slug: "georgia-power",
    coverageModel: "live_address",
    officialUrl: "https://www.georgiapower.com/residential/manage-your-account/start-stop-move.html",
    note: "Georgia Power is a major Georgia electric utility, but cooperative and municipal territories overlap ZIPs; confirm service by address.",
    source: "research",
  },
  {
    slug: "peach-pass",
    coverageModel: "polygon",
    officialUrl: "https://peachpass.com/",
    note: "Peach Pass is the Georgia Express Lanes toll account surface; ZIPs are corridor prefilters and relevance depends on toll-facility use.",
    source: "research",
    polygons: [
      rectangle("Atlanta Express Lanes corridor", 34.20, -84.90, 33.25, -83.70),
    ],
  },
  {
    slug: "atlanta-water",
    coverageModel: "live_address",
    officialUrl: "https://atlantawatershed.org/start-my-service/",
    note: "Atlanta Watershed serves City of Atlanta water and sewer accounts; exact ZIPs are city prefilters and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "gng",
    coverageModel: "live_address",
    officialUrl: "https://gng.com/shop-plans/movers",
    note: "Georgia Natural Gas is a retail natural gas marketer in Atlanta Gas Light market areas; service and plan availability should be confirmed by address.",
    source: "research",
  },
  {
    slug: "atlanta-gas-light",
    coverageModel: "live_address",
    officialUrl: "https://www.atlantagaslight.com/residential/start-stop-service.html",
    note: "Atlanta Gas Light is the delivery utility and meter infrastructure provider for many Georgia gas service areas; confirm by address and marketer eligibility.",
    source: "catalog",
  },
  {
    slug: "gas-south",
    coverageModel: "live_address",
    officialUrl: "https://www.gassouth.com/move-transfer-service",
    note: "Gas South is a retail natural gas marketer; service depends on the address and Atlanta Gas Light market availability.",
    source: "catalog",
  },
  {
    slug: "cobb-emc",
    coverageModel: "live_address",
    officialUrl: "https://www.cobbemc.com/start-stop-or-transfer-service",
    note: "Cobb EMC is a cooperative electric provider with overlapping metro ZIPs; use the official address finder to confirm service.",
    source: "catalog",
  },
  {
    slug: "sawnee-emc",
    coverageModel: "live_address",
    officialUrl: "https://sawnee.coop/start-or-stop-service",
    note: "Sawnee EMC serves selected north Georgia addresses; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "marietta-power-water",
    coverageModel: "live_address",
    officialUrl: "https://www.mariettaga.gov/431/Start-or-Stop-Your-Service",
    note: "Marietta Power and Water is a municipal electric and water utility; eligibility should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "fulton-county-water",
    coverageModel: "live_address",
    officialUrl: "https://www.fultoncountyga.gov/services/water-services/start-your-water-service",
    note: "Fulton County Water Services covers county water and sewer service areas outside City of Atlanta; confirm by service address.",
    source: "catalog",
  },
  {
    slug: "dekalb-watershed",
    coverageModel: "live_address",
    officialUrl: "https://dekalbcountyga.gov/departments/watershed-management",
    note: "DeKalb Watershed water and sewer eligibility varies by address and should be confirmed through county customer service.",
    source: "catalog",
  },
  {
    slug: "gwinnett-water-resources",
    coverageModel: "live_address",
    officialUrl: "https://www.gwinnettcounty.com/government/departments/water",
    note: "Gwinnett County water service, billing, and transfer workflows are address-based despite county ZIP prefilters.",
    source: "catalog",
  },
  {
    slug: "cobb-county-water",
    coverageModel: "live_address",
    officialUrl: "https://www.cobbcounty.gov/water/customers/setup-service",
    note: "Cobb County Water System is distinct from Marietta municipal utility service; confirm account eligibility by address.",
    source: "catalog",
  },
  {
    slug: "dekalb-sanitation",
    coverageModel: "live_address",
    officialUrl: "https://dekalbcountyga.gov/departments/public-works/sanitation/new-residential-service",
    note: "DeKalb County sanitation service is address-based and separate from county watershed water/sewer accounts.",
    source: "catalog",
  },
  {
    slug: "gwinnett-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.gwinnettcounty.com/services/solid-waste-management/start-service",
    note: "Gwinnett County residential trash and recycling enrollment is address-based within the county service program.",
    source: "catalog",
  },
  {
    slug: "atlanta-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.atlantaga.gov/government/departments/public-works/office-of-solid-waste-services",
    note: "City of Atlanta solid-waste service applies to eligible city residential addresses and is separate from water/sewer accounts.",
    source: "catalog",
  },
  {
    slug: "dmv-ar",
    coverageModel: "state",
    officialUrl: "https://www.dfa.arkansas.gov/office/mydmv/",
    note: "Arkansas DFA MyDMV is the statewide driver license, ID, vehicle registration, and address-change service surface.",
    source: "research",
  },
  {
    slug: "entergy-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.myentergy.com/s/newservice",
    note: "Entergy Arkansas has broad but not universal electric coverage; service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "swepco-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.swepco.com/account/service/start-stop-transfer",
    note: "SWEPCO Arkansas service is concentrated in western and northwest Arkansas; ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "oge-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.oge.com/web/portal/label_ord/residential/startstoptransfer/overview",
    note: "OG&E's Arkansas service area is concentrated around Fort Smith and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "summit-utilities-ar",
    coverageModel: "live_address",
    officialUrl: "https://summitutilities.com/contact/start-stop-transfer-service",
    note: "Summit Utilities Arkansas natural gas service is address-specific within its Arkansas territory.",
    source: "research",
  },
  {
    slug: "black-hills-energy-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.blackhillsenergy.com/app-startstop/service-select",
    note: "Black Hills Energy Arkansas natural gas service applies only in selected communities and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "arkansas-oklahoma-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.aogc.com/RequestService",
    note: "Arkansas Oklahoma Gas serves selected western Arkansas addresses and should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "carroll-electric-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.carrollecc.com/apply-for-service",
    note: "Carroll Electric Cooperative serves selected Northwest Arkansas addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "first-electric-ar",
    coverageModel: "live_address",
    officialUrl: "https://www.firstelectric.coop/services/electrical-service/set-up-new-service",
    note: "First Electric Cooperative serves portions of central and southeast Arkansas; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "central-ar-water",
    coverageModel: "live_address",
    officialUrl: "https://carkw.com/customer-service/start-or-stop-service/",
    note: "Central Arkansas Water serves selected Little Rock-area and central Arkansas addresses; confirm water service by address.",
    source: "research",
  },
  {
    slug: "north-little-rock-electric",
    coverageModel: "live_address",
    officialUrl: "https://nlrelectric.com/forms/",
    note: "North Little Rock Electric is a municipal utility and service should be confirmed by exact address.",
    source: "catalog",
  },
  {
    slug: "conway-corp-electric",
    coverageModel: "live_address",
    officialUrl: "https://conwaycorp.com/sign-up-for-a-service/",
    note: "Conway Corporation municipal utility service is address-specific within Conway.",
    source: "catalog",
  },
  {
    slug: "springdale-water-utilities",
    coverageModel: "live_address",
    officialUrl: "https://springdalewaterar.gov/new-customer/",
    note: "Springdale Water Utilities water and wastewater service should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "bentonville-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.bentonvillear.com/565/Utility-Service",
    note: "City of Bentonville utility accounts cover municipal services and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "fayetteville-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.fayetteville-ar.gov/1368/New-Water-and-Sewer-Services",
    note: "Fayetteville water, sewer, trash, and recycling account eligibility should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "fort-smith-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.fortsmithar.gov/resident-services/water-utilities",
    note: "Fort Smith municipal utility accounts are address-specific for water, sewer, and sanitation billing.",
    source: "catalog",
  },
  {
    slug: "rogers-water-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.rogerswaterar.gov/residential/services-and-information/start-or-stop-service/",
    note: "Rogers Water Utilities water service should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "dmv-az",
    coverageModel: "state",
    officialUrl: "https://azdot.gov/mvd/services/driver-license-ID/change-your-address",
    note: "Arizona MVD is the statewide driver license, ID, vehicle record, registration, title, and address-change surface.",
    source: "research",
  },
  {
    slug: "aps-az",
    coverageModel: "live_address",
    officialUrl: "https://www.aps.com/en/Residential/Account/Start-Stop-and-Move-Service",
    note: "Arizona Public Service has a broad but non-statewide electric territory; start, stop, and move service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "srp-az",
    coverageModel: "live_address",
    officialUrl: "https://myaccount.srpnet.com/power/residentialelectric",
    note: "Salt River Project electric and water service is concentrated in central Arizona and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "tucson-electric-power",
    coverageModel: "live_address",
    officialUrl: "https://www.tep.com/im-moving/",
    note: "Tucson Electric Power serves Tucson-area electric addresses; ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "unisource-electric-az",
    coverageModel: "live_address",
    officialUrl: "https://www.uesaz.com/im-moving/",
    note: "UniSource electric service is limited to selected Arizona communities and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "unisource-gas-az",
    coverageModel: "live_address",
    officialUrl: "https://www.uesaz.com/im-moving/",
    note: "UniSource natural gas service is limited to selected Arizona communities and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "southwest-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.swgas.com/en/residential",
    note: "Southwest Gas natural gas service spans Arizona and Nevada but is address-specific within those territories.",
    source: "research",
  },
  {
    slug: "phoenix-water",
    coverageModel: "live_address",
    officialUrl: "https://www.phoenix.gov/residents/water-sewer.html",
    note: "City of Phoenix water, sewer, trash, and city services billing apply to eligible Phoenix service addresses.",
    source: "research",
  },
  {
    slug: "tucson-water",
    coverageModel: "live_address",
    officialUrl: "https://www.tucsonaz.gov/Departments/Water",
    note: "Tucson Water service is address-specific within Tucson and nearby service areas.",
    source: "research",
  },
  {
    slug: "mesa-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.mesaaz.gov/Utilities",
    note: "City of Mesa utilities include multiple services with commodity-specific service maps and address-based eligibility.",
    source: "research",
  },
  {
    slug: "epcor-water-az",
    coverageModel: "live_address",
    officialUrl: "https://www.epcor.com/us/en/az/account/start-service.html",
    note: "EPCOR Water Arizona has non-contiguous water and wastewater districts; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "arizona-water-company",
    coverageModel: "live_address",
    officialUrl: "https://www.azwater.com/",
    note: "Arizona Water Company operates multiple water systems and communities; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "liberty-utilities-az-water",
    coverageModel: "live_address",
    officialUrl: "https://arizona.libertyutilities.com/rio-rico/commercial/new-services/water-service-transfer.html",
    note: "Liberty Utilities Arizona water and wastewater service is community-specific and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "trico-electric",
    coverageModel: "live_address",
    officialUrl: "https://trico.coop/start-stop-transfer-service/",
    note: "Trico Electric Cooperative serves selected Tucson-area addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "mohave-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.mohaveelectric.com/member-service/apply-for-service/",
    note: "Mohave Electric Cooperative serves selected northwest Arizona addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "ssvec",
    coverageModel: "live_address",
    officialUrl: "https://www.ssvec.org/services/new-service.php",
    note: "Sulphur Springs Valley Electric Cooperative serves selected southeastern Arizona addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "chandler-water",
    coverageModel: "live_address",
    officialUrl: "https://www.chandleraz.gov/residents/utility-services",
    note: "Chandler utility service covers municipal water, sewer, and solid waste workflows and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "tempe-water-services",
    coverageModel: "live_address",
    officialUrl: "https://www.tempe.gov/i-want-to/start-stop-water-service",
    note: "Tempe water, sewer, and solid waste service is address-specific within the municipal utility system.",
    source: "catalog",
  },
  {
    slug: "scottsdale-water",
    coverageModel: "live_address",
    officialUrl: "https://www.scottsdaleaz.gov/utilities/establish-service",
    note: "Scottsdale utility service requires address confirmation before account setup.",
    source: "catalog",
  },
  {
    slug: "dmv-nv",
    coverageModel: "state",
    officialUrl: "https://dmv.nv.gov/newresident.htm",
    note: "Nevada DMV is the statewide driver license, vehicle registration, title, new-resident, and address-change surface.",
    source: "research",
  },
  {
    slug: "nv-energy",
    coverageModel: "live_address",
    officialUrl: "https://www.nvenergy.com/my-account/ss-landing",
    note: "NV Energy serves most Nevada electric customers and selected natural gas customers; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "lvvwd",
    coverageModel: "live_address",
    officialUrl: "https://www.lvvwd.com/customer-service/water-service/start-stop-service.html",
    note: "Las Vegas Valley Water District is the Southern Nevada retail water provider for eligible service addresses.",
    source: "research",
  },
  {
    slug: "tmwa",
    coverageModel: "live_address",
    officialUrl: "https://tmwa.com/start-stop-or-transfer-service/",
    note: "Truckee Meadows Water Authority water service is address-specific across Reno, Sparks, and nearby service areas.",
    source: "research",
  },
  {
    slug: "henderson-utility-services",
    coverageModel: "live_address",
    officialUrl: "https://www.cityofhenderson.com/government/departments/utility-services/businesses/start-stop-and-transfer-service",
    note: "City of Henderson water and sewer utility accounts are municipal and address-specific.",
    source: "research",
  },
  {
    slug: "north-las-vegas-utilities",
    coverageModel: "live_address",
    officialUrl: "https://payutil.cityofnorthlasvegas.com/",
    note: "City of North Las Vegas utility billing and service requests are address-specific within city utility boundaries.",
    source: "research",
  },
  {
    slug: "clark-county-water-reclamation",
    coverageModel: "live_address",
    officialUrl: "https://www.cleanwaterteam.com/",
    note: "Clark County Water Reclamation District sewer billing and account changes are separate from water service and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "reno-sewer-service",
    coverageModel: "live_address",
    officialUrl: "https://www.reno.gov/government/departments/finance/sewer-service",
    note: "City of Reno sewer service billing and mailing address changes are address-specific and separate from TMWA water.",
    source: "research",
  },
  {
    slug: "carson-city-utility-billing",
    coverageModel: "live_address",
    officialUrl: "https://www.carson.org/business/water-and-sewer-services",
    note: "Carson City water, sewer, and stormwater utility billing is city-scoped and address-specific.",
    source: "research",
  },
  {
    slug: "virgin-valley-water-district",
    coverageModel: "live_address",
    officialUrl: "https://vvwdnv.com/sign-up-for-service",
    note: "Virgin Valley Water District serves selected Mesquite-area service addresses.",
    source: "research",
  },
  {
    slug: "great-basin-water",
    coverageModel: "live_address",
    officialUrl: "https://www.myutility.us/greatbasinwater",
    note: "Great Basin Water has multiple Nevada water and wastewater divisions and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "republic-services-southern-nevada",
    coverageModel: "live_address",
    officialUrl: "https://www.republicservices.com/municipality/southern-nevada",
    note: "Republic Services of Southern Nevada trash and recycling service varies by municipal contract and service address.",
    source: "research",
  },
  {
    slug: "wm-nevada",
    coverageModel: "live_address",
    officialUrl: "https://www.wm.com/us/en/location/nv",
    note: "WM Nevada residential trash and recycling service varies by location and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "valley-electric-association",
    coverageModel: "live_address",
    officialUrl: "https://www.vea.coop/member-services/start-stop/",
    note: "Valley Electric Association cooperative electric service should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "overton-power-district",
    coverageModel: "live_address",
    officialUrl: "https://opd5.com/customer-information/application-for-new-service/",
    note: "Overton Power District No. 5 public-power service is local and address-specific.",
    source: "research",
  },
  {
    slug: "lincoln-county-power-district",
    coverageModel: "live_address",
    officialUrl: "https://www.lcpd1.com/form/start-or-stop-service",
    note: "Lincoln County Power District No. 1 electric service should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "mt-wheeler-power",
    coverageModel: "live_address",
    officialUrl: "https://www.mwpower.net/new-service-upgrade-request",
    note: "Mt. Wheeler Power serves selected eastern Nevada addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "wells-rural-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.wrec.coop/member-services/start-stop-transfer-service/",
    note: "Wells Rural Electric Company serves selected northeastern Nevada addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "boulder-city-utilities",
    coverageModel: "live_address",
    officialUrl: "https://bcnv.org/321/Utilities---Billing",
    note: "Boulder City municipal electric, water, wastewater, and utility billing service is city-scoped and address-specific.",
    source: "research",
  },
  {
    slug: "bge",
    coverageModel: "live_address",
    officialUrl: "https://secure.bge.com/CustomerServices/",
    note: "BGE provides electric and natural gas service across central Maryland, but service should be confirmed by premise address.",
    source: "research",
  },
  {
    slug: "pepco",
    coverageModel: "live_address",
    officialUrl: "https://www.pepco.com/MyAccount/MyService/Pages/StartStopMove.aspx",
    note: "Pepco serves DC and Maryland suburbs in Montgomery and Prince George's counties; ZIP prefixes are prefilters and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "delmarva-power-de",
    coverageModel: "live_address",
    officialUrl: "https://www.delmarva.com/MyAccount/MyService/Pages/StartStopMove.aspx",
    note: "Delmarva Power serves Delaware and Maryland Eastern Shore electric customers; ZIP prefixes are prefilters and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "potomac-edison",
    coverageModel: "live_address",
    officialUrl: "https://www.firstenergycorp.com/service_requests/moving_customer_survey.html",
    note: "Potomac Edison serves western and north-central Maryland plus parts of West Virginia; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "smeco",
    coverageModel: "live_address",
    officialUrl: "https://www.smeco.coop/my-account/service-management/connect-service/",
    note: "SMECO serves Southern Maryland cooperative members; ZIPs are prefilters and electric service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "choptank-electric",
    coverageModel: "live_address",
    officialUrl: "https://choptankelectric.coop/apply-service",
    note: "Choptank Electric serves portions of Maryland's Eastern Shore; ZIPs are prefilters and membership/service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "washington-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.washingtongas.com/services/current-customers/available-services/start-and-stop-service",
    note: "Washington Gas service spans DC, suburban Maryland, and Northern Virginia; natural gas service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "dmv-va",
    coverageModel: "state",
    officialUrl: "https://www.dmv.virginia.gov/online-services/address-change",
    note: "Virginia DMV is the statewide driver, vehicle, title, registration, and address-change surface.",
    source: "research",
  },
  {
    slug: "dmv-sc",
    coverageModel: "state",
    officialUrl: "https://dmv.sc.gov/driver-services/moving-to-sc",
    note: "South Carolina DMV is the statewide driver, vehicle, title, registration, new-resident, and address-change surface.",
    source: "research",
  },
  {
    slug: "ezpass-va",
    coverageModel: "state",
    officialUrl: "https://www.ezpassva.com/",
    note: "E-ZPass Virginia is a statewide toll account issuer; recommendation relevance depends on toll-road use rather than utility service territory.",
    source: "catalog",
  },
  {
    slug: "dominion",
    coverageModel: "live_address",
    officialUrl: "https://www.dominionenergy.com/en/Virginia/Start-Stop-Service",
    note: "Dominion Energy Virginia electric service is address-specific and overlaps with co-op and municipal electric territories.",
    source: "research",
  },
  {
    slug: "apco-wv",
    coverageModel: "live_address",
    officialUrl: "https://www.appalachianpower.com/account/service/start-stop-transfer",
    note: "Appalachian Power serves selected western and southwestern Virginia plus West Virginia areas; electric service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "old-dominion-power",
    coverageModel: "live_address",
    officialUrl: "https://lge-ku.com/odp",
    note: "Old Dominion Power is the Virginia-facing KU electric surface for selected southwest Virginia addresses.",
    source: "catalog",
  },
  {
    slug: "novec",
    coverageModel: "live_address",
    officialUrl: "https://www.novec.com/Customer_Services/Apply-for-Service.cfm",
    note: "NOVEC serves selected Northern Virginia cooperative electric addresses; exact ZIPs are prefilters.",
    source: "catalog",
  },
  {
    slug: "rappahannock-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.myrec.coop/startstop-service",
    note: "Rappahannock Electric Cooperative serves portions of many Virginia counties; confirm by service address.",
    source: "catalog",
  },
  {
    slug: "shenandoah-valley-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.svec.coop/member-services/start-stop-service/",
    note: "Shenandoah Valley Electric Cooperative service is territory-specific and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "central-virginia-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.mycvec.com/member-services/start-stop-move-service/",
    note: "Central Virginia Electric Cooperative serves selected central Virginia addresses and should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "virginia-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.virginianaturalgas.com/residential/manage-your-account/start-stop-transfer-service.html",
    note: "Virginia Natural Gas availability varies within southeastern Virginia ZIPs and should be confirmed by exact address.",
    source: "catalog",
  },
  {
    slug: "columbia-gas-va",
    coverageModel: "live_address",
    officialUrl: "https://www.columbiagasva.com/services/start-stop-or-move-service",
    note: "Columbia Gas of Virginia has non-contiguous gas territories; exact ZIPs are prefilters and service should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "roanoke-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.roanokegas.com/become-a-customer/residential-service/",
    note: "Roanoke Gas is regional and address-qualified around the Roanoke service area.",
    source: "catalog",
  },
  {
    slug: "richmond-gas-works",
    coverageModel: "live_address",
    officialUrl: "https://richmondgasworks.com/service/start-stop-transfer-service/",
    note: "Richmond Gas Works serves Richmond-area gas customers and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "fairfax-water",
    coverageModel: "live_address",
    officialUrl: "https://www.fairfaxwater.org/start-service",
    note: "Fairfax Water serves Northern Virginia water addresses within a defined service area; exact ZIPs are prefilters.",
    source: "research",
  },
  {
    slug: "loudoun-water",
    coverageModel: "live_address",
    officialUrl: "https://www.loudounwater.org/content/start-service",
    note: "Loudoun Water serves designated service areas outside incorporated towns and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "prince-william-water",
    coverageModel: "live_address",
    officialUrl: "https://princewilliamwater.org/our-customers/how-to/start-service",
    note: "Prince William Water serves most of Prince William County but account eligibility should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "va-american-water",
    coverageModel: "live_address",
    officialUrl: "https://amwater.com/vaaw/customer-service-billing/for-new-customers",
    note: "Virginia American Water serves multiple non-contiguous Virginia water systems; exact ZIPs are prefilters.",
    source: "research",
  },
  {
    slug: "virginia-beach-public-utilities",
    coverageModel: "live_address",
    officialUrl: "https://pu.virginiabeach.gov/customer-service/online-services",
    note: "Virginia Beach Public Utilities covers city water and sanitary sewer service addresses.",
    source: "catalog",
  },
  {
    slug: "arlington-water-sewer-refuse",
    coverageModel: "live_address",
    officialUrl: "https://www.arlingtonva.us/Government/Programs/Water-Utilities/Customer-Service/Start-Stop-Service",
    note: "Arlington County utility accounts cover water, sewer, and refuse service for county addresses.",
    source: "catalog",
  },
  {
    slug: "hrsd",
    coverageModel: "live_address",
    officialUrl: "https://www.hrsd.com/customers",
    note: "HRSD is a regional wastewater utility; sewer billing/service applicability should be confirmed by address and local water-provider coordination.",
    source: "catalog",
  },
  {
    slug: "virginia-beach-waste-management",
    coverageModel: "live_address",
    officialUrl: "https://pw.virginiabeach.gov/trash-recycling",
    note: "Virginia Beach trash and recycling service applies to eligible city residential addresses.",
    source: "catalog",
  },
  {
    slug: "columbia-gas-md",
    coverageModel: "live_address",
    officialUrl: "https://www.columbiagasmd.com/services/start-stop-or-move-service",
    note: "Columbia Gas of Maryland serves selected western Maryland communities; exact ZIPs come from the service-area list and should still be confirmed by address.",
    source: "research",
  },
  {
    slug: "chpk-de-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.chpkgas.com/customer-care/manage-my-account/start-stop-transfer-service/",
    note: "Chesapeake Utilities serves Delaware and selected Maryland Eastern Shore gas communities; ZIP prefixes are prefilters and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "wssc-md",
    coverageModel: "live_address",
    officialUrl: "https://www.wsscwater.com/service",
    note: "WSSC Water serves Montgomery and Prince George's counties, but retail service should be confirmed by address and account eligibility.",
    source: "research",
  },
  {
    slug: "anne-arundel-county-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.aacounty.org/services/sewer-water",
    note: "Anne Arundel County public water and wastewater service is address-specific within county ZIP prefilters.",
    source: "research",
  },
  {
    slug: "howard-county-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.howardcountymd.gov/public-works/bureau-utilities",
    note: "Howard County public water and wastewater systems serve most, but not all, county residents; confirm by service address.",
    source: "research",
  },
  {
    slug: "maryland-american-water",
    coverageModel: "live_address",
    officialUrl: "https://amwater.com/mdaw/",
    note: "Maryland American Water has a small, non-contiguous Maryland footprint around Bel Air, Harford County, and Severn; confirm by address.",
    source: "research",
  },
  {
    slug: "prince-georges-county-residential-collections",
    coverageModel: "live_address",
    officialUrl: "https://www.princegeorgescountymd.gov/departments-offices/environment/waste-recycling/residential-collections",
    note: "Prince George's County residential collection applies to county-contracted areas, so address eligibility should be confirmed.",
    source: "research",
  },
  {
    slug: "baltimore-county-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.baltimorecountymd.gov/departments/public-works/solid-waste",
    note: "Baltimore County solid waste service is distinct from Baltimore City sanitation and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "xcel-energy",
    coverageModel: "live_address",
    officialUrl: "https://co.my.xcelenergy.com/s/moving",
    note: "Xcel Energy Colorado electric and gas service is address-specific; ZIPs are Front Range prefilters.",
    source: "research",
  },
  {
    slug: "expresstoll",
    coverageModel: "polygon",
    officialUrl: "https://www.expresstoll.com/",
    note: "ExpressToll applies to Colorado toll corridors rather than all Colorado residents.",
    source: "research",
    polygons: [rectangle("Colorado Front Range toll corridors", 40.25, -105.35, 39.35, -104.45)],
  },
  {
    slug: "bhe-co-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.blackhillsenergy.com/app-startstop/service-select",
    note: "Black Hills Energy Colorado service is limited to selected communities and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "atmos-co",
    coverageModel: "live_address",
    officialUrl: "https://www.atmosenergy.com/accountcenter/moveininf/bpMoveInStart.html",
    note: "Atmos Energy Colorado serves selected communities; confirm natural gas service by exact address.",
    source: "research",
  },
  {
    slug: "denver-water",
    coverageModel: "live_address",
    officialUrl: "https://www.denverwater.org/residential/services-and-information/start-or-stop-service",
    note: "Denver Water covers Denver and selected nearby service areas; exact retail service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "denver-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Recycle-Compost-Trash",
    note: "Denver Solid Waste service applies to eligible City and County of Denver residential addresses.",
    source: "research",
  },
  {
    slug: "colorado-springs-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.csu.org/my-account/start-stop-service",
    note: "Colorado Springs Utilities is a municipal multi-utility; electric, gas, water, and wastewater service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "fort-collins-utilities",
    coverageModel: "live_address",
    officialUrl: "https://secure.fcgov.com/utilities-service-request/",
    note: "Fort Collins Utilities service is city and address specific across electric, water, wastewater, and stormwater.",
    source: "research",
  },
  {
    slug: "boulder-water-utilities",
    coverageModel: "live_address",
    officialUrl: "https://bouldercolorado.gov/water-service-request-form",
    note: "Boulder utility billing covers city water, wastewater, and stormwater accounts; confirm by service address.",
    source: "research",
  },
  {
    slug: "aurora-water",
    coverageModel: "live_address",
    officialUrl: "https://www.auroragov.org/residents/water/pay_my_water_bill/home_sellers_buyers_checklist/general_escrow_request_and_transfer_of_ownership",
    note: "Aurora Water account transfer and billing workflows are address-specific within the city service area.",
    source: "research",
  },
  {
    slug: "westminster-utilities-co",
    coverageModel: "live_address",
    officialUrl: "https://www.westminsterco.gov/184/Utility-Billing",
    note: "Westminster water, wastewater, stormwater, and utility billing eligibility should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "core-electric",
    coverageModel: "live_address",
    officialUrl: "https://core.coop/start-stop-service/",
    note: "CORE Electric Cooperative serves selected Colorado Front Range and foothills addresses; confirm membership/service by address.",
    source: "research",
  },
  {
    slug: "united-power",
    coverageModel: "live_address",
    officialUrl: "https://www.unitedpower.com/start-transfer-stop",
    note: "United Power service is cooperative-territory specific and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "pvrea",
    coverageModel: "live_address",
    officialUrl: "https://pvrea.coop/for-members/account-management/start-stop-service/",
    note: "Poudre Valley REA serves selected northern Colorado addresses; confirm cooperative electric service by address.",
    source: "research",
  },
  {
    slug: "holy-cross-energy",
    coverageModel: "live_address",
    officialUrl: "https://www.holycross.com/account-services/services/service-requests/start-stop-transfer-service",
    note: "Holy Cross Energy serves selected western Colorado communities and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "longmont-utilities",
    coverageModel: "live_address",
    officialUrl: "https://longmontcolorado.gov/utilities-and-public-works/utility-bill/start-or-stop-service/",
    note: "Longmont municipal utility service and billing are city and address specific.",
    source: "research",
  },
  {
    slug: "loveland-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.lovelandwaterandpower.org/about-us/start-stop-or-move-service",
    note: "Loveland municipal water, wastewater, and power service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "bart",
    coverageModel: "polygon",
    officialUrl: "https://www.bart.gov/system-map",
    note: "BART should match corridor and station geography rather than broad California state scope.",
    source: "research",
    polygons: [
      polygon("BART core district corridor", [
        [38.06, -122.53],
        [38.06, -121.23],
        [37.92, -121.18],
        [37.35, -121.73],
        [37.09, -121.94],
        [37.1, -122.31],
        [37.78, -122.55],
      ]),
    ],
  },
  {
    slug: "caltrain",
    coverageModel: "polygon",
    officialUrl: "https://www.caltrain.com",
    note: "Caltrain is a Bay Peninsula corridor provider and needs route-aware matching.",
    source: "research",
    polygons: [
      polygon("Caltrain peninsula rail corridor", [
        [37.81, -122.52],
        [37.8, -122.39],
        [37.71, -122.31],
        [37.58, -122.27],
        [37.45, -122.12],
        [37.31, -121.94],
        [37.08, -121.85],
        [37.08, -121.95],
        [37.29, -122.02],
        [37.53, -122.28],
        [37.72, -122.38],
      ]),
    ],
  },
  {
    slug: "la-metro",
    coverageModel: "polygon",
    officialUrl: "https://www.metro.net",
    note: "LA Metro coverage should be treated as a metro corridor network, not all of California.",
    source: "research",
    polygons: [
      rectangle("Los Angeles County Metro service area", 34.84, -118.95, 33.35, -117.63),
    ],
  },
  {
    slug: "mts-sd",
    coverageModel: "polygon",
    officialUrl: "https://www.sdmts.com",
    note: "San Diego MTS is a route network best represented as a service polygon.",
    source: "research",
    polygons: [
      rectangle("San Diego MTS service area", 33.52, -117.61, 32.53, -116.9),
    ],
  },
  {
    slug: "muni",
    coverageModel: "polygon",
    officialUrl: "https://www.sfmta.com/maps",
    note: "SF Muni is a dense municipal route network and should not be state-broad.",
    source: "research",
    polygons: [
      rectangle("San Francisco Muni service envelope", 37.833, -122.525, 37.705, -122.355),
    ],
  },
  {
    slug: "vta",
    coverageModel: "polygon",
    officialUrl: "https://www.vta.org/go/maps",
    note: "VTA should match Santa Clara corridor coverage rather than statewide California.",
    source: "research",
    polygons: [
      rectangle("Santa Clara Valley Transportation Authority", 37.49, -122.13, 36.92, -121.21),
    ],
  },
  {
    slug: "wmata",
    coverageModel: "polygon",
    officialUrl: "https://www.wmata.com",
    note: "WMATA spans DC, Maryland, and Virginia route corridors and needs route-aware matching.",
    source: "research",
    polygons: [
      rectangle("WMATA compact area", 39.18, -77.54, 38.69, -76.69),
    ],
  },
  {
    slug: "rtd",
    coverageModel: "polygon",
    officialUrl: "https://www.rtd-denver.com/routes-services",
    note: "RTD Denver should be represented as a regional route polygon.",
    source: "research",
    polygons: [
      rectangle("RTD Denver metro service area", 40.25, -105.55, 39.3, -104.55),
    ],
  },
  {
    slug: "dc-streetcar",
    coverageModel: "polygon",
    officialUrl: "https://dcstreetcar.com",
    note: "DC Streetcar is corridor-bound and should be modeled as a line/corridor match.",
    source: "research",
  },
  {
    slug: "capmetro",
    coverageModel: "polygon",
    officialUrl: "https://www.capmetro.org/ride/plan/schedmap",
    note: "CapMetro covers Austin corridors and is more precise than plain ZIP fallback.",
    source: "research",
    polygons: [
      rectangle("CapMetro Austin service area", 30.65, -98.01, 30.02, -97.38),
    ],
  },
  {
    slug: "dart",
    coverageModel: "polygon",
    officialUrl: "https://www.dart.org/guide/transit-and-use/dart-schedules-and-maps",
    note: "DART should be route-aware across the Dallas transit network.",
    source: "research",
    polygons: [
      rectangle("Dallas Area Rapid Transit service area", 33.19, -97.19, 32.55, -96.38),
    ],
  },
  {
    slug: "metro-houston",
    coverageModel: "polygon",
    officialUrl: "https://www.ridemetro.org/riding-metro/system-map",
    note: "Houston METRO is a corridor-based transit network.",
    source: "research",
    polygons: [
      rectangle("Houston METRO core service area", 30.2, -95.91, 29.33, -94.91),
    ],
  },
  {
    slug: "via-sa",
    coverageModel: "polygon",
    officialUrl: "https://www.viainfo.net",
    note: "VIA transit service is tied to San Antonio corridors rather than statewide TX.",
    source: "research",
    polygons: [
      rectangle("VIA Metropolitan Transit service area", 29.93, -98.98, 29.12, -98.19),
    ],
  },
  {
    slug: "uta",
    coverageModel: "polygon",
    officialUrl: "https://www.rideuta.com/Rider-Tools/Schedules-and-Maps",
    note: "UTA needs corridor-aware transit matching.",
    source: "research",
    polygons: [
      rectangle("UTA Wasatch Front corridor", 41.4, -112.12, 40.07, -111.5),
    ],
  },
  {
    slug: "sunpass",
    coverageModel: "polygon",
    officialUrl: "https://www.sunpass.com/",
    note: "SunPass is Florida's prepaid toll account surface; it is broadly useful in Florida but still tied to toll-road travel rather than every household service address.",
    source: "research",
  },
  {
    slug: "epass-cfx",
    coverageModel: "polygon",
    officialUrl: "https://epass.cfxway.com/",
    note: "E-PASS is the Central Florida Expressway Authority toll account surface and should be centered on Orlando/Central Florida toll corridors.",
    source: "catalog",
    polygons: [
      rectangle("Central Florida E-PASS toll corridor", 29.05, -81.75, 28.05, -80.85),
    ],
  },
  {
    slug: "leeway",
    coverageModel: "polygon",
    officialUrl: "https://www.leegov.com/tolls",
    note: "LeeWay is Lee County's local bridge toll account/transponder surface, not a statewide Florida toll provider.",
    source: "catalog",
    polygons: [
      rectangle("Lee County toll bridge area", 26.85, -82.35, 26.25, -81.65),
    ],
  },
  {
    slug: "fpl",
    coverageModel: "live_address",
    officialUrl: "https://www.fpl.com/landing/service-order.html",
    note: "FPL service starts/stops are address-qualified because Florida has overlapping investor-owned, municipal, and cooperative electric territories.",
    source: "research",
  },
  {
    slug: "duke-fl",
    coverageModel: "live_address",
    officialUrl: "https://www.duke-energy.com/start-stop-move/landing",
    note: "Duke Energy Florida serves selected central, west-central, and north-central Florida addresses; ZIPs are prefilters and service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "tampa-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.tampaelectric.com/residential/start-service/",
    note: "Tampa Electric service is concentrated in the Tampa Bay area and should be confirmed by service address.",
    source: "catalog",
  },
  {
    slug: "teco-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.peoplesgas.com/residential/start-service/",
    note: "Peoples Gas Florida natural gas availability is ZIP and neighborhood dependent; confirm by address before recommending account actions.",
    source: "research",
  },
  {
    slug: "florida-city-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.floridacitygas.com/residential/start-stop-transfer-or-add/",
    note: "Florida City Gas serves non-contiguous gas pockets in South Florida and the Treasure Coast; confirm by address.",
    source: "catalog",
  },
  {
    slug: "florida-public-utilities",
    coverageModel: "live_address",
    officialUrl: "https://fpuc.com/customer-care/start-stop-transfer-service/",
    note: "Florida Public Utilities provides gas and selected electric service in scattered Florida territories; confirm by service address.",
    source: "catalog",
  },
  {
    slug: "ouc",
    coverageModel: "live_address",
    officialUrl: "https://www.ouc.com/account/start-stop-move/",
    note: "OUC electric and water service is limited to Orlando, St. Cloud, and selected nearby areas; confirm by address.",
    source: "research",
  },
  {
    slug: "jea",
    coverageModel: "live_address",
    officialUrl: "https://www.jea.com/my_account/add%2C_move%2C_or_stop_service/",
    note: "JEA electric, water, and sewer service is Northeast Florida address-specific.",
    source: "research",
  },
  {
    slug: "tampa-water",
    coverageModel: "live_address",
    officialUrl: "https://www.tampa.gov/service/utility-service-starttransferstop-service",
    note: "City of Tampa utility service covers city and selected nearby service addresses for water, wastewater, and solid waste.",
    source: "research",
  },
  {
    slug: "miami-water",
    coverageModel: "live_address",
    officialUrl: "https://www.miamidade.gov/global/water/my-account.page",
    note: "Miami-Dade Water and Sewer service should be confirmed by address within county ZIP prefilters.",
    source: "research",
  },
  {
    slug: "hillsborough-county-water",
    coverageModel: "live_address",
    officialUrl: "https://hcfl.gov/residents/property-owners-and-renters/water-and-sewer/request-to-start-stop-or-move-water-service",
    note: "Hillsborough County Water Resources serves unincorporated county service areas and should be confirmed by address.",
    source: "catalog",
  },
  {
    slug: "pinellas-county-water",
    coverageModel: "live_address",
    officialUrl: "https://pinellas.gov/services/request-utilities-service/",
    note: "Pinellas County Utilities applies to county utility service areas and not every municipal address in Pinellas County.",
    source: "catalog",
  },
  {
    slug: "orange-county-utilities-water",
    coverageModel: "live_address",
    officialUrl: "https://www.orangecountyfl.net/WaterGarbageRecycling.aspx",
    note: "Orange County Utilities covers county water, wastewater, reclaimed water, and solid waste service areas, distinct from OUC and Toho.",
    source: "catalog",
  },
  {
    slug: "fastrak",
    coverageModel: "polygon",
    officialUrl: "https://www.bayareafastrak.org/coverage-map",
    note: "FasTrak belongs to specific toll facilities and bridge corridors.",
    source: "research",
    polygons: [
      rectangle("Bay Area FasTrak toll region", 38.35, -123.12, 36.85, -121.58),
    ],
  },
  {
    slug: "good-to-go",
    coverageModel: "polygon",
    officialUrl: "https://wsdot.wa.gov/goodtogo",
    note: "Good To Go! maps to toll corridors, not statewide service by residence alone.",
    source: "research",
    polygons: [
      rectangle("Good To Go north Puget Sound corridor", 47.97, -122.52, 47.35, -121.86),
      rectangle("Good To Go south Puget Sound corridor", 47.4, -122.73, 46.92, -121.98),
    ],
  },
  {
    slug: "txtag",
    coverageModel: "polygon",
    officialUrl: "https://www.txtag.org",
    note: "TxTag is tied to toll corridors and agencies, so polygon matching is more honest than state fallback.",
    source: "research",
  },
  {
    slug: "ipass",
    coverageModel: "polygon",
    officialUrl: "https://www.getipass.com",
    note: "I-PASS belongs to the Illinois Tollway network and adjacent interoperable corridors.",
    source: "research",
    polygons: [
      rectangle("I-PASS northern Illinois toll corridor", 42.45, -88.65, 41.45, -87.45),
    ],
  },
  {
    slug: "alaska-communications",
    coverageModel: "live_address",
    officialUrl: "https://www.alaskacommunications.com/Residential",
    note: "Alaska Communications is best modeled as address-qualified availability.",
    source: "research",
  },
  {
    slug: "oncor-electric-delivery",
    coverageModel: "polygon",
    officialUrl: "https://www.oncor.com",
    note: "Oncor electric delivery territory should be polygon-modeled rather than broad Texas fallback.",
    source: "research",
  },
  {
    slug: "dmv-nc",
    coverageModel: "state",
    officialUrl: "https://www.ncdot.gov/dmv/help/moving/Pages/default.aspx",
    note: "NCDMV moving, address-change, driver license, ID, title, and registration workflows are statewide.",
    source: "research",
  },
  {
    slug: "nc-quick-pass",
    coverageModel: "polygon",
    officialUrl: "https://www.ncquickpass.com/open-account/",
    note: "NC Quick Pass is tied to North Carolina toll corridors rather than a statewide utility territory.",
    source: "research",
    polygons: [
      rectangle("Triangle Expressway toll corridor", 36.05, -79.05, 35.55, -78.55),
      rectangle("Charlotte I-77 and Monroe toll corridors", 35.55, -81.05, 34.75, -80.35),
    ],
  },
  {
    slug: "duke-nc",
    coverageModel: "live_address",
    officialUrl: "https://www.duke-energy.com/start-stop-move/landing",
    note: "Duke Energy North Carolina covers separate Duke Energy Carolinas and Duke Energy Progress territories; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "dominion-energy-nc",
    coverageModel: "live_address",
    officialUrl: "https://www.dominionenergy.com/en/North-Carolina/Start-Stop-Service",
    note: "Dominion Energy North Carolina electric service is address-specific in northeastern North Carolina.",
    source: "research",
  },
  {
    slug: "dominion-energy-sc",
    coverageModel: "live_address",
    officialUrl: "https://www.dominionenergy.com/en/South-Carolina/Start-Stop-Service",
    note: "Dominion Energy South Carolina electric service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "palmetto-pass",
    coverageModel: "polygon",
    officialUrl: "https://southernconnector.com/index.html",
    note: "Southern Connector / Palmetto Pass is tied to the Greenville-area I-185 toll corridor.",
    source: "research",
    polygons: [rectangle("Southern Connector I-185 toll corridor", 34.9, -82.5, 34.58, -82.25)],
  },
  {
    slug: "duke-energy-sc",
    coverageModel: "live_address",
    officialUrl: "https://www.duke-energy.com/start-stop-move/landing",
    note: "Duke Energy South Carolina spans Duke Energy Carolinas and Duke Energy Progress territories; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "santee-cooper",
    coverageModel: "live_address",
    officialUrl: "https://www.santeecooper.com/residential/start-move-stop-service/",
    note: "Santee Cooper power and water service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "berkeley-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.berkeleyelectric.coop/service-territory",
    note: "Berkeley Electric Cooperative service is address-specific in Lowcountry South Carolina.",
    source: "research",
  },
  {
    slug: "horry-electric",
    coverageModel: "live_address",
    officialUrl: "https://horryelectric.com/services/electric-service/",
    note: "Horry Electric Cooperative service is address-specific in the Horry County and Grand Strand market.",
    source: "research",
  },
  {
    slug: "blue-ridge-electric-sc",
    coverageModel: "live_address",
    officialUrl: "https://blueridge.coop/start-service",
    note: "Blue Ridge Electric Cooperative serves selected Upstate South Carolina addresses.",
    source: "research",
  },
  {
    slug: "laurens-electric",
    coverageModel: "live_address",
    officialUrl: "https://laurenselectric.com/my-account/start-service/",
    note: "Laurens Electric Cooperative serves selected Upstate South Carolina addresses.",
    source: "research",
  },
  {
    slug: "mid-carolina-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.mcecoop.com/my-account/start-service/",
    note: "Mid-Carolina Electric Cooperative requires address eligibility confirmation before service application.",
    source: "research",
  },
  {
    slug: "palmetto-electric",
    coverageModel: "live_address",
    officialUrl: "https://palmetto.coop/startstop-service",
    note: "Palmetto Electric Cooperative serves selected Lowcountry South Carolina addresses.",
    source: "research",
  },
  {
    slug: "york-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.yorkelectric.net/my-service/residential-accounts/start-residential-electric-service/",
    note: "York Electric Cooperative serves selected York, Lancaster, Chester, and Cherokee-area addresses.",
    source: "research",
  },
  {
    slug: "santee-electric",
    coverageModel: "live_address",
    officialUrl: "https://santee.org/service",
    note: "Santee Electric Cooperative is distinct from Santee Cooper and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "dominion-sc-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.dominionenergy.com/en/South-Carolina/Start-Stop-Service/Check-Availability",
    note: "Dominion Energy South Carolina gas availability should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "york-county-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://ycnga.com/start-stop-change-service/",
    note: "York County Natural Gas Authority service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "fort-hill-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.fhnga.com/customer-support/start-stop-transfer.stml",
    note: "Fort Hill Natural Gas Authority serves selected Oconee, Pickens, and Anderson-area addresses.",
    source: "research",
  },
  {
    slug: "lancaster-county-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://lcngasc.com/",
    note: "Lancaster County Natural Gas Authority service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "charleston-water-sc",
    coverageModel: "live_address",
    officialUrl: "https://www.charlestonwater.com/180/Open-or-Close-an-Account",
    note: "Charleston Water System water and sewer account eligibility should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "greenville-water",
    coverageModel: "live_address",
    officialUrl: "https://www.greenvillewater.com/customer-service/start-stop-move",
    note: "Greenville Water service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "columbia-water-sc",
    coverageModel: "live_address",
    officialUrl: "https://columbiascwater.net/new-transfer-service/",
    note: "Columbia Water account eligibility should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "spartanburg-water",
    coverageModel: "live_address",
    officialUrl: "https://www.spartanburgwater.org/manage-water-service",
    note: "Spartanburg Water service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "beaufort-jasper-water",
    coverageModel: "live_address",
    officialUrl: "https://www.bjwsa.org/167/StartStop-Services",
    note: "Beaufort-Jasper Water & Sewer Authority service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "grand-strand-water",
    coverageModel: "live_address",
    officialUrl: "https://www.gswsa.com/customer-service.cfm?page=44",
    note: "Grand Strand Water & Sewer Authority service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "mount-pleasant-waterworks",
    coverageModel: "live_address",
    officialUrl: "https://www.mountpleasantwaterworks.com/customers/service___account_requests/start_or_stop_service.php",
    note: "Mount Pleasant Waterworks service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "energyunited",
    coverageModel: "live_address",
    officialUrl: "https://www.energyunited.com/member-guide/",
    note: "EnergyUnited cooperative electric service is territory-specific and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "blue-ridge-energy",
    coverageModel: "live_address",
    officialUrl: "https://www.blueridgeenergy.com/residential/apply-for-service",
    note: "Blue Ridge Energy serves selected northwestern North Carolina cooperative addresses.",
    source: "research",
  },
  {
    slug: "brunswick-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.bemc.org/name-change-transfer-service/",
    note: "Brunswick Electric Membership Corporation service is address-specific in southeastern North Carolina.",
    source: "research",
  },
  {
    slug: "piedmont-carolinas",
    coverageModel: "live_address",
    officialUrl: "https://www.piedmontng.com/home/start-stop-or-move",
    note: "Piedmont Natural Gas availability is fragmented across Carolinas service areas and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "psnc",
    coverageModel: "live_address",
    officialUrl: "https://www.enbridgegas.com/north-carolina/start-stop-service",
    note: "Enbridge Gas North Carolina is the current customer surface for legacy PSNC/Dominion gas service and requires address confirmation.",
    source: "research",
  },
  {
    slug: "frontier-natural-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.frontiernaturalgas.com/natural-gas-conversion/service-area/",
    note: "Frontier Natural Gas serves selected North Carolina communities and should be confirmed by exact address.",
    source: "research",
  },
  {
    slug: "charlotte-water",
    coverageModel: "live_address",
    officialUrl: "https://www.charlottenc.gov/water/Customer-Care/Start-Stop-Service",
    note: "Charlotte Water is a municipal water and sewer provider; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "charlotte-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.charlottenc.gov/Services/Trash-and-Recycling",
    note: "Charlotte Solid Waste Services is city-scoped and should be matched by residential address.",
    source: "research",
  },
  {
    slug: "raleigh-water",
    coverageModel: "live_address",
    officialUrl: "https://raleighnc.gov/water-and-sewer/services/start-stop-or-transfer-utility-services",
    note: "Raleigh Water serves Raleigh and partner municipalities; water and sewer accounts should be confirmed by address.",
    source: "research",
  },
  {
    slug: "raleigh-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://raleighnc.gov/departments/solid-waste-services",
    note: "Raleigh Solid Waste Services is city-scoped and should be matched by residential address.",
    source: "research",
  },
  {
    slug: "durham-water",
    coverageModel: "live_address",
    officialUrl: "https://www.durhamnc.gov/4097/Start-Stop-Transfer",
    note: "Durham Water Management is address-specific for municipal water and sewer service.",
    source: "research",
  },
  {
    slug: "durham-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.durhamnc.gov/832/Solid-Waste",
    note: "Durham Solid Waste Management is city-scoped and should be matched by residential address.",
    source: "research",
  },
  {
    slug: "greensboro-water",
    coverageModel: "live_address",
    officialUrl: "https://www.greensboro-nc.gov/departments/water-resources/customer-service-for-residents-and-businesses",
    note: "Greensboro Water Resources is a municipal water and sewer surface; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "winston-salem-forsyth-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.cityofws.org/1237/Start-Stop-or-Transfer-Service",
    note: "Winston-Salem/Forsyth County Utilities water and sewer service varies by service address.",
    source: "research",
  },
  {
    slug: "winston-salem-solid-waste",
    coverageModel: "live_address",
    officialUrl: "https://www.cityofws.org/568/Solid-Waste-Collections",
    note: "Winston-Salem solid waste collection is resident-address scoped.",
    source: "research",
  },
  {
    slug: "owasa",
    coverageModel: "live_address",
    officialUrl: "https://www.owasa.org/start-stop-move/",
    note: "OWASA serves Carrboro-Chapel Hill water and sewer addresses and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "aqua-nc",
    coverageModel: "live_address",
    officialUrl: "https://www.aquawater.com/start-or-stop-service",
    note: "Aqua North Carolina serves scattered private water and wastewater systems; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "carolina-water-nc",
    coverageModel: "live_address",
    officialUrl: "https://www.mywater.us/north-carolina",
    note: "Carolina Water Service of North Carolina serves scattered systems and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "old-north-state-water",
    coverageModel: "live_address",
    officialUrl: "https://onswc.com/customer-service/",
    note: "Old North State Water Company serves scattered water and wastewater communities; address confirmation is required.",
    source: "research",
  },
  {
    slug: "dmv-or",
    coverageModel: "state",
    officialUrl: "https://www.oregon.gov/odot/dmv/pages/dv/chgaddress.aspx",
    note: "Oregon DMV address-change, license, ID, and vehicle registration workflows are statewide.",
    source: "research",
  },
  {
    slug: "breezeby-electronic-tolling",
    coverageModel: "polygon",
    officialUrl: "https://www.portofhoodriver.com/about-breezeby-electronic-bridge-tolling",
    note: "BreezeBy is a bridge toll account system tied to Columbia River crossings rather than a statewide household utility.",
    source: "research",
    polygons: [
      rectangle("BreezeBy Columbia River bridge corridor", 45.9, -122.15, 45.45, -121.25),
    ],
  },
  {
    slug: "pge-or",
    coverageModel: "live_address",
    officialUrl: "https://portlandgeneral.com/start-stop-move",
    note: "Portland General Electric serves Portland metro and northern Willamette Valley addresses; confirm electric service by address.",
    source: "research",
  },
  {
    slug: "pacific-power-or",
    coverageModel: "live_address",
    officialUrl: "https://www.pacificpower.net/my-account/start-stop-move.html",
    note: "Pacific Power Oregon service is broad but not statewide; exact electric service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "idaho-power-or",
    coverageModel: "live_address",
    officialUrl: "https://www.idahopower.com/accounts-service/start-stop-transfer/",
    note: "Idaho Power's Oregon service area is address-specific and should remain distinct from Oregon Trail Electric until operational transfer details change.",
    source: "research",
  },
  {
    slug: "nw-natural",
    coverageModel: "live_address",
    officialUrl: "https://www.nwnatural.com/account/start-stop-transfer",
    note: "NW Natural gas service is address-qualified across Oregon and Southwest Washington.",
    source: "research",
  },
  {
    slug: "cascade-wa-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.cngc.com/customer-service/start-stop-or-transfer-service/",
    note: "Cascade Natural Gas serves selected Oregon and Washington communities; confirm service availability by address.",
    source: "research",
  },
  {
    slug: "avista-utilities-or-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.myavista.com/your-account/moving",
    note: "Avista Oregon gas service should be confirmed by address and kept separate from NW Natural and Cascade Natural Gas territories.",
    source: "research",
  },
  {
    slug: "eweb",
    coverageModel: "live_address",
    officialUrl: "https://www.eweb.org/start-stop",
    note: "EWEB electric and water service is local to Eugene-area addresses and should be confirmed at the service address.",
    source: "research",
  },
  {
    slug: "springfield-utility-board",
    coverageModel: "live_address",
    officialUrl: "https://www.subutil.com/customer-service/start-stop-service/",
    note: "Springfield Utility Board electric and water service is municipal and address-specific.",
    source: "research",
  },
  {
    slug: "central-lincoln-pud",
    coverageModel: "live_address",
    officialUrl: "https://clpud.org/customer-information/start-or-stop-service/",
    note: "Central Lincoln PUD serves selected central Oregon coast addresses.",
    source: "research",
  },
  {
    slug: "tillamook-pud",
    coverageModel: "live_address",
    officialUrl: "https://www.tpud.org/customer-service/start-or-stop-service/",
    note: "Tillamook PUD electric service is local and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "oregon-trail-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.otec.coop/",
    note: "Oregon Trail Electric Cooperative serves selected eastern Oregon addresses.",
    source: "research",
  },
  {
    slug: "umatilla-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.umatillaelectric.com/member-services/start-stop-service/",
    note: "Umatilla Electric Cooperative serves selected northeastern Oregon addresses.",
    source: "research",
  },
  {
    slug: "consumers-power-or",
    coverageModel: "live_address",
    officialUrl: "https://cpi.coop/service/stop-service",
    note: "Consumers Power Inc. serves selected Oregon zones and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "lane-electric",
    coverageModel: "live_address",
    officialUrl: "https://www.laneelectric.com/member-services/new-member-guide/",
    note: "Lane Electric Cooperative serves rural Lane County and nearby addresses, distinct from EWEB and Springfield Utility Board.",
    source: "research",
  },
  {
    slug: "portland-water-or",
    coverageModel: "live_address",
    officialUrl: "https://www.portland.gov/water/customer-service/pay-your-utility-bill/start-stop-or-transfer-service",
    note: "City of Portland water, sewer, and stormwater utility accounts are address-specific.",
    source: "research",
  },
  {
    slug: "city-of-salem-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.cityofsalem.net/community/household/water-utilities/utility-payments-and-your-utility-account/manage-your-city-of-salem-utility-service-account",
    note: "City of Salem utility service account eligibility should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "city-of-bend-water",
    coverageModel: "live_address",
    officialUrl: "https://bendoregon.gov/service/water-sewer-start-or-stop-service/",
    note: "Bend water and sewer service is municipal and address-specific.",
    source: "research",
  },
  {
    slug: "medford-water",
    coverageModel: "live_address",
    officialUrl: "https://www.medfordwater.org/services/customer-service/",
    note: "Medford Water service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "tualatin-valley-water",
    coverageModel: "live_address",
    officialUrl: "https://www.tvwd.org/district/page/startstop-service-interim-billing",
    note: "Tualatin Valley Water District is a regional water district and should be confirmed by address.",
    source: "research",
  },
  {
    slug: "hillsboro-utility-billing",
    coverageModel: "live_address",
    officialUrl: "https://www.hillsboro-oregon.gov/services/utility-billing/start-or-stop-service",
    note: "Hillsboro utility billing is city-scoped and address-specific.",
    source: "research",
  },
  {
    slug: "gresham-utility-services",
    coverageModel: "live_address",
    officialUrl: "https://www.greshamoregon.gov/services/utilities/stop-or-start-utility-services/",
    note: "Gresham water, wastewater, and stormwater service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "dmv-ut",
    coverageModel: "state",
    officialUrl: "https://dld.utah.gov/address-change-regular/",
    note: "Utah Driver License Division is the statewide driver license and ID address-change surface.",
    source: "research",
  },
  {
    slug: "utah-dmv-motor-vehicle-portal",
    coverageModel: "state",
    officialUrl: "https://mvp.tax.utah.gov/",
    note: "Utah Motor Vehicle Portal handles statewide vehicle title, registration, renewal, and vehicle address-change workflows.",
    source: "catalog",
  },
  {
    slug: "express-pass",
    coverageModel: "polygon",
    officialUrl: "https://www.expresspass.utah.gov/",
    note: "Utah Express Pass belongs to the I-15 Express Lanes corridor rather than a generic statewide residence match.",
    source: "research",
    polygons: [
      rectangle("I-15 Wasatch Front Express Lanes corridor", 41.35, -112.25, 40.05, -111.45),
    ],
  },
  {
    slug: "rmp-ut",
    coverageModel: "live_address",
    officialUrl: "https://www.rockymountainpower.net/my-account/start-stop-move.html",
    note: "Rocky Mountain Power is a multi-state electric utility; exact service should be checked by address, especially near municipal/co-op territories.",
    source: "research",
  },
  {
    slug: "dominion-ut-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.enbridgegas.com/utwyid/start-stop-service",
    note: "Enbridge Gas Utah is the successor customer surface for Dominion Energy Utah/Questar Gas; coverage is broad but still address-qualified.",
    source: "research",
  },
  {
    slug: "slc-water-ut",
    coverageModel: "live_address",
    officialUrl: "https://www.slc.gov/utilities/",
    note: "Salt Lake City Department of Public Utilities is city-scoped and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "provo-city-utilities",
    coverageModel: "live_address",
    officialUrl: "https://www.provo.gov/181/City-Utilities",
    note: "Provo City Utilities covers municipal electric, water, wastewater, and garbage account setup for Provo service addresses.",
    source: "catalog",
  },
  {
    slug: "st-george-utilities",
    coverageModel: "live_address",
    officialUrl: "https://sgcityutah.gov/departments/apply_for_utility_services.php",
    note: "City of St. George utility service is municipal and address-specific; nearby cooperative electric providers may serve some adjacent addresses.",
    source: "catalog",
  },
  {
    slug: "wasatch-front-waste-recycling-district",
    coverageModel: "live_address",
    officialUrl: "https://wfwrdutah.gov/services-and-request/services-requests",
    note: "Wasatch Front Waste & Recycling District serves selected Salt Lake County cities and unincorporated areas, so address confirmation is required.",
    source: "catalog",
  },
  {
    slug: "dmv-oh",
    coverageModel: "state",
    officialUrl: "https://bmvonline.dps.ohio.gov/",
    note: "Ohio Bureau of Motor Vehicles is the statewide driver, title, registration, plate renewal, and address-change surface.",
    source: "research",
  },
  {
    slug: "ohio-edison",
    coverageModel: "live_address",
    officialUrl: "https://www.firstenergycorp.com/service_requests/moving_customer_survey.html",
    note: "FirstEnergy Ohio utilities include Ohio Edison, The Illuminating Company, and Toledo Edison; exact electric delivery service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "aep-ohio",
    coverageModel: "live_address",
    officialUrl: "https://www.aepohio.com/account/service/start-stop-transfer",
    note: "AEP Ohio has broad but non-contiguous Ohio electric territory; address-level confirmation avoids false positives near other electric utilities.",
    source: "research",
  },
  {
    slug: "duke-oh",
    coverageModel: "live_address",
    officialUrl: "https://www.duke-energy.com/start-stop-move/landing",
    note: "Duke Energy Ohio serves southwest Ohio electric and gas customers; exact service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "aes-ohio",
    coverageModel: "live_address",
    officialUrl: "https://www.aes-ohio.com/moving",
    note: "AES Ohio serves Dayton and west-central Ohio electric customers; exact service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "cleveland-public-power",
    coverageModel: "live_address",
    officialUrl: "https://www.cpp.org/Residential/Start-Service",
    note: "Cleveland Public Power is a municipal electric utility; coverage should be checked by service address within Cleveland.",
    source: "research",
  },
  {
    slug: "columbia-gas-oh",
    coverageModel: "live_address",
    officialUrl: "https://www.columbiagasohio.com/services/start-stop-or-move-service",
    note: "Columbia Gas of Ohio serves broad Ohio gas territories but remains address-qualified near other gas providers.",
    source: "research",
  },
  {
    slug: "enbridge-gas-oh",
    coverageModel: "live_address",
    officialUrl: "https://www.enbridgegas.com/ohio/start-stop-service",
    note: "Enbridge Gas Ohio is the current customer surface for former Dominion Energy Ohio gas service; availability should be confirmed by address.",
    source: "research",
  },
  {
    slug: "centerpoint-oh-gas",
    coverageModel: "live_address",
    officialUrl: "https://www.centerpointenergy.com/en-us/residential/customer-service/start-stop-transfer-service?sa=OH",
    note: "CenterPoint Energy Ohio gas service is concentrated in west-central Ohio; CenterPoint says customer service remains unchanged during the pending National Fuel sale process, and availability should be confirmed by address.",
    source: "research",
  },
  {
    slug: "cleveland-water",
    coverageModel: "live_address",
    officialUrl: "https://www.clevelandwater.com/customer-service/faqs",
    note: "Cleveland Water serves multiple northeast Ohio communities; account setup and final billing are address and property dependent.",
    source: "research",
  },
  {
    slug: "columbus-water",
    coverageModel: "live_address",
    officialUrl: "https://www.columbus.gov/Services/Columbus-Water-Power/Start-New-Utility-Service",
    note: "Columbus Water & Power service can vary by municipal boundary and utility type, so address confirmation is required.",
    source: "research",
  },
  {
    slug: "cincy-water",
    coverageModel: "live_address",
    officialUrl: "https://www.cincinnati-oh.gov/water/moving-or-selling-your-property1/",
    note: "Greater Cincinnati Water Works is regional and account-transfer oriented; service should be confirmed by address.",
    source: "research",
  },
  {
    slug: "toledo-public-utilities",
    coverageModel: "live_address",
    officialUrl: "https://toledo.oh.gov/residents/water/customer-service/turn-on-new-water-service",
    note: "Toledo Public Utilities water service is municipal and should be confirmed by service address.",
    source: "research",
  },
  {
    slug: "neorsd",
    coverageModel: "live_address",
    officialUrl: "https://www.neorsd.org/customers-service-page/bill-payment-option/",
    note: "Northeast Ohio Regional Sewer District is regional, with account and billing routing that depends on community and address.",
    source: "research",
  },
  {
    slug: "msd-greater-cincinnati",
    coverageModel: "live_address",
    officialUrl: "https://msdgc.org/",
    note: "Metropolitan Sewer District of Greater Cincinnati serves Cincinnati/Hamilton County sewer customers and nearby pockets; address confirmation is required.",
    source: "research",
  },
  {
    slug: "rumpke-oh",
    coverageModel: "live_address",
    officialUrl: "https://www.rumpke.com/about-us/service-areas/oh",
    note: "Rumpke availability depends on address, municipality, and contract; ZIP prefixes should only prefilter Ohio markets.",
    source: "research",
  },
  {
    slug: "columbus-refuse",
    coverageModel: "live_address",
    officialUrl: "https://www.columbus.gov/Services/Trash-Recycling-Bulk-Collection",
    note: "Columbus refuse collection is city-scoped and should be confirmed by address for resident collection schedules and services.",
    source: "research",
  },
  {
    slug: "ohio-turnpike-ezpass",
    coverageModel: "polygon",
    officialUrl: "https://www.ezpassoh.com",
    note: "Ohio Turnpike E-ZPass is corridor-based and should follow toll-network coverage.",
    source: "research",
    polygons: [
      rectangle("Ohio Turnpike corridor", 41.95, -84.9, 40.9, -80.45),
    ],
  },
];

const coverageMetadataMap = new Map<string, ProviderCoverageMetadata>();

for (const entry of CURATED_RESEARCH_MODELS) {
  coverageMetadataMap.set(entry.slug, entry);
}

export function getProviderCoverageMetadataMap() {
  return coverageMetadataMap;
}

export function getProviderCoverageMetadata(slug?: string | null) {
  if (!slug) return null;
  return coverageMetadataMap.get(slug) || null;
}
