import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireDbUserId } from "@/lib/auth";
import { movingPlanSchema } from "@/lib/validators";
import { rateLimit, getRateLimitKey } from "@/lib/rate-limit";
import { canCreateAddress, canCreateMovingPlan } from "@/lib/plan-limits";
import { encrypt } from "@/lib/shared-encryption";
import {
  generateTaskTemplates,
  analyzeMigration,
  generateMigrationTasks,
  type UserChecklistProfile,
  type ServiceWithProvider,
  type ProviderForMigration,
} from "@/lib/shared-relocation";

function normalizeAddressValue(value?: string | null) {
  return (value || "").trim().toUpperCase();
}

function addressesMatch(
  left: { street: string; city: string; state: string; zip: string },
  right: { street: string; city: string; state: string; zip: string }
) {
  return normalizeAddressValue(left.street) === normalizeAddressValue(right.street)
    && normalizeAddressValue(left.city) === normalizeAddressValue(right.city)
    && normalizeAddressValue(left.state) === normalizeAddressValue(right.state)
    && normalizeAddressValue(left.zip) === normalizeAddressValue(right.zip);
}

const TASK_TITLE_MAX_LENGTH = 200;
const TASK_CATEGORY_MAX_LENGTH = 50;
const TASK_TEMPLATE_ID_MAX_LENGTH = 30;
const TASK_PRIORITY_VALUES = new Set(["LOW", "MEDIUM", "HIGH", "URGENT"]);

function stripNonBmpCharacters(value?: string | null) {
  if (!value) return value;
  return Array.from(value)
    .filter((char) => {
      const codePoint = char.codePointAt(0);
      return codePoint !== undefined && codePoint <= 0xFFFF;
    })
    .join("");
}

function sanitizeDbString(value?: string | null, maxLength?: number, collapseWhitespace = false) {
  if (value == null) return value;
  const stripped = stripNonBmpCharacters(value) ?? "";
  const normalized = collapseWhitespace ? stripped.replace(/\s+/g, " ").trim() : stripped;
  if (typeof maxLength === "number" && normalized.length > maxLength) {
    return normalized.slice(0, maxLength);
  }
  return normalized;
}

function normalizeTaskPriority(priority?: string | null) {
  if (priority && TASK_PRIORITY_VALUES.has(priority)) {
    return priority;
  }
  return "MEDIUM";
}

function buildGeneratedTaskRows(
  tasks: any[],
  userId: string,
  movingPlanId: string,
  sanitizeText = false,
) {
  return tasks.map((task: any) => {
    const title = sanitizeText
      ? sanitizeDbString(task.title, TASK_TITLE_MAX_LENGTH, true) || "Moving task"
      : task.title;
    const description = sanitizeText
      ? sanitizeDbString(task.description)
      : task.description;
    const category = sanitizeText
      ? sanitizeDbString(task.category, TASK_CATEGORY_MAX_LENGTH, true) || undefined
      : task.category;
    const templateId = sanitizeText
      ? sanitizeDbString(task.templateId, TASK_TEMPLATE_ID_MAX_LENGTH, true) || undefined
      : task.templateId;

    return {
      userId,
      movingPlanId,
      title,
      description,
      category,
      priority: normalizeTaskPriority(task.priority),
      dueDate: task.dueDate,
      daysBeforeMove: task.daysBeforeMove,
      isAutoGenerated: true,
      templateId,
    };
  });
}

function isRetryableGeneratedTaskInsertError(error: any) {
  const message = typeof error?.message === "string" ? error.message : "";
  return error?.code === "P2000"
    || /incorrect string value|data too long|value too long/i.test(message);
}

// GET /api/moving
export async function GET() {
  try {
    const userId = await requireDbUserId();
    const plans = await prisma.movingPlan.findMany({
      where: { userId, deletedAt: null },
      include: {
        fromAddress: { select: { street: true, city: true, state: true, zip: true } },
        toAddress: { select: { street: true, city: true, state: true, zip: true } },
        tasks: { select: { id: true, title: true, category: true, dueDate: true, priority: true, completed: true }, orderBy: { dueDate: "asc" } },
      },
      orderBy: { moveDate: "desc" },
    });
    return NextResponse.json({ plans });
  } catch (error) {
    console.error("Failed to fetch moving plans:", error);
    return NextResponse.json({ error: "Failed to fetch moving plans" }, { status: 500 });
  }
}

// POST /api/moving
export async function POST(request: NextRequest) {
  try {
    const userId = await requireDbUserId();

    // Rate limit: 10 plans per minute
    const rlKey = getRateLimitKey(request, "moving:create");
    const rl = await rateLimit(rlKey, { limit: 10, windowSeconds: 60 });
    if (!rl.success) {
      return NextResponse.json({ error: "Too many requests. Please wait." }, { status: 429 });
    }

    const body = await request.json();
    const validated = movingPlanSchema.parse(body);
    const needsNewDestinationAddress = Boolean(validated.destinationAddress);

    // Plan limit check
    const limitCheck = await canCreateMovingPlan(userId);
    if (!limitCheck.allowed) {
      return NextResponse.json({ error: limitCheck.reason }, { status: 403 });
    }
    if (needsNewDestinationAddress) {
      const addressLimitCheck = await canCreateAddress(userId);
      if (!addressLimitCheck.allowed) {
        return NextResponse.json({ error: addressLimitCheck.reason }, { status: 403 });
      }
    }

    // Prevent same-address moving plan
    if (validated.fromAddressId === validated.toAddressId) {
      return NextResponse.json({ error: "Origin and destination addresses cannot be the same" }, { status: 400 });
    }

    const fromAddress = await prisma.address.findUnique({ where: { id: validated.fromAddressId } });
    if (!fromAddress || fromAddress.userId !== userId || fromAddress.deletedAt) {
      return NextResponse.json({ error: "Origin address not found" }, { status: 404 });
    }

    let toAddress: { id?: string; street: string; city: string; state: string; zip: string } | null = null;
    if (validated.toAddressId) {
      const existingDestination = await prisma.address.findUnique({ where: { id: validated.toAddressId } });
      if (!existingDestination || existingDestination.userId !== userId || existingDestination.deletedAt) {
        return NextResponse.json({ error: "Destination address not found" }, { status: 404 });
      }
      if (addressesMatch(fromAddress, existingDestination)) {
        return NextResponse.json({ error: "Origin and destination addresses cannot be the same" }, { status: 400 });
      }
      toAddress = existingDestination;
    } else if (validated.destinationAddress) {
      if (addressesMatch(fromAddress, validated.destinationAddress)) {
        return NextResponse.json({ error: "Origin and destination addresses cannot be the same" }, { status: 400 });
      }
      toAddress = {
        street: validated.destinationAddress.street,
        city: validated.destinationAddress.city,
        state: validated.destinationAddress.state,
        zip: validated.destinationAddress.zip,
      };
    }

    if (!toAddress) {
      return NextResponse.json({ error: "Destination address not found" }, { status: 404 });
    }

    // Wrap plan + task creation in a transaction to prevent orphaned data
    const profile = await prisma.profile.findUnique({ where: { userId } });
    const checklistProfile: UserChecklistProfile = {
      hasChildren: profile?.hasChildren ?? false,
      childrenCount: profile?.childrenCount ?? 0,
      hasPets: profile?.hasPets ?? false,
      hasSenior: profile?.hasSenior ?? false,
      carCount: profile?.carCount ?? 0,
      hasDisability: profile?.hasDisability ?? false,
      needsStorage: profile?.needsStorage ?? false,
      hasMotorcycle: profile?.hasMotorcycle ?? false,
      hasBoatRV: profile?.hasBoatRV ?? false,
      isImmigrant: (profile as any)?.isImmigrant ?? false,
      isBusinessOwner: (profile as any)?.isBusinessOwner ?? false,
      moveType: ((profile as any)?.moveType as "PERSONAL" | "BUSINESS" | "VACATION") || "PERSONAL",
    };

    const stateRule = await prisma.stateRule.findUnique({ where: { stateCode: toAddress.state } }).catch(() => null);

    const genericTemplates = generateTaskTemplates(
      checklistProfile,
      new Date(validated.moveDate),
      toAddress.state,
      stateRule ? {
        dmvRules: stateRule.dmvRules,
        voterRegistration: stateRule.voterRegistration,
        taxInfo: stateRule.taxInfo,
      } : null,
    );

    // ── Migration analysis: generate personalized service tasks ──
    let migrationTasks: any[] = [];
    let replacedTemplateIds: string[] = [];
    try {
      const existingServices = await prisma.service.findMany({
        where: { userId, addressId: validated.fromAddressId, isActive: true },
        include: {
          provider: { select: { id: true, name: true, scope: true, states: true, category: true } },
        },
      });

      if (existingServices.length > 0) {
        const safeJSON = (v: any, fb: any) => {
          if (Array.isArray(v)) return v;
          if (typeof v === "string") { try { return JSON.parse(v); } catch { return fb; } }
          return fb;
        };

        const servicesWithParsed: ServiceWithProvider[] = existingServices.map((s: any) => ({
          id: s.id, category: s.category, providerName: s.providerName,
          providerId: s.providerId, isActive: s.isActive, monthlyCost: s.monthlyCost,
          provider: s.provider ? {
            id: s.provider.id, name: s.provider.name, scope: s.provider.scope,
            states: safeJSON(s.provider.states, []), category: s.provider.category,
          } : null,
        }));

        const allProviders = await prisma.serviceProvider.findMany({ where: { isActive: true } });
        const providersForMigration: ProviderForMigration[] = allProviders
          .map((p: any) => ({
            id: p.id, name: p.name, slug: p.slug, category: p.category, scope: p.scope,
            states: safeJSON(p.states, []), popularityScore: p.popularityScore || 0,
            avgRating: p.avgRating, reviewCount: p.reviewCount || 0,
          }))
          .filter((p: ProviderForMigration) => p.scope === "FEDERAL" || p.states.includes(toAddress.state));

        const analysis = analyzeMigration(servicesWithParsed, fromAddress.state, toAddress.state, providersForMigration, checklistProfile);
        const migResult = generateMigrationTasks(analysis, new Date(validated.moveDate), toAddress.state);
        migrationTasks = migResult.tasks;
        replacedTemplateIds = migResult.replaces;
      }
    } catch (migErr) {
      console.error("Migration analysis failed (non-blocking):", migErr);
    }

    // ── Merge: filter out generic tasks replaced by migration tasks ──
    const replacedSet = new Set(replacedTemplateIds);
    const filteredGeneric = genericTemplates.filter((t: any) => !replacedSet.has(t.templateId));
    const allTasks = [...filteredGeneric, ...migrationTasks];

    const { plan, destinationAddressId } = await prisma.$transaction(async (tx: any) => {
      let destinationAddressId = validated.toAddressId;

      if (!destinationAddressId && validated.destinationAddress) {
        const destinationAddress = await tx.address.create({
          data: {
            ...validated.destinationAddress,
            formattedAddress: validated.destinationAddress.formattedAddress
              ? encrypt(validated.destinationAddress.formattedAddress)
              : validated.destinationAddress.formattedAddress,
            isPrimary: false,
            userId,
            startDate: new Date(validated.destinationAddress.startDate),
            endDate: validated.destinationAddress.endDate ? new Date(validated.destinationAddress.endDate) : undefined,
          },
        });
        destinationAddressId = destinationAddress.id;
      }

      if (!destinationAddressId) {
        throw new Error("Destination address could not be created");
      }

      const created = await tx.movingPlan.create({
        data: {
          userId,
          fromAddressId: validated.fromAddressId,
          toAddressId: destinationAddressId,
          moveDate: new Date(validated.moveDate),
          isTemporary: validated.isTemporary,
          estimatedDuration: validated.estimatedDuration,
        },
      });

      if (allTasks.length > 0) {
        try {
          await tx.task.createMany({
            data: buildGeneratedTaskRows(allTasks, userId, created.id),
          });
        } catch (taskError: any) {
          if (!isRetryableGeneratedTaskInsertError(taskError)) {
            throw taskError;
          }

          console.warn("Retrying generated moving tasks with sanitized text fields:", taskError);
          await tx.task.createMany({
            data: buildGeneratedTaskRows(allTasks, userId, created.id, true),
          });
        }

        await tx.movingPlan.update({
          where: { id: created.id },
          data: { totalTasks: allTasks.length },
        });
      }

      return { plan: created, destinationAddressId };
    });

    return NextResponse.json({ plan, destinationAddressId }, { status: 201 });
  } catch (error: any) {
    if (error?.name === "ZodError") {
      return NextResponse.json({ error: "Validation failed", details: error.errors }, { status: 400 });
    }
    if (error?.message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (typeof error?.message === "string" && error.message.startsWith("AUTH_NOT_CONFIGURED")) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
    console.error("Failed to create moving plan:", error);
    const details = process.env.NODE_ENV !== "production" && typeof error?.message === "string"
      ? error.message
      : undefined;
    return NextResponse.json(
      details ? { error: "Failed to create moving plan", details } : { error: "Failed to create moving plan" },
      { status: 500 },
    );
  }
}
