INSERT IGNORE INTO `EmailTemplate`
  (`id`, `slug`, `name`, `subject`, `body`, `category`, `variables`, `isActive`, `isDefault`, `createdAt`, `updatedAt`)
VALUES
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'subscription-activated', 'Subscription Activated', 'Your LocateFlow subscription is active', '<p>Your LocateFlow subscription is active.</p>', 'TRANSACTIONAL', '["firstName","planName","amount","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'subscription-canceled', 'Subscription Canceled', 'Your LocateFlow subscription was canceled', '<p>Your LocateFlow subscription cancellation is recorded.</p>', 'TRANSACTIONAL', '["firstName","planName","accessEndsOn","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'subscription-resumed', 'Subscription Renewal Resumed', 'Your LocateFlow subscription will renew', '<p>Auto-renew is back on for your LocateFlow subscription.</p>', 'TRANSACTIONAL', '["firstName","planName","renewsOn","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'payment-failed', 'Payment Failed', 'Action needed: LocateFlow payment issue', '<p>We could not process your LocateFlow payment.</p>', 'TRANSACTIONAL', '["firstName","amount","nextAttemptOn","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'task-reminder', 'Task Reminder', 'Task reminder: {{taskTitle}}', '<p>Your moving task is due soon.</p>', 'NOTIFICATION', '["firstName","taskTitle","dueDate","movingPlan","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'bill-overdue', 'Bill Overdue', 'Overdue bill: {{serviceName}}', '<p>Your bill appears overdue.</p>', 'NOTIFICATION', '["firstName","serviceName","amount","dueDate","appUrl"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'support-ticket-created', 'Support Ticket Created', 'Support ticket received: {{ticketSubject}}', '<p>We received your support request.</p>', 'TRANSACTIONAL', '["firstName","ticketSubject","priority","category","ticketLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'support-ticket-reply', 'Support Ticket Reply', 'New reply on: {{ticketSubject}}', '<p>Our support team replied to your ticket.</p>', 'TRANSACTIONAL', '["firstName","ticketSubject","ticketLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'support-ticket-status', 'Support Ticket Status', 'Support ticket {{status}}', '<p>Your support ticket status changed.</p>', 'TRANSACTIONAL', '["firstName","ticketSubject","status","ticketLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'security-password-changed', 'Security: Password Changed', 'Your LocateFlow password was changed', '<p>Your account password was just changed.</p>', 'TRANSACTIONAL', '["firstName","manageLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'security-mfa-enabled', 'Security: MFA Enabled', 'Two-factor authentication is now on', '<p>Two-factor authentication is now active on your account.</p>', 'TRANSACTIONAL', '["firstName","manageLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'security-mfa-disabled', 'Security: MFA Disabled', 'Two-factor authentication was turned off', '<p>Two-factor authentication has been turned off on your account.</p>', 'TRANSACTIONAL', '["firstName","manageLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'security-oauth-linked', 'Security: Sign-in Method Linked', 'A new sign-in method was linked to your account', '<p>A new sign-in method was linked to your account.</p>', 'TRANSACTIONAL', '["firstName","manageLink"]', true, true, NOW(), NOW()),
  (CONCAT('tpl_', SUBSTR(REPLACE(UUID(), '-', ''), 1, 22)), 'security-account-deletion-requested', 'Security: Account Deletion Requested', 'Your LocateFlow account deletion is scheduled', '<p>Your LocateFlow account deletion is scheduled.</p>', 'TRANSACTIONAL', '["firstName","manageLink"]', true, true, NOW(), NOW());
