// AUTO-GENERATED by scripts/gen-state-data.cjs from
// packages/db/prisma/seed-data/state-rules.ts. Do not edit by hand —
// re-run the generator to refresh. Kept Prisma-free on purpose so the
// static /moving/[state] route never pulls the DB client into its build.

export interface StateProvider {
  name: string;
  /** Official provider homepage, when a verified domain is known. */
  url: string | null;
}

export interface StateGuide {
  /** USPS two-letter code, e.g. "CA". */
  abbr: string;
  /** Full display name, e.g. "California". */
  name: string;
  /** URL slug, e.g. "california". */
  slug: string;
  /** Driver's license / vehicle registration deadlines (verbatim seed). */
  dmvRules: string;
  /** Voter registration method + deadline (verbatim seed). */
  voterRegistration: string;
  /** Utility market notes (verbatim seed). */
  utilityInfo: string;
  /** Income / sales / property tax summary (verbatim seed). */
  taxInfo: string;
  /** Auto-insurance minimums (verbatim seed). */
  insuranceRules: string;
  /** Top local utilities & providers for the state. */
  providers: StateProvider[];
}

export const STATE_GUIDES: StateGuide[] = [
  {
    "abbr": "AL",
    "name": "Alabama",
    "slug": "alabama",
    "dmvRules": "Must obtain AL DL within 30 days. Visit county license office. Title and registration at county probate office.",
    "voterRegistration": "Register online at alabamavotes.gov. Deadline: 15 days before election.",
    "utilityInfo": "Major providers: Alabama Power, Alagasco. Regulated market.",
    "taxInfo": "State income tax: 2%-5%. Property tax rates among lowest in US. Sales tax: 4% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Alabama Power",
        "url": "https://www.alabamapower.com"
      },
      {
        "name": "Alagasco",
        "url": "https://www.spireenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      }
    ]
  },
  {
    "abbr": "AK",
    "name": "Alaska",
    "slug": "alaska",
    "dmvRules": "Must obtain AK DL within 90 days. Visit local DMV. Vehicle registration required within 10 days.",
    "voterRegistration": "Register online at voterregistration.alaska.gov. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Chugach Electric, ENSTAR. High energy costs due to remote location.",
    "taxInfo": "No state income tax. No state sales tax (some local taxes). PFD (Permanent Fund Dividend) paid annually.",
    "insuranceRules": "Auto insurance required: liability minimum 50/100/25. Higher minimums than most states.",
    "providers": [
      {
        "name": "Chugach Electric",
        "url": "https://www.chugachelectric.com"
      },
      {
        "name": "ENSTAR",
        "url": "https://www.enstarnaturalgas.com"
      },
      {
        "name": "GCI",
        "url": "https://www.gci.com"
      },
      {
        "name": "ACS",
        "url": "https://www.alaskacommunications.com"
      }
    ]
  },
  {
    "abbr": "AZ",
    "name": "Arizona",
    "slug": "arizona",
    "dmvRules": "Must obtain AZ DL immediately upon establishing residency. Visit MVD or third-party provider. DL valid until age 65.",
    "voterRegistration": "Register online at azsos.gov/elections. Deadline: 29 days before election.",
    "utilityInfo": "Major providers: APS, SRP. Regulated market. Solar incentives available.",
    "taxInfo": "Flat state income tax: 2.5%. Property tax varies by county. Sales tax: 5.6% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/15.",
    "providers": [
      {
        "name": "APS",
        "url": "https://www.aps.com"
      },
      {
        "name": "SRP",
        "url": "https://www.srpnet.com"
      },
      {
        "name": "Southwest Gas",
        "url": "https://www.swgas.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "AR",
    "name": "Arkansas",
    "slug": "arkansas",
    "dmvRules": "Must obtain AR DL within 30 days. Visit local revenue office. Title transfer within 30 days.",
    "voterRegistration": "Register by mail or in person. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Entergy Arkansas, CenterPoint Energy. Regulated market.",
    "taxInfo": "State income tax: 2%-4.7%. Sales tax: 6.5% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Entergy Arkansas",
        "url": "https://www.entergyarkansas.com"
      },
      {
        "name": "CenterPoint Energy",
        "url": "https://www.centerpointenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Suddenlink",
        "url": "https://www.optimum.com"
      }
    ]
  },
  {
    "abbr": "CA",
    "name": "California",
    "slug": "california",
    "dmvRules": "Must update DL within 10 days of establishing residency. Visit local DMV or apply online at dmv.ca.gov.",
    "voterRegistration": "Register online at registertovote.ca.gov. Deadline: 15 days before election (conditional registration available).",
    "utilityInfo": "Major providers: PG&E, SCE, SDG&E. Deregulated energy market in some areas.",
    "taxInfo": "State income tax: 1%-13.3%. No tax on Social Security benefits. High property tax exemption for homeowners.",
    "insuranceRules": "Auto insurance required: liability minimum 15/30/5. Earthquake insurance optional but recommended.",
    "providers": [
      {
        "name": "PG&E",
        "url": "https://www.pge.com"
      },
      {
        "name": "Southern California Edison",
        "url": "https://www.sce.com"
      },
      {
        "name": "San Diego Gas & Electric",
        "url": "https://www.sdge.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      }
    ]
  },
  {
    "abbr": "CO",
    "name": "Colorado",
    "slug": "colorado",
    "dmvRules": "Must obtain CO DL within 30 days. Visit county DMV office. Emissions testing required in Denver metro.",
    "voterRegistration": "Register online at govotecolorado.gov. Same-day registration available.",
    "utilityInfo": "Major providers: Xcel Energy. Partially deregulated market.",
    "taxInfo": "Flat state income tax: 4.4%. Property tax relatively low. Sales tax: 2.9% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/15.",
    "providers": [
      {
        "name": "Xcel Energy",
        "url": "https://www.xcelenergy.com"
      },
      {
        "name": "Comcast Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "CT",
    "name": "Connecticut",
    "slug": "connecticut",
    "dmvRules": "Must obtain CT DL within 30 days. Visit DMV office. Emissions test required for registration.",
    "voterRegistration": "Register online at voterregistration.ct.gov. Deadline: 7 days before election.",
    "utilityInfo": "Major providers: Eversource, United Illuminating. Regulated market with high rates.",
    "taxInfo": "State income tax: 3%-6.99%. Property tax among highest in US. Sales tax: 6.35%.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Eversource",
        "url": "https://www.eversource.com"
      },
      {
        "name": "United Illuminating",
        "url": "https://www.uinet.com"
      },
      {
        "name": "CT Natural Gas",
        "url": "https://www.cngcorp.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Frontier",
        "url": "https://frontier.com"
      }
    ]
  },
  {
    "abbr": "DE",
    "name": "Delaware",
    "slug": "delaware",
    "dmvRules": "Must obtain DE DL within 60 days. Visit DMV location. No vehicle inspection required.",
    "voterRegistration": "Register online at ivote.de.gov. Deadline: 24 days before election.",
    "utilityInfo": "Major providers: Delmarva Power, Chesapeake Utilities. Regulated market.",
    "taxInfo": "State income tax: 2.2%-6.6%. No sales tax. Low property tax.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10. PIP required.",
    "providers": [
      {
        "name": "Delmarva Power",
        "url": "https://www.delmarva.com"
      },
      {
        "name": "Chesapeake Utilities",
        "url": "https://www.chpk.com"
      },
      {
        "name": "Comcast Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon",
        "url": "https://www.verizon.com"
      }
    ]
  },
  {
    "abbr": "DC",
    "name": "District of Columbia",
    "slug": "district-of-columbia",
    "dmvRules": "Must obtain DC DL within 30 days. Visit DC DMV office. Vehicle inspection required every 2 years.",
    "voterRegistration": "Register online at dcboe.org. Same-day registration available.",
    "utilityInfo": "Major providers: Pepco, Washington Gas. Deregulated electricity market.",
    "taxInfo": "Income tax: 4%-10.75%. Sales tax: 6% (10% meals, 14.95% hotels). Property tax varies.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10. No-fault district.",
    "providers": [
      {
        "name": "Pepco",
        "url": "https://www.pepco.com"
      },
      {
        "name": "Washington Gas",
        "url": "https://www.washingtongas.com"
      },
      {
        "name": "DC Water",
        "url": "https://www.dcwater.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon Fios",
        "url": "https://www.verizon.com/home/fios"
      }
    ]
  },
  {
    "abbr": "FL",
    "name": "Florida",
    "slug": "florida",
    "dmvRules": "Must obtain FL DL within 30 days. Visit local DHSMV office or apply at flhsmv.gov.",
    "voterRegistration": "Register online at registertovoteflorida.gov. Deadline: 29 days before election.",
    "utilityInfo": "Major providers: FPL, Duke Energy, TECO. Regulated market.",
    "taxInfo": "No state income tax. Sales tax: 6% + local. Homestead exemption up to $50K for property tax.",
    "insuranceRules": "Auto insurance: PIP ($10K) and property damage ($10K) required. Bodily injury recommended.",
    "providers": [
      {
        "name": "Florida Power & Light",
        "url": "https://www.fpl.com"
      },
      {
        "name": "Duke Energy",
        "url": "https://www.duke-energy.com"
      },
      {
        "name": "TECO",
        "url": "https://www.tampaelectric.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      }
    ]
  },
  {
    "abbr": "GA",
    "name": "Georgia",
    "slug": "georgia",
    "dmvRules": "Must obtain GA DL within 30 days. Visit DDS office. Emissions test required in metro Atlanta counties.",
    "voterRegistration": "Register online at registertovote.sos.ga.gov. Deadline: 29 days before election.",
    "utilityInfo": "Major providers: Georgia Power, Atlanta Gas Light. Deregulated natural gas market.",
    "taxInfo": "State income tax: 1%-5.49%. Sales tax: 4% + local. Homestead exemption available.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Georgia Power",
        "url": "https://www.georgiapower.com"
      },
      {
        "name": "Atlanta Gas Light",
        "url": "https://www.atlantagaslight.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "HI",
    "name": "Hawaii",
    "slug": "hawaii",
    "dmvRules": "Must obtain HI DL within 30 days. Visit county DMV. Safety inspection required annually.",
    "voterRegistration": "Register online at elections.hawaii.gov. All-mail voting state since 2020.",
    "utilityInfo": "Major providers: Hawaiian Electric (HECO). Highest electricity rates in US.",
    "taxInfo": "State income tax: 1.4%-11%. GET tax: 4% (instead of sales tax).",
    "insuranceRules": "Auto insurance required: liability minimum 20/40/10. No-fault state. PIP required.",
    "providers": [
      {
        "name": "Hawaiian Electric",
        "url": "https://www.hawaiianelectric.com"
      },
      {
        "name": "Hawaii Gas",
        "url": "https://www.hawaiigas.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "Hawaiian Telcom",
        "url": "https://www.hawaiiantel.com"
      }
    ]
  },
  {
    "abbr": "ID",
    "name": "Idaho",
    "slug": "idaho",
    "dmvRules": "Must obtain ID DL immediately upon establishing residency. Visit county assessor office. No emissions test.",
    "voterRegistration": "Register online at idahovotes.gov. Same-day registration available.",
    "utilityInfo": "Major providers: Idaho Power, Intermountain Gas. Regulated market. Low electricity rates.",
    "taxInfo": "Flat state income tax: 5.8%. Sales tax: 6%. Property tax relatively low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/15.",
    "providers": [
      {
        "name": "Idaho Power",
        "url": "https://www.idahopower.com"
      },
      {
        "name": "Intermountain Gas",
        "url": "https://www.intgas.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      },
      {
        "name": "Cable One",
        "url": "https://www.sparklight.com"
      }
    ]
  },
  {
    "abbr": "IL",
    "name": "Illinois",
    "slug": "illinois",
    "dmvRules": "Must obtain IL DL within 90 days. Visit Secretary of State office. Vehicle emissions test in Chicago metro.",
    "voterRegistration": "Register online at ova.elections.il.gov. Same-day registration available.",
    "utilityInfo": "Major providers: ComEd, Ameren, Nicor Gas. Deregulated electricity market.",
    "taxInfo": "Flat state income tax: 4.95%. Property tax among highest in US. Sales tax: 6.25% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20. Uninsured motorist coverage recommended.",
    "providers": [
      {
        "name": "ComEd",
        "url": "https://www.comed.com"
      },
      {
        "name": "Ameren Illinois",
        "url": "https://www.ameren.com"
      },
      {
        "name": "Nicor Gas",
        "url": "https://www.nicorgas.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "IN",
    "name": "Indiana",
    "slug": "indiana",
    "dmvRules": "Must obtain IN DL within 60 days. Visit BMV branch. Emissions test in Lake and Porter counties.",
    "voterRegistration": "Register online at indianavoters.in.gov. Deadline: 29 days before election.",
    "utilityInfo": "Major providers: Duke Energy Indiana, Indiana Michigan Power, Vectren. Regulated market.",
    "taxInfo": "Flat state income tax: 3.05% + county tax. Sales tax: 7%. Property tax capped at 1-3%.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Duke Energy",
        "url": "https://www.duke-energy.com"
      },
      {
        "name": "Indiana Michigan Power",
        "url": "https://www.indianamichiganpower.com"
      },
      {
        "name": "Vectren",
        "url": "https://www.centerpointenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      }
    ]
  },
  {
    "abbr": "IA",
    "name": "Iowa",
    "slug": "iowa",
    "dmvRules": "Must obtain IA DL within 30 days. Visit county treasurer or DOT office. No emissions test.",
    "voterRegistration": "Register online at sos.iowa.gov. Same-day registration available.",
    "utilityInfo": "Major providers: MidAmerican Energy, Alliant Energy. Regulated market.",
    "taxInfo": "State income tax: 4.4%-6%. Sales tax: 6% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 20/40/15.",
    "providers": [
      {
        "name": "MidAmerican Energy",
        "url": "https://www.midamericanenergy.com"
      },
      {
        "name": "Alliant Energy",
        "url": "https://www.alliantenergy.com"
      },
      {
        "name": "Mediacom",
        "url": "https://www.mediacomcable.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "KS",
    "name": "Kansas",
    "slug": "kansas",
    "dmvRules": "Must obtain KS DL within 90 days. Visit county treasurer office. No emissions test.",
    "voterRegistration": "Register online at sos.ks.gov/elections. Deadline: 21 days before election.",
    "utilityInfo": "Major providers: Evergy, Kansas Gas Service. Regulated market.",
    "taxInfo": "State income tax: 3.1%-5.7%. Sales tax: 6.5% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25. No-fault state. PIP required.",
    "providers": [
      {
        "name": "Evergy",
        "url": "https://www.evergy.com"
      },
      {
        "name": "Kansas Gas Service",
        "url": "https://www.kansasgasservice.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      }
    ]
  },
  {
    "abbr": "KY",
    "name": "Kentucky",
    "slug": "kentucky",
    "dmvRules": "Must obtain KY DL within 30 days. Visit county clerk office. No emissions test.",
    "voterRegistration": "Register online at elect.ky.gov. Deadline: 29 days before election.",
    "utilityInfo": "Major providers: Kentucky Utilities, Louisville Gas & Electric. Regulated market. Low rates.",
    "taxInfo": "Flat state income tax: 4.5%. Sales tax: 6%. Property tax relatively low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25. No-fault state. PIP required ($10K).",
    "providers": [
      {
        "name": "Kentucky Utilities",
        "url": "https://lge-ku.com"
      },
      {
        "name": "Louisville Gas & Electric",
        "url": "https://lge-ku.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "LA",
    "name": "Louisiana",
    "slug": "louisiana",
    "dmvRules": "Must obtain LA DL within 30 days. Visit OMV office or use expresslane.org.",
    "voterRegistration": "Register online at geauxvote.com. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Entergy Louisiana, Atmos Energy. Regulated market.",
    "taxInfo": "State income tax: 1.85%-4.25%. Sales tax: 4.45% + local (combined can exceed 10%).",
    "insuranceRules": "Auto insurance required: liability minimum 15/30/25. High insurance rates statewide.",
    "providers": [
      {
        "name": "Entergy Louisiana",
        "url": "https://www.entergylouisiana.com"
      },
      {
        "name": "Atmos Energy",
        "url": "https://www.atmosenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      }
    ]
  },
  {
    "abbr": "ME",
    "name": "Maine",
    "slug": "maine",
    "dmvRules": "Must obtain ME DL within 30 days. Visit BMV office. Annual vehicle inspection required.",
    "voterRegistration": "Register online at maine.gov/sos/cec. Same-day registration available.",
    "utilityInfo": "Major providers: Central Maine Power, Versant Power. Deregulated electricity market.",
    "taxInfo": "State income tax: 5.8%-7.15%. Sales tax: 5.5%. Homestead exemption available.",
    "insuranceRules": "Auto insurance required: liability minimum 50/100/25.",
    "providers": [
      {
        "name": "Central Maine Power",
        "url": "https://www.cmpco.com"
      },
      {
        "name": "Versant Power",
        "url": "https://www.versantpower.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "Consolidated Communications",
        "url": "https://www.consolidated.com"
      }
    ]
  },
  {
    "abbr": "MD",
    "name": "Maryland",
    "slug": "maryland",
    "dmvRules": "Must obtain MD DL within 60 days. Visit MVA office. Emissions test required in most counties.",
    "voterRegistration": "Register online at elections.maryland.gov. Same-day registration available.",
    "utilityInfo": "Major providers: BGE, Pepco, Delmarva Power. Deregulated electricity market.",
    "taxInfo": "State income tax: 2%-5.75% + county tax. Sales tax: 6%. Property tax varies by county.",
    "insuranceRules": "Auto insurance required: liability minimum 30/60/15. PIP required.",
    "providers": [
      {
        "name": "BGE",
        "url": "https://www.bge.com"
      },
      {
        "name": "Pepco",
        "url": "https://www.pepco.com"
      },
      {
        "name": "Washington Gas",
        "url": "https://www.washingtongas.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon",
        "url": "https://www.verizon.com"
      }
    ]
  },
  {
    "abbr": "MA",
    "name": "Massachusetts",
    "slug": "massachusetts",
    "dmvRules": "Must obtain MA DL within 30 days. Visit RMV office. Annual vehicle inspection required.",
    "voterRegistration": "Register online at sec.state.ma.us/ovr. Deadline: 20 days before election.",
    "utilityInfo": "Major providers: Eversource, National Grid. Deregulated electricity market. High rates.",
    "taxInfo": "Flat state income tax: 5% (+ 4% surtax on income over $1M). Sales tax: 6.25%.",
    "insuranceRules": "Auto insurance required: liability minimum 20/40/5. No-fault state. PIP required.",
    "providers": [
      {
        "name": "Eversource",
        "url": "https://www.eversource.com"
      },
      {
        "name": "National Grid",
        "url": "https://www.nationalgridus.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon Fios",
        "url": "https://www.verizon.com/home/fios"
      }
    ]
  },
  {
    "abbr": "MI",
    "name": "Michigan",
    "slug": "michigan",
    "dmvRules": "Must obtain MI DL immediately upon establishing residency. Visit SOS office (appointment required).",
    "voterRegistration": "Register online at mvic.sos.state.mi.us. Same-day registration available.",
    "utilityInfo": "Major providers: DTE Energy, Consumers Energy. Partially deregulated.",
    "taxInfo": "Flat state income tax: 4.05%. Sales tax: 6%. Property tax varies.",
    "insuranceRules": "Auto insurance: No-fault state with reformed PIP. Liability minimum 50/100/10.",
    "providers": [
      {
        "name": "DTE Energy",
        "url": "https://www.dteenergy.com"
      },
      {
        "name": "Consumers Energy",
        "url": "https://www.consumersenergy.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "MN",
    "name": "Minnesota",
    "slug": "minnesota",
    "dmvRules": "Must obtain MN DL within 60 days. Visit DVS office. No emissions test.",
    "voterRegistration": "Register online at sos.state.mn.us. Same-day registration available.",
    "utilityInfo": "Major providers: Xcel Energy, CenterPoint Energy. Regulated market.",
    "taxInfo": "State income tax: 5.35%-9.85%. Sales tax: 6.875% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 30/60/10. No-fault state. PIP required.",
    "providers": [
      {
        "name": "Xcel Energy",
        "url": "https://www.xcelenergy.com"
      },
      {
        "name": "CenterPoint Energy",
        "url": "https://www.centerpointenergy.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "MS",
    "name": "Mississippi",
    "slug": "mississippi",
    "dmvRules": "Must obtain MS DL within 60 days. Visit DPS office. No emissions test.",
    "voterRegistration": "Register by mail. Deadline: 30 days before election. No online registration.",
    "utilityInfo": "Major providers: Mississippi Power, Entergy Mississippi. Regulated market.",
    "taxInfo": "State income tax: 0%-5% (first $10K exempt). Sales tax: 7%. Low property tax.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Entergy Mississippi",
        "url": "https://www.entergymississippi.com"
      },
      {
        "name": "Mississippi Power",
        "url": "https://www.mississippipower.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Sparklight",
        "url": "https://www.sparklight.com"
      }
    ]
  },
  {
    "abbr": "MO",
    "name": "Missouri",
    "slug": "missouri",
    "dmvRules": "Must obtain MO DL within 30 days. Visit license office. Emissions test in St. Louis and KC metros.",
    "voterRegistration": "Register online at sos.mo.gov/elections. Deadline: 27 days before election.",
    "utilityInfo": "Major providers: Ameren Missouri, Evergy, Spire. Regulated market.",
    "taxInfo": "State income tax: 2%-4.95%. Sales tax: 4.225% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Ameren Missouri",
        "url": "https://www.ameren.com"
      },
      {
        "name": "Evergy",
        "url": "https://www.evergy.com"
      },
      {
        "name": "Spire",
        "url": "https://www.spireenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      }
    ]
  },
  {
    "abbr": "MT",
    "name": "Montana",
    "slug": "montana",
    "dmvRules": "Must obtain MT DL within 60 days. Visit county treasurer or MVD. No vehicle inspection.",
    "voterRegistration": "Register online at sosmt.gov/elections. Same-day registration available.",
    "utilityInfo": "Major providers: NorthWestern Energy. Deregulated electricity market.",
    "taxInfo": "State income tax: 1%-6.75%. No sales tax. Property tax varies.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20.",
    "providers": [
      {
        "name": "NorthWestern Energy",
        "url": "https://www.northwesternenergy.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      }
    ]
  },
  {
    "abbr": "NE",
    "name": "Nebraska",
    "slug": "nebraska",
    "dmvRules": "Must obtain NE DL within 30 days. Visit county treasurer or DMV. No emissions test.",
    "voterRegistration": "Register online at sos.nebraska.gov/elections. Deadline: 18 days before election.",
    "utilityInfo": "Major providers: OPPD, LES, MUD. Public power state — all electricity is publicly owned.",
    "taxInfo": "State income tax: 2.46%-5.84%. Sales tax: 5.5% + local. Property tax relatively high.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "OPPD",
        "url": "https://www.oppd.com"
      },
      {
        "name": "LES",
        "url": "https://www.les.com"
      },
      {
        "name": "MUD",
        "url": "https://www.mudomaha.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "NV",
    "name": "Nevada",
    "slug": "nevada",
    "dmvRules": "Must obtain NV DL within 30 days. Visit DMV office. Emissions test in Clark and Washoe counties.",
    "voterRegistration": "Register online at nvsos.gov. Same-day registration available.",
    "utilityInfo": "Major providers: NV Energy. Partially deregulated market.",
    "taxInfo": "No state income tax. Sales tax: 6.85% + local. Low property tax.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20.",
    "providers": [
      {
        "name": "NV Energy",
        "url": "https://www.nvenergy.com"
      },
      {
        "name": "Southwest Gas",
        "url": "https://www.swgas.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "NH",
    "name": "New Hampshire",
    "slug": "new-hampshire",
    "dmvRules": "Must obtain NH DL within 60 days. Visit DMV office. Annual vehicle inspection required.",
    "voterRegistration": "Register on election day at the polls. No advance deadline required.",
    "utilityInfo": "Major providers: Eversource, Liberty Utilities. Deregulated electricity market.",
    "taxInfo": "No state income tax on wages. No sales tax. Property tax among highest in US.",
    "insuranceRules": "Auto insurance NOT mandatory (but financial responsibility required). Recommended: 25/50/25.",
    "providers": [
      {
        "name": "Eversource",
        "url": "https://www.eversource.com"
      },
      {
        "name": "Liberty Utilities",
        "url": "https://new-hampshire.libertyutilities.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Consolidated Communications",
        "url": "https://www.consolidated.com"
      }
    ]
  },
  {
    "abbr": "NJ",
    "name": "New Jersey",
    "slug": "new-jersey",
    "dmvRules": "Must obtain NJ DL within 60 days. Visit MVC. Vehicle inspection every 2-4 years.",
    "voterRegistration": "Register online at voter.svrs.nj.gov. Deadline: 21 days before election.",
    "utilityInfo": "Major providers: PSE&G, JCP&L, NJ American Water. Deregulated electricity market.",
    "taxInfo": "State income tax: 1.4%-10.75%. Sales tax: 6.625%. Property tax highest in US.",
    "insuranceRules": "Auto insurance required: liability minimum 15/30/5. No-fault state. PIP required.",
    "providers": [
      {
        "name": "PSE&G",
        "url": "https://www.pseg.com"
      },
      {
        "name": "JCP&L",
        "url": "https://www.firstenergycorp.com/jcp-l.html"
      },
      {
        "name": "NJ American Water",
        "url": "https://www.amwater.com/njaw"
      },
      {
        "name": "Optimum",
        "url": "https://www.optimum.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      }
    ]
  },
  {
    "abbr": "NM",
    "name": "New Mexico",
    "slug": "new-mexico",
    "dmvRules": "Must obtain NM DL within 30 days. Visit MVD office. Emissions test in Bernalillo County.",
    "voterRegistration": "Register online at portal.sos.state.nm.us. Same-day registration available.",
    "utilityInfo": "Major providers: PNM, New Mexico Gas Company. Regulated market.",
    "taxInfo": "State income tax: 1.7%-5.9%. Gross receipts tax: 5.125% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10.",
    "providers": [
      {
        "name": "PNM",
        "url": "https://www.pnm.com"
      },
      {
        "name": "New Mexico Gas Company",
        "url": "https://www.nmgco.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "NY",
    "name": "New York",
    "slug": "new-york",
    "dmvRules": "Must obtain NY DL within 30 days. Visit local DMV. Vehicle inspection required annually.",
    "voterRegistration": "Register online at elections.ny.gov. Deadline: 25 days before election.",
    "utilityInfo": "Major providers: Con Edison, National Grid, NYSEG. Regulated market.",
    "taxInfo": "State income tax: 4%-10.9%. NYC residents pay additional city tax. Property tax varies.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10. No-fault state. PIP required.",
    "providers": [
      {
        "name": "Con Edison",
        "url": "https://www.coned.com"
      },
      {
        "name": "National Grid",
        "url": "https://www.nationalgridus.com"
      },
      {
        "name": "PSEG",
        "url": "https://www.pseg.com"
      },
      {
        "name": "Optimum",
        "url": "https://www.optimum.com"
      },
      {
        "name": "Verizon Fios",
        "url": "https://www.verizon.com/home/fios"
      }
    ]
  },
  {
    "abbr": "NC",
    "name": "North Carolina",
    "slug": "north-carolina",
    "dmvRules": "Must obtain NC DL within 60 days. Visit NCDMV office. Annual vehicle inspection required.",
    "voterRegistration": "Register online at ncsbe.gov. Deadline: 25 days before election.",
    "utilityInfo": "Major providers: Duke Energy NC, Dominion Energy, Piedmont Natural Gas. Regulated market.",
    "taxInfo": "Flat state income tax: 4.5%. Sales tax: 4.75% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 30/60/25.",
    "providers": [
      {
        "name": "Duke Energy",
        "url": "https://www.duke-energy.com"
      },
      {
        "name": "Dominion Energy",
        "url": "https://www.dominionenergy.com"
      },
      {
        "name": "Piedmont Natural Gas",
        "url": "https://www.piedmontng.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "ND",
    "name": "North Dakota",
    "slug": "north-dakota",
    "dmvRules": "Must obtain ND DL within 60 days. Visit DOT office. No vehicle inspection.",
    "voterRegistration": "No voter registration required — bring valid ID to vote.",
    "utilityInfo": "Major providers: Xcel Energy, Montana-Dakota Utilities. Regulated market.",
    "taxInfo": "State income tax: 0%-2.5%. Sales tax: 5% + local. Low property tax.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25. No-fault state.",
    "providers": [
      {
        "name": "Xcel Energy",
        "url": "https://www.xcelenergy.com"
      },
      {
        "name": "Montana-Dakota Utilities",
        "url": "https://www.montana-dakota.com"
      },
      {
        "name": "Midcontinent Communications",
        "url": "https://www.midco.com"
      }
    ]
  },
  {
    "abbr": "OH",
    "name": "Ohio",
    "slug": "ohio",
    "dmvRules": "Must obtain OH DL within 30 days. Visit BMV deputy registrar. Emissions test in select counties.",
    "voterRegistration": "Register online at olvr.ohiosos.gov. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Ohio Edison, AEP Ohio, Duke Energy, Columbia Gas. Deregulated electricity.",
    "taxInfo": "State income tax: 0%-3.5% (first $26K exempt). Sales tax: 5.75% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Ohio Edison",
        "url": "https://www.firstenergycorp.com/ohio_edison.html"
      },
      {
        "name": "AEP Ohio",
        "url": "https://www.aepohio.com"
      },
      {
        "name": "Columbia Gas",
        "url": "https://www.columbiagas.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "OK",
    "name": "Oklahoma",
    "slug": "oklahoma",
    "dmvRules": "Must obtain OK DL within 30 days. Visit tag agency. Vehicle must be registered within 30 days.",
    "voterRegistration": "Register online at ok.gov/elections. Deadline: 25 days before election.",
    "utilityInfo": "Major providers: OG&E, PSO. Regulated market. Low electricity rates.",
    "taxInfo": "State income tax: 0.25%-4.75%. Sales tax: 4.5% + local. Low property tax.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "OG&E",
        "url": "https://www.oge.com"
      },
      {
        "name": "PSO",
        "url": "https://www.psoklahoma.com"
      },
      {
        "name": "Oklahoma Natural Gas",
        "url": "https://www.oklahomanaturalgas.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "OR",
    "name": "Oregon",
    "slug": "oregon",
    "dmvRules": "Must obtain OR DL within 30 days. Visit DMV office. No vehicle inspection.",
    "voterRegistration": "Register online at sos.oregon.gov/voting. Deadline: 21 days. All-mail voting state.",
    "utilityInfo": "Major providers: Portland General Electric, Pacific Power, NW Natural. Regulated market.",
    "taxInfo": "State income tax: 4.75%-9.9%. No sales tax. Property tax capped.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20. PIP required.",
    "providers": [
      {
        "name": "Portland General Electric",
        "url": "https://portlandgeneral.com"
      },
      {
        "name": "Pacific Power",
        "url": "https://www.pacificpower.net"
      },
      {
        "name": "NW Natural Gas",
        "url": "https://www.nwnatural.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "PA",
    "name": "Pennsylvania",
    "slug": "pennsylvania",
    "dmvRules": "Must obtain PA DL within 60 days. Visit PennDOT office. Emissions test in select counties. Annual safety inspection.",
    "voterRegistration": "Register online at vote.pa.gov. Deadline: 15 days before election.",
    "utilityInfo": "Major providers: PECO, PPL, Columbia Gas. Deregulated electricity market.",
    "taxInfo": "Flat state income tax: 3.07%. Sales tax: 6% (7-8% in some counties). Local wage taxes common.",
    "insuranceRules": "Auto insurance required: liability minimum 15/30/5. No-fault state.",
    "providers": [
      {
        "name": "PECO",
        "url": "https://www.peco.com"
      },
      {
        "name": "PPL Electric",
        "url": "https://www.pplelectric.com"
      },
      {
        "name": "Columbia Gas",
        "url": "https://www.columbiagas.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon Fios",
        "url": "https://www.verizon.com/home/fios"
      }
    ]
  },
  {
    "abbr": "RI",
    "name": "Rhode Island",
    "slug": "rhode-island",
    "dmvRules": "Must obtain RI DL within 30 days. Visit DMV office. No emissions test.",
    "voterRegistration": "Register online at vote.ri.gov. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Rhode Island Energy. Regulated market.",
    "taxInfo": "State income tax: 3.75%-5.99%. Sales tax: 7%. Property tax varies.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Rhode Island Energy",
        "url": "https://www.rienergy.com"
      },
      {
        "name": "Providence Water",
        "url": "https://www.provwater.com"
      },
      {
        "name": "Cox",
        "url": "https://www.cox.com"
      },
      {
        "name": "Verizon",
        "url": "https://www.verizon.com"
      }
    ]
  },
  {
    "abbr": "SC",
    "name": "South Carolina",
    "slug": "south-carolina",
    "dmvRules": "Must obtain SC DL within 90 days. Visit SCDMV office. No vehicle inspection.",
    "voterRegistration": "Register online at scvotes.gov. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Duke Energy, Dominion Energy. Regulated market.",
    "taxInfo": "State income tax: 0%-6.4%. Sales tax: 6% + local. Property tax relatively low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Duke Energy",
        "url": "https://www.duke-energy.com"
      },
      {
        "name": "Dominion Energy",
        "url": "https://www.dominionenergy.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "SD",
    "name": "South Dakota",
    "slug": "south-dakota",
    "dmvRules": "Must obtain SD DL within 90 days. Visit DPS office. No vehicle inspection.",
    "voterRegistration": "Register online at sdsos.gov. Deadline: 15 days before election.",
    "utilityInfo": "Major providers: Black Hills Energy, NorthWestern Energy. Regulated market.",
    "taxInfo": "No state income tax. Sales tax: 4.5% + local. Property tax moderate.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Black Hills Energy",
        "url": "https://www.blackhillsenergy.com"
      },
      {
        "name": "NorthWestern Energy",
        "url": "https://www.northwesternenergy.com"
      },
      {
        "name": "Midcontinent Communications",
        "url": "https://www.midco.com"
      }
    ]
  },
  {
    "abbr": "TN",
    "name": "Tennessee",
    "slug": "tennessee",
    "dmvRules": "Must obtain TN DL within 30 days. Visit county clerk office. Emissions test in select counties.",
    "voterRegistration": "Register online at ovr.govote.tn.gov. Deadline: 30 days before election.",
    "utilityInfo": "Major providers: Nashville Electric, Memphis Light Gas & Water, TVA. Regulated. Low rates.",
    "taxInfo": "No state income tax on wages. Sales tax: 7% + local (combined up to 9.75%).",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/15.",
    "providers": [
      {
        "name": "Nashville Electric Service",
        "url": "https://www.nespower.com"
      },
      {
        "name": "Memphis Light Gas & Water",
        "url": "https://www.mlgw.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      }
    ]
  },
  {
    "abbr": "TX",
    "name": "Texas",
    "slug": "texas",
    "dmvRules": "Must obtain TX DL within 90 days. Visit local DPS office. Vehicle inspection required within 90 days.",
    "voterRegistration": "Register by mail or in person. Deadline: 30 days before election. No online registration.",
    "utilityInfo": "Deregulated electricity market — choose your provider at powertochoose.org.",
    "taxInfo": "No state income tax. Property tax rates among highest in US (~1.8%). Sales tax: 6.25% + local.",
    "insuranceRules": "Auto insurance required: liability minimum 30/60/25.",
    "providers": [
      {
        "name": "TXU Energy",
        "url": "https://www.txu.com"
      },
      {
        "name": "Reliant",
        "url": "https://www.reliant.com"
      },
      {
        "name": "CenterPoint Energy",
        "url": "https://www.centerpointenergy.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      }
    ]
  },
  {
    "abbr": "UT",
    "name": "Utah",
    "slug": "utah",
    "dmvRules": "Must obtain UT DL within 60 days. Visit DLD office. Emissions test in select counties.",
    "voterRegistration": "Register online at vote.utah.gov. Same-day registration available. All-mail voting.",
    "utilityInfo": "Major providers: Rocky Mountain Power, Dominion Energy Utah. Regulated market.",
    "taxInfo": "Flat state income tax: 4.65%. Sales tax: 6.1% + local. Property tax relatively low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/65/15. PIP required ($3K).",
    "providers": [
      {
        "name": "Rocky Mountain Power",
        "url": "https://www.rockymountainpower.net"
      },
      {
        "name": "Dominion Energy Utah",
        "url": "https://www.dominionenergy.com/utah"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "VT",
    "name": "Vermont",
    "slug": "vermont",
    "dmvRules": "Must obtain VT DL within 60 days. Visit DMV office. Annual vehicle inspection required.",
    "voterRegistration": "Register online at olvr.vermont.gov. Same-day registration available.",
    "utilityInfo": "Major providers: Green Mountain Power. Over 99% renewable electricity.",
    "taxInfo": "State income tax: 3.35%-8.75%. Sales tax: 6% + local. Property tax relatively high.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10.",
    "providers": [
      {
        "name": "Green Mountain Power",
        "url": "https://greenmountainpower.com"
      },
      {
        "name": "Vermont Gas Systems",
        "url": "https://www.vermontgas.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Consolidated Communications",
        "url": "https://www.consolidated.com"
      }
    ]
  },
  {
    "abbr": "VA",
    "name": "Virginia",
    "slug": "virginia",
    "dmvRules": "Must obtain VA DL within 60 days. Visit DMV office. Annual safety inspection required.",
    "voterRegistration": "Register online at vote.virginia.gov. Deadline: 22 days before election.",
    "utilityInfo": "Major providers: Dominion Energy, Appalachian Power. Partially deregulated.",
    "taxInfo": "State income tax: 2%-5.75%. Sales tax: 5.3% + local. Property tax varies by locality.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20.",
    "providers": [
      {
        "name": "Dominion Energy",
        "url": "https://www.dominionenergy.com"
      },
      {
        "name": "Appalachian Power",
        "url": "https://www.appalachianpower.com"
      },
      {
        "name": "Washington Gas",
        "url": "https://www.washingtongas.com"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "Verizon",
        "url": "https://www.verizon.com"
      }
    ]
  },
  {
    "abbr": "WA",
    "name": "Washington",
    "slug": "washington",
    "dmvRules": "Must obtain WA DL within 30 days. Visit DOL office. Emissions test in select counties.",
    "voterRegistration": "Register online at sos.wa.gov/elections. Same-day registration. All-mail voting.",
    "utilityInfo": "Major providers: Puget Sound Energy, Seattle City Light. Regulated. Low rates (hydropower).",
    "taxInfo": "No state income tax. Sales tax: 6.5% + local (up to ~10%). B&O tax for businesses.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10.",
    "providers": [
      {
        "name": "Puget Sound Energy",
        "url": "https://www.pse.com"
      },
      {
        "name": "Seattle City Light",
        "url": "https://www.seattle.gov/city-light"
      },
      {
        "name": "Xfinity",
        "url": "https://www.xfinity.com"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  },
  {
    "abbr": "WV",
    "name": "West Virginia",
    "slug": "west-virginia",
    "dmvRules": "Must obtain WV DL within 30 days. Visit DMV regional office. No emissions test.",
    "voterRegistration": "Register online at ovr.sos.wv.gov. Deadline: 21 days before election.",
    "utilityInfo": "Major providers: Appalachian Power, MonPower. Regulated market. Low rates.",
    "taxInfo": "State income tax: 2.36%-5.12%. Sales tax: 6% + local. Property tax relatively low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/25.",
    "providers": [
      {
        "name": "Appalachian Power",
        "url": "https://www.appalachianpower.com"
      },
      {
        "name": "Mountaineer Gas",
        "url": "https://www.mountaineergas.com"
      },
      {
        "name": "Frontier",
        "url": "https://frontier.com"
      },
      {
        "name": "Suddenlink",
        "url": "https://www.optimum.com"
      }
    ]
  },
  {
    "abbr": "WI",
    "name": "Wisconsin",
    "slug": "wisconsin",
    "dmvRules": "Must obtain WI DL within 60 days. Visit DMV office. No vehicle inspection.",
    "voterRegistration": "Register online at myvote.wi.gov. Same-day registration available.",
    "utilityInfo": "Major providers: We Energies, Alliant Energy, Madison Gas & Electric. Regulated market.",
    "taxInfo": "State income tax: 3.54%-7.65%. Sales tax: 5% + county. Property tax moderate.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/10.",
    "providers": [
      {
        "name": "We Energies",
        "url": "https://www.we-energies.com"
      },
      {
        "name": "Alliant Energy",
        "url": "https://www.alliantenergy.com"
      },
      {
        "name": "Madison Gas & Electric",
        "url": "https://www.mge.com"
      },
      {
        "name": "Spectrum",
        "url": "https://www.spectrum.com"
      },
      {
        "name": "AT&T",
        "url": "https://www.att.com"
      }
    ]
  },
  {
    "abbr": "WY",
    "name": "Wyoming",
    "slug": "wyoming",
    "dmvRules": "Must obtain WY DL immediately upon establishing residency. Visit county clerk. No vehicle inspection.",
    "voterRegistration": "Register on election day or in advance at county clerk. No online registration.",
    "utilityInfo": "Major providers: Black Hills Energy, Rocky Mountain Power. Regulated. Low rates.",
    "taxInfo": "No state income tax. Sales tax: 4% + local. Property tax low.",
    "insuranceRules": "Auto insurance required: liability minimum 25/50/20.",
    "providers": [
      {
        "name": "Black Hills Energy",
        "url": "https://www.blackhillsenergy.com"
      },
      {
        "name": "Rocky Mountain Power",
        "url": "https://www.rockymountainpower.net"
      },
      {
        "name": "CenturyLink",
        "url": "https://www.centurylink.com"
      }
    ]
  }
];

/** Slug -> guide lookup, built once at module load. */
export const STATE_GUIDE_BY_SLUG: Record<string, StateGuide> = Object.fromEntries(
  STATE_GUIDES.map((s) => [s.slug, s]),
);

/** All slugs, for generateStaticParams + sitemap. */
export const STATE_SLUGS: string[] = STATE_GUIDES.map((s) => s.slug);

export function getStateGuide(slug: string): StateGuide | null {
  return STATE_GUIDE_BY_SLUG[slug] ?? null;
}
