/**
 * LocateFlow — CSS design-token source of truth + emitter.
 *
 * STEP 1 of the design-system foundation: this module is the *single*
 * structured source for every CSS custom property that previously lived
 * hand-synced across five files:
 *
 *   1. apps/web/src/styles/globals.css      (`:root,.dark` + `.light` + shadcn HSL)
 *   2. apps/admin/src/app/globals.css       (`:root,.dark` + `.light` + shadcn HSL)
 *   3. apps/web/src/styles/aurora.css        (`.lf-aurora` `--au-*` primitives)
 *   4. apps/admin/src/app/aurora.css         (`.adm-aurora` `--au-*` primitives)
 *
 * `scripts/emit-design-tokens.ts` consumes the maps below and writes the
 * `_tokens.generated.css` / `_aurora-tokens.generated.css` partials that
 * those files now `@import`. The drift-guard test re-runs the emitter in
 * memory and asserts the committed output is byte-identical, so a hand
 * edit to any generated file fails CI.
 *
 * PURE REFACTOR: every value below is copied verbatim from the current
 * hand-written CSS. This is *not* the place to change a colour — that is
 * Step 2. The TS runtime token model (`./design-tokens`) keeps its own
 * exports for the mobile app and is intentionally left untouched here;
 * the two models overlap conceptually but the CSS copies carried small
 * historical drifts (e.g. `--tone-foil-bg` alpha) that must be preserved
 * exactly to guarantee zero visual change.
 */

// ────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────

/** An ordered list of CSS custom-property declarations. `comment` rows
 *  emit a `/* … *\/` line; `blank` rows emit an empty line; `var` rows
 *  emit `  --name: value;` aligned to the block's declared padding. */
export type TokenRow =
  | { kind: "var"; name: string; value: string }
  | { kind: "comment"; text: string }
  | { kind: "blank" }
  /** Pre-formatted raw line emitted verbatim (used for the admin aurora
   *  single-line tone triplets that pack three decls per source line). */
  | { kind: "raw"; text: string };

export interface CssBlock {
  /** Selector list, e.g. `":root,\n.dark"` or `".light .lf-aurora"`. */
  selector: string;
  rows: TokenRow[];
}

export interface CssLayer {
  /** When set, wraps `blocks` in `@layer <name> { … }`. */
  layer?: string;
  blocks: CssBlock[];
}

// ────────────────────────────────────────────────────────────────────
// Emitter
// ────────────────────────────────────────────────────────────────────

const v = (name: string, value: string): TokenRow => ({ kind: "var", name, value });
const c = (text: string): TokenRow => ({ kind: "comment", text });
const raw = (text: string): TokenRow => ({ kind: "raw", text });
const blank: TokenRow = { kind: "blank" };

export interface EmitOptions {
  /**
   * Minimum column width for the `--name:` portion of each declaration.
   * The actual width per block is `max(pad, longest `--name:` in the block
   * + 1)` so every value is preceded by at least one space and the colons
   * align within a block.
   */
  pad: number;
}

/**
 * Emit a list of layers/blocks to a CSS partial string with the leading
 * "generated" banner. This is the shared rendering engine; `renderTarget`
 * is a thin wrapper that pairs a layer set with its output path and pad.
 */
export function emitCssVars(layers: CssLayer[], options: EmitOptions): string {
  const out: string[] = [GENERATED_BANNER, ""];

  for (const layer of layers) {
    if (layer.layer) {
      out.push(`@layer ${layer.layer} {`);
      const parts = layer.blocks.map((block) =>
        block.selector === "__PLAN__"
          ? renderPlanRows(block.rows, "  ")
          : renderBlock(block, "  ", options.pad),
      );
      out.push(parts.join("\n\n"));
      out.push("}");
    } else {
      const parts = layer.blocks.map((b) => renderBlock(b, "", options.pad));
      out.push(parts.join("\n\n"));
    }
    out.push("");
  }

  // Collapse trailing blanks into a single terminal newline.
  return out.join("\n").replace(/\n+$/, "\n");
}

export const GENERATED_BANNER =
  "/* AUTO-GENERATED by scripts/emit-design-tokens.ts — DO NOT EDIT.\n" +
  "   Source of truth: packages/shared/src/design-tokens-css.ts.\n" +
  "   Run `pnpm tokens:emit` after editing the model. */";

// ════════════════════════════════════════════════════════════════════
// 1 + 2 · App globals.css token model (web + admin)
// ════════════════════════════════════════════════════════════════════

// ── WEB globals.css ─────────────────────────────────────────────────

const webRootDark: CssBlock = {
  selector: ":root,\n.dark",
  rows: [
    c("─────────────── Brand core — LocateFlow Gold primary ───────────────"),
    v("rose", "#CBA45E"),
    v("rose-light", "#DCBC7C"),
    v("rose-deep", "#B0852F"),
    v("rose-dark", "#86631A"),
    blank,
    v("foil-a", "#DCBC7C"),
    v("foil-b", "#CBA45E"),
    v("foil-c", "#B0852F"),
    v("foil", "#CBA45E"),
    v("foil-ink", "#86631A"),
    blank,
    v("nude", "#CBA45E"),
    v("nude-deep", "#B0852F"),
    blank,
    v("sage", "#54CB7E"),
    v("sage-soft", "#8BE3A8"),
    blank,
    c("Legacy brand aliases — flipped to LocateFlow Gold; amber stays semantic warn"),
    v("brand-orange", "#CBA45E"),
    v("brand-orange-light", "#DCBC7C"),
    v("brand-orange-dark", "#B0852F"),
    v("brand-amber", "#E0A85A"),
    blank,
    c('"orange" scale — now the LocateFlow Gold scale (kept for `bg-orange-500` etc.)'),
    v("orange-50", "#FFF8E8"),
    v("orange-100", "#F8E8BF"),
    v("orange-200", "#EAD095"),
    v("orange-300", "#DCBC7C"),
    v("orange-400", "#CBA45E"),
    v("orange-500", "#CBA45E"),
    v("orange-600", "#B0852F"),
    v("orange-700", "#9A7325"),
    v("orange-800", "#86631A"),
    v("orange-900", "#5F4614"),
    blank,
    c("Honest canonical names (D13) — additive aliases of the brand/semantic\n     hues by their true colour. Gold + Sapphire are literal regardless of\n     mode; teal/green follow the per-mode info/success ramp. Legacy aliases\n     (rose/foil/sage/brand-orange/tone-*) above stay as-is (no codemod)."),
    v("gold", "#CBA45E"),
    v("sapphire", "#2E5FB0"),
    v("teal", "#37C2C9"),
    v("green", "#54CB7E"),
    blank,
    c("─────────────── Surfaces — Aurora deep navy ───────────────────────────"),
    v("bg", "#070B14"),
    v("bg-deep", "#060B18"),
    v("surface", "#121B2D"),
    v("surface-2", "#18233A"),
    v("surface-3", "#1F2C47"),
    v("elevated", "#1D2943"),
    blank,
    c("─────────────── Foreground — LocateFlow dark ink ramp ─────────────────"),
    v("fg", "#EFF3FA"),
    v("fg-1", "rgba(239, 243, 250, 1)"),
    v("fg-2", "rgba(239, 243, 250, 0.66)"),
    v("fg-3", "rgba(239, 243, 250, 0.43)"),
    v("fg-4", "rgba(239, 243, 250, 0.30)"),
    v("fg-muted", "rgba(239, 243, 250, 0.22)"),
    blank,
    c("─────────────── Borders ───────────────────────────────────────────────"),
    v("line", "rgba(110, 150, 225, 0.12)"),
    v("line-2", "rgba(110, 150, 225, 0.18)"),
    v("line-foil", "rgba(203, 164, 94, 0.24)"),
    v("line-rose", "rgba(203, 164, 94, 0.30)"),
    v("border-strong", "rgba(255, 255, 255, 0.14)"),
    v("border-focus", "rgba(203, 164, 94, 0.55)"),
    blank,
    c("─────────────── Glass ───────────────────────────────────────────────────"),
    v("glass-bg", "rgba(255, 255, 255, 0.03)"),
    v("glass-border", "rgba(255, 255, 255, 0.05)"),
    v("glass-hover", "rgba(255, 255, 255, 0.08)"),
    blank,
    c("─────────────── Semantic — Aurora mint / amber / coral / cool ─────────"),
    v("success", "#54CB7E"),
    v("success-soft", "rgba(84, 203, 126, 0.14)"),
    v("warning", "#E0A85A"),
    v("warning-soft", "rgba(224, 168, 90, 0.16)"),
    v("danger", "#E25C5C"),
    v("danger-soft", "rgba(226, 92, 92, 0.16)"),
    v("info", "#37C2C9"),
    v("info-soft", "rgba(55, 194, 201, 0.14)"),
    blank,
    c("─────────────── Tonal pairs — six Aurora tones ──────────────────────────"),
    v("tone-rose-bg", "rgba(226, 92, 92, 0.16)"),
    v("tone-rose-br", "rgba(226, 92, 92, 0.28)"),
    v("tone-rose-fg", "#E25C5C"),
    blank,
    v("tone-foil-bg", "rgba(203, 164, 94, 0.10)"),
    v("tone-foil-br", "rgba(203, 164, 94, 0.24)"),
    v("tone-foil-fg", "#CBA45E"),
    blank,
    v("tone-sage-bg", "rgba(84, 203, 126, 0.10)"),
    v("tone-sage-br", "rgba(84, 203, 126, 0.22)"),
    v("tone-sage-fg", "#54CB7E"),
    blank,
    v("tone-honey-bg", "rgba(224, 168, 90, 0.16)"),
    v("tone-honey-br", "rgba(224, 168, 90, 0.24)"),
    v("tone-honey-fg", "#E0A85A"),
    blank,
    v("tone-umber-bg", "rgba(176, 133, 47, 0.10)"),
    v("tone-umber-br", "rgba(176, 133, 47, 0.22)"),
    v("tone-umber-fg", "#B0852F"),
    blank,
    v("tone-slate-bg", "rgba(168, 181, 201, 0.10)"),
    v("tone-slate-br", "rgba(168, 181, 201, 0.22)"),
    v("tone-slate-fg", "#A8B5C9"),
    blank,
    c("Legacy tone aliases — orange→rose(cool), emerald→sage(mint),\n     amber→honey(amber), sky/cyan→slate(ink-2)."),
    v("tone-orange-bg", "rgba(203, 164, 94, 0.10)"),
    v("tone-orange-br", "rgba(203, 164, 94, 0.22)"),
    v("tone-orange-fg", "#CBA45E"),
    v("tone-emerald-bg", "rgba(84, 203, 126, 0.10)"),
    v("tone-emerald-br", "rgba(84, 203, 126, 0.22)"),
    v("tone-emerald-fg", "#54CB7E"),
    v("tone-amber-bg", "rgba(224, 168, 90, 0.16)"),
    v("tone-amber-br", "rgba(224, 168, 90, 0.24)"),
    v("tone-amber-fg", "#E0A85A"),
    v("tone-sky-bg", "rgba(55, 194, 201, 0.10)"),
    v("tone-sky-br", "rgba(55, 194, 201, 0.22)"),
    v("tone-sky-fg", "#37C2C9"),
    v("tone-cyan-bg", "rgba(55, 194, 201, 0.10)"),
    v("tone-cyan-br", "rgba(55, 194, 201, 0.22)"),
    v("tone-cyan-fg", "#37C2C9"),
    blank,
    c("─────────────── Radii ───────────────"),
    v("radius-sm", "8px"),
    v("radius-md", "13px"),
    v("radius-lg", "18px"),
    v("radius-xl", "22px"),
    v("radius-2xl", "26px"),
    v("radius-full", "9999px"),
    blank,
    c("─────────────── Spacing ───────────────"),
    v("space-xs", "4px"),
    v("space-sm", "8px"),
    v("space-md", "12px"),
    v("space-lg", "16px"),
    v("space-xl", "20px"),
    v("space-2xl", "24px"),
    v("space-3xl", "32px"),
    v("space-4xl", "40px"),
    v("space-5xl", "56px"),
    v("space-6xl", "80px"),
    blank,
    c("─────────────── Shadows ───────────────"),
    v("shadow-xs", "0 1px 2px rgba(0, 0, 0, 0.25)"),
    v("shadow-sm", "0 2px 6px rgba(0, 0, 0, 0.28)"),
    v("shadow-md", "0 6px 18px rgba(0, 0, 0, 0.40)"),
    v("shadow-lg", "0 20px 50px rgba(0, 0, 0, 0.55)"),
    v("shadow-xl", "0 40px 80px rgba(0, 0, 0, 0.60)"),
    v("shadow-rose", "0 0 20px rgba(203, 164, 94, 0.28)"),
    v("shadow-foil", "0 0 30px rgba(203, 164, 94, 0.20)"),
    v("shadow-glow", "0 0 20px rgba(203, 164, 94, 0.28)"),
    blank,
    c("─────────────── Typography ───────────────"),
    v("font-display", 'var(--font-playfair), "Playfair Display", "Didot", Georgia, serif'),
    v("font-sans", 'var(--font-dm-sans), "DM Sans", "Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif'),
    v("font-mono", 'var(--font-dm-mono), "DM Mono", "Geist Mono", "JetBrains Mono", ui-monospace, Consolas, monospace'),
    blank,
    v("fs-xs", "11px"),
    v("fs-sm", "12px"),
    v("fs-base", "14px"),
    v("fs-md", "15px"),
    v("fs-lg", "16px"),
    v("fs-xl", "18px"),
    v("fs-2xl", "22px"),
    v("fs-3xl", "28px"),
    v("fs-4xl", "36px"),
    v("fs-display", "48px"),
    v("fs-display-lg", "72px"),
    v("fs-display-xl", "96px"),
    blank,
    v("fw-light", "300"),
    v("fw-regular", "400"),
    v("fw-medium", "500"),
    v("fw-semibold", "600"),
    v("fw-bold", "700"),
    v("fw-black", "800"),
    blank,
    v("lh-tight", "1.0"),
    v("lh-snug", "1.15"),
    v("lh-normal", "1.45"),
    v("lh-relaxed", "1.7"),
    blank,
    v("tracking-tightest", "0"),
    v("tracking-tight", "0"),
    v("tracking-normal", "0"),
    v("tracking-wide", "0.04em"),
    v("tracking-mono", "0.14em"),
    blank,
    c("Legacy display axis presets; ignored when the current font lacks these axes."),
    v("fv-display-hero", '"opsz" 144, "SOFT" 50'),
    v("fv-display-h2", '"opsz"  96, "SOFT" 40'),
    v("fv-display-h3", '"opsz"  48, "SOFT" 30'),
    v("fv-display-sm", '"opsz"  36, "SOFT" 20'),
  ],
};

const webLight: CssBlock = {
  selector: ".light",
  rows: [
    v("bg", "#EFEADF"),
    v("bg-deep", "#E7E1D4"),
    v("surface", "#FFFFFF"),
    v("surface-2", "#F5F0E7"),
    v("surface-3", "#ECE6DA"),
    v("elevated", "#FFFFFF"),
    blank,
    v("fg", "#14202F"),
    v("fg-1", "#14202F"),
    v("fg-2", "rgba(20, 32, 47, 0.72)"),
    v("fg-3", "rgba(20, 32, 47, 0.50)"),
    v("fg-4", "rgba(20, 32, 47, 0.30)"),
    v("fg-muted", "rgba(20, 32, 47, 0.30)"),
    blank,
    v("line", "rgba(20, 32, 47, 0.06)"),
    v("line-2", "rgba(20, 32, 47, 0.14)"),
    v("line-foil", "rgba(46, 95, 176, 0.30)"),
    v("line-rose", "rgba(46, 95, 176, 0.30)"),
    v("border-strong", "rgba(20, 32, 47, 0.14)"),
    v("border-focus", "rgba(46, 95, 176, 0.55)"),
    blank,
    v("glass-bg", "rgba(255, 255, 255, 0.55)"),
    v("glass-border", "rgba(20, 32, 47, 0.06)"),
    v("glass-hover", "rgba(255, 255, 255, 0.92)"),
    blank,
    c("Accents: Sapphire on light paper; dark mode remaps these tokens to Gold."),
    v("rose", "#2E5FB0"),
    v("rose-light", "#3D74C8"),
    v("rose-deep", "#2E5FB0"),
    v("foil", "#2E5FB0"),
    v("foil-ink", "#244C90"),
    v("sage", "#0F6B50"),
    blank,
    v("tone-rose-fg", "#A83333"),
    v("tone-foil-fg", "#244C90"),
    v("tone-sage-fg", "#0F6B50"),
    v("tone-honey-fg", "#7A5418"),
    v("tone-umber-fg", "#244C90"),
    v("tone-slate-fg", "#4A5C75"),
    v("tone-orange-fg", "#244C90"),
    v("tone-emerald-fg", "#0F6B50"),
    v("tone-amber-fg", "#7A5418"),
    v("tone-sky-fg", "#16666B"),
    v("tone-cyan-fg", "#16666B"),
    blank,
    c("Tonal alphas — Aurora light ramp (darker text-on-paper, lighter bg)."),
    v("tone-rose-bg", "rgba(168, 51, 51, 0.10)"),
    v("tone-rose-br", "rgba(168, 51, 51, 0.22)"),
    v("tone-foil-bg", "rgba(46, 95, 176, 0.10)"),
    v("tone-foil-br", "rgba(46, 95, 176, 0.22)"),
    v("tone-sage-bg", "rgba(15, 107, 80, 0.10)"),
    v("tone-sage-br", "rgba(15, 107, 80, 0.22)"),
    v("tone-honey-bg", "rgba(138, 91, 22, 0.10)"),
    v("tone-honey-br", "rgba(138, 91, 22, 0.22)"),
    v("tone-umber-bg", "rgba(46, 95, 176, 0.10)"),
    v("tone-umber-br", "rgba(46, 95, 176, 0.22)"),
    v("tone-slate-bg", "rgba(74, 92, 117, 0.10)"),
    v("tone-slate-br", "rgba(74, 92, 117, 0.22)"),
    v("tone-orange-bg", "rgba(46, 95, 176, 0.10)"),
    v("tone-orange-br", "rgba(46, 95, 176, 0.22)"),
    v("tone-emerald-bg", "rgba(15, 107, 80, 0.10)"),
    v("tone-emerald-br", "rgba(15, 107, 80, 0.22)"),
    v("tone-amber-bg", "rgba(138, 91, 22, 0.10)"),
    v("tone-amber-br", "rgba(138, 91, 22, 0.22)"),
    v("tone-sky-bg", "rgba(22, 102, 107, 0.10)"),
    v("tone-sky-br", "rgba(22, 102, 107, 0.22)"),
    v("tone-cyan-bg", "rgba(22, 102, 107, 0.10)"),
    v("tone-cyan-br", "rgba(22, 102, 107, 0.22)"),
    blank,
    v("orange-50", "#EEF5FF"),
    v("orange-100", "#DBE8FF"),
    v("orange-200", "#C8D9FB"),
    v("orange-300", "#A9C5F8"),
    v("orange-400", "#2E5FB0"),
    v("orange-500", "#2E5FB0"),
    v("orange-600", "#2E5FB0"),
    v("orange-700", "#244C90"),
    v("orange-800", "#244C90"),
    v("orange-900", "#18345F"),
    blank,
    v("brand-orange", "#2E5FB0"),
    v("brand-orange-light", "#3D74C8"),
    v("brand-orange-dark", "#2E5FB0"),
    blank,
    c("Honest canonical names (D13) — Gold + Sapphire stay literal; teal/green\n     follow the AA-safe light info/success ramp."),
    v("gold", "#CBA45E"),
    v("sapphire", "#2E5FB0"),
    v("teal", "#16666B"),
    v("green", "#0F6B50"),
    blank,
    c("Semantic — Aurora light ramp. Darker ink-on-paper hues for AA contrast."),
    v("success", "#0F6B50"),
    v("success-soft", "rgba(15, 107, 80, 0.10)"),
    v("warning", "#7A5418"),
    v("warning-soft", "rgba(138, 91, 22, 0.10)"),
    v("danger", "#A83333"),
    v("danger-soft", "rgba(168, 51, 51, 0.10)"),
    v("info", "#16666B"),
    v("info-soft", "rgba(22, 102, 107, 0.10)"),
    blank,
    c("Glow shadows — flip from cool-on-dark to cool-on-paper."),
    v("shadow-rose", "0 0 20px rgba(46, 95, 176, 0.20)"),
    v("shadow-foil", "0 0 30px rgba(46, 95, 176, 0.16)"),
    v("shadow-glow", "0 0 20px rgba(46, 95, 176, 0.20)"),
  ],
};

const webShadcnRootDark: CssBlock = {
  selector: ":root,\n  .dark",
  rows: [
    v("background", "218 43% 6%"),
    v("foreground", "214 36% 95%"),
    blank,
    v("card", "217 41% 9%"),
    v("card-foreground", "214 36% 95%"),
    blank,
    v("popover", "217 41% 9%"),
    v("popover-foreground", "214 36% 95%"),
    blank,
    v("primary", "38.53 51.17% 58.24%"),
    v("primary-foreground", "218 43% 6%"),
    blank,
    v("secondary", "215 22% 72%"),
    v("secondary-foreground", "218 43% 6%"),
    blank,
    v("muted", "217 38% 12%"),
    v("muted-foreground", "215 18% 65%"),
    blank,
    v("accent", "217 38% 14%"),
    v("accent-foreground", "214 36% 95%"),
    blank,
    v("destructive", "359 75% 75%"),
    v("destructive-foreground", "218 43% 6%"),
    blank,
    v("warning", "35 68% 62%"),
    v("success", "156 56% 70%"),
    v("info", "183 57% 50%"),
    blank,
    v("border", "217 32% 18%"),
    v("input", "217 32% 18%"),
    v("ring", "38.53 51.17% 58.24%"),
    blank,
    raw("--radius: 0.625rem; /* 10px */"),
    blank,
    c("Legacy short surface tokens — Aurora navy"),
    v("surface-secondary", "#131C2C"),
    v("text-primary", "rgba(236, 241, 248, 1)"),
    v("text-secondary", "rgba(236, 241, 248, 0.66)"),
    v("text-tertiary", "rgba(236, 241, 248, 0.43)"),
  ],
};

// Plan classes + light shadcn block — emitted as raw lines to preserve the
// exact one-line formatting of the originals.
const webShadcnPlanRows: TokenRow[] = [
  c("Plan classes are kept for legacy selectors, but all resolve to the\n     canonical LocateFlow accent. Plan identity should be expressed by\n     copy/badges, not by changing the global brand color."),
  raw(".plan-free { --primary: 38.53 51.17% 58.24%; --ring: 38.53 51.17% 58.24%; }"),
  raw(".light .plan-free { --primary: 217.38 58.56% 43.53%; --ring: 217.38 58.56% 43.53%; }"),
  raw(".plan-family { --primary: 38.53 51.17% 58.24%; --ring: 38.53 51.17% 58.24%; }"),
  raw(".light .plan-family { --primary: 217.38 58.56% 43.53%; --ring: 217.38 58.56% 43.53%; }"),
  raw(".plan-pro { --primary: 38.53 51.17% 58.24%; --ring: 38.53 51.17% 58.24%; }"),
  raw(".light .plan-pro { --primary: 217.38 58.56% 43.53%; --ring: 217.38 58.56% 43.53%; }"),
];

const webShadcnLight: CssBlock = {
  selector: ".light",
  rows: [
    v("background", "220 33% 97%"),
    v("foreground", "213 39% 13%"),
    blank,
    v("card", "0 0% 100%"),
    v("card-foreground", "213 39% 13%"),
    blank,
    v("popover", "0 0% 100%"),
    v("popover-foreground", "213 39% 13%"),
    blank,
    v("primary", "217.38 58.56% 43.53%"),
    v("primary-foreground", "0 0% 100%"),
    blank,
    v("secondary", "214 22% 38%"),
    v("secondary-foreground", "0 0% 100%"),
    blank,
    v("muted", "214 36% 95%"),
    v("muted-foreground", "213 18% 30%"),
    blank,
    v("accent", "38 42% 94%"),
    v("accent-foreground", "213 39% 13%"),
    blank,
    v("destructive", "358 47% 43%"),
    v("destructive-foreground", "0 0% 100%"),
    blank,
    v("warning", "36.73 67.12% 28.63%"),
    v("success", "162 75% 24%"),
    v("info", "184 66% 25%"),
    blank,
    v("border", "214 24% 82%"),
    v("input", "214 24% 82%"),
    v("ring", "217.38 58.56% 43.53%"),
    blank,
    v("radius", "0.625rem"),
    blank,
    c("Legacy short surface tokens — warm paper canvas"),
    v("surface-secondary", "#FFFFFF"),
    v("text-primary", "rgba(20, 32, 47, 1)"),
    v("text-secondary", "rgba(20, 32, 47, 0.72)"),
    v("text-tertiary", "rgba(20, 32, 47, 0.50)"),
  ],
};

// ── ADMIN globals.css ───────────────────────────────────────────────

const adminRootDark: CssBlock = {
  selector: ":root,\n.dark",
  rows: [
    v("rose", "#CBA45E"),
    v("rose-light", "#DCBC7C"),
    v("rose-deep", "#B0852F"),
    v("rose-dark", "#86631A"),
    v("foil-a", "#DCBC7C"),
    v("foil-b", "#CBA45E"),
    v("foil-c", "#B0852F"),
    v("foil", "#CBA45E"),
    v("foil-ink", "#86631A"),
    v("sage", "#54CB7E"),
    blank,
    v("brand-orange", "#CBA45E"),
    v("brand-orange-light", "#DCBC7C"),
    v("brand-orange-dark", "#B0852F"),
    v("brand-amber", "#E0A85A"),
    blank,
    v("orange-50", "#FFF8E8"),
    v("orange-100", "#F8E8BF"),
    v("orange-200", "#EAD095"),
    v("orange-300", "#DCBC7C"),
    v("orange-400", "#CBA45E"),
    v("orange-500", "#CBA45E"),
    v("orange-600", "#B0852F"),
    v("orange-700", "#9A7325"),
    v("orange-800", "#86631A"),
    v("orange-900", "#5F4614"),
    blank,
    c("Honest canonical names (D13) — Gold + Sapphire literal; teal/green\n     follow the per-mode info/success ramp."),
    v("gold", "#CBA45E"),
    v("sapphire", "#2E5FB0"),
    v("teal", "#37C2C9"),
    v("green", "#54CB7E"),
    blank,
    v("bg", "#070B14"),
    v("panel", "#0E1626"),
    v("panel2", "#16203A"),
    v("surface", "#121B2D"),
    v("surface-2", "#18233A"),
    v("surface-3", "#1F2C47"),
    blank,
    v("line", "rgba(255, 255, 255, 0.10)"),
    v("line-2", "rgba(255, 255, 255, 0.16)"),
    v("line-foil", "rgba(203, 164, 94, 0.22)"),
    v("border-focus", "rgba(203, 164, 94, 0.55)"),
    blank,
    raw("--tone-rose-bg: rgba(226, 92, 92, 0.16); --tone-rose-br: rgba(226, 92, 92, 0.32); --tone-rose-fg: #E25C5C;"),
    raw("--tone-foil-bg: rgba(203, 164, 94, 0.16); --tone-foil-br: rgba(203, 164, 94, 0.32); --tone-foil-fg: #DCBC7C;"),
    raw("--tone-sage-bg: rgba(84, 203, 126, 0.16); --tone-sage-br: rgba(84, 203, 126, 0.32); --tone-sage-fg: #A0EAD2;"),
    raw("--tone-honey-bg: rgba(224, 168, 90, 0.16); --tone-honey-br: rgba(224, 168, 90, 0.32); --tone-honey-fg: #E0A85A;"),
    raw("--tone-umber-bg: rgba(217, 154, 78, 0.16); --tone-umber-br: rgba(217, 154, 78, 0.32); --tone-umber-fg: #E2B873;"),
    raw("--tone-slate-bg: rgba(168, 181, 201, 0.16); --tone-slate-br: rgba(168, 181, 201, 0.32); --tone-slate-fg: #C3CEDD;"),
    raw("--tone-orange-bg: rgba(203, 164, 94, 0.16); --tone-orange-br: rgba(203, 164, 94, 0.32); --tone-orange-fg: #CBA45E;"),
    raw("--tone-emerald-bg: rgba(84, 203, 126, 0.16); --tone-emerald-br: rgba(84, 203, 126, 0.32); --tone-emerald-fg: #A0EAD2;"),
    raw("--tone-amber-bg: rgba(224, 168, 90, 0.16); --tone-amber-br: rgba(224, 168, 90, 0.32); --tone-amber-fg: #E0A85A;"),
    raw("--tone-sky-bg: rgba(55, 194, 201, 0.14); --tone-sky-br: rgba(55, 194, 201, 0.28); --tone-sky-fg: #37C2C9;"),
    raw("--tone-cyan-bg: rgba(55, 194, 201, 0.14); --tone-cyan-br: rgba(55, 194, 201, 0.28); --tone-cyan-fg: #37C2C9;"),
    blank,
    v("shadow-glow", "0 0 10px rgba(203, 164, 94, 0.16)"),
    v("shadow-rose", "0 0 10px rgba(203, 164, 94, 0.16)"),
    v("shadow-foil", "0 0 14px rgba(203, 164, 94, 0.07)"),
    blank,
    c("Semantic — Aurora ramp. Consumed by Tailwind `bg-success` etc."),
    v("success", "#54CB7E"),
    v("success-soft", "rgba(84, 203, 126, 0.14)"),
    v("warning", "#E0A85A"),
    v("warning-soft", "rgba(224, 168, 90, 0.16)"),
    v("danger", "#E25C5C"),
    v("danger-soft", "rgba(226, 92, 92, 0.16)"),
    v("info", "#37C2C9"),
    v("info-soft", "rgba(55, 194, 201, 0.14)"),
  ],
};

const adminLight: CssBlock = {
  selector: ".light",
  rows: [
    v("rose", "#2E5FB0"),
    v("rose-light", "#3D74C8"),
    v("rose-deep", "#2E5FB0"),
    v("rose-dark", "#18345F"),
    v("foil-a", "#3D74C8"),
    v("foil-b", "#2E5FB0"),
    v("foil-c", "#244C90"),
    v("foil", "#2E5FB0"),
    v("foil-ink", "#2E5FB0"),
    v("sage", "#0F6B50"),
    blank,
    v("brand-orange", "#2E5FB0"),
    v("brand-orange-light", "#3D74C8"),
    v("brand-orange-dark", "#2E5FB0"),
    v("brand-amber", "#7A5418"),
    blank,
    v("orange-50", "#EEF5FF"),
    v("orange-100", "#DBE8FF"),
    v("orange-200", "#C8D9FB"),
    v("orange-300", "#A9C5F8"),
    v("orange-400", "#3D74C8"),
    v("orange-500", "#2E5FB0"),
    v("orange-600", "#2E5FB0"),
    v("orange-700", "#2E5FB0"),
    v("orange-800", "#244C90"),
    v("orange-900", "#18345F"),
    blank,
    c("Honest canonical names (D13) — Gold + Sapphire literal; teal/green\n     follow the AA-safe light info/success ramp."),
    v("gold", "#CBA45E"),
    v("sapphire", "#2E5FB0"),
    v("teal", "#16666B"),
    v("green", "#0F6B50"),
    blank,
    v("bg", "#F2F4F8"),
    v("surface", "#FFFFFF"),
    v("surface-2", "#EAEEF4"),
    v("surface-3", "#E2E7EE"),
    blank,
    v("line", "rgba(20, 32, 47, 0.06)"),
    v("line-2", "rgba(20, 32, 47, 0.14)"),
    v("line-foil", "rgba(46, 95, 176, 0.30)"),
    v("border-focus", "rgba(46, 95, 176, 0.55)"),
    blank,
    raw("--tone-rose-bg: rgba(168, 51, 51, 0.10); --tone-rose-br: rgba(168, 51, 51, 0.22); --tone-rose-fg: #A83333;"),
    raw("--tone-foil-bg: rgba(46, 95, 176, 0.10); --tone-foil-br: rgba(46, 95, 176, 0.22); --tone-foil-fg: #244C90;"),
    raw("--tone-sage-bg: rgba(15, 107, 80, 0.10); --tone-sage-br: rgba(15, 107, 80, 0.22); --tone-sage-fg: #0F6B50;"),
    raw("--tone-honey-bg: rgba(185, 131, 24, 0.10); --tone-honey-br: rgba(185, 131, 24, 0.22); --tone-honey-fg: #7A5418;"),
    raw("--tone-umber-bg: rgba(46, 95, 176, 0.10); --tone-umber-br: rgba(46, 95, 176, 0.22); --tone-umber-fg: #244C90;"),
    raw("--tone-slate-bg: rgba(74, 92, 117, 0.10); --tone-slate-br: rgba(74, 92, 117, 0.22); --tone-slate-fg: #4A5C75;"),
    raw("--tone-orange-bg: rgba(46, 95, 176, 0.10); --tone-orange-br: rgba(46, 95, 176, 0.22); --tone-orange-fg: #244C90;"),
    raw("--tone-emerald-bg: rgba(15, 107, 80, 0.10); --tone-emerald-br: rgba(15, 107, 80, 0.22); --tone-emerald-fg: #0F6B50;"),
    raw("--tone-amber-bg: rgba(185, 131, 24, 0.10); --tone-amber-br: rgba(185, 131, 24, 0.22); --tone-amber-fg: #7A5418;"),
    raw("--tone-sky-bg: rgba(22, 102, 107, 0.10); --tone-sky-br: rgba(22, 102, 107, 0.22); --tone-sky-fg: #16666B;"),
    raw("--tone-cyan-bg: rgba(22, 102, 107, 0.10); --tone-cyan-br: rgba(22, 102, 107, 0.22); --tone-cyan-fg: #16666B;"),
    blank,
    v("shadow-glow", "0 0 20px rgba(46, 95, 176, 0.18)"),
    v("shadow-rose", "0 0 20px rgba(46, 95, 176, 0.18)"),
    v("shadow-foil", "0 0 30px rgba(46, 95, 176, 0.14)"),
    blank,
    v("success", "#0F6B50"),
    v("success-soft", "rgba(15, 107, 80, 0.10)"),
    v("warning", "#7A5418"),
    v("warning-soft", "rgba(185, 131, 24, 0.10)"),
    v("danger", "#A83333"),
    v("danger-soft", "rgba(168, 51, 51, 0.10)"),
    v("info", "#16666B"),
    v("info-soft", "rgba(22, 102, 107, 0.10)"),
  ],
};

const adminShadcnRoot: CssBlock = {
  selector: ":root",
  rows: [
    c("Light mode — Aurora soft sky paper"),
    v("background", "220 23% 96%"),
    v("foreground", "213 39% 13%"),
    v("card", "218 21% 92%"),
    v("card-foreground", "213 39% 13%"),
    v("popover", "218 21% 96%"),
    v("popover-foreground", "213 39% 13%"),
    v("primary", "217.38 58.56% 43.53%"),
    v("primary-foreground", "0 0% 100%"),
    v("secondary", "214 22% 38%"),
    v("secondary-foreground", "0 0% 100%"),
    v("muted", "218 21% 88%"),
    v("muted-foreground", "213 18% 30%"),
    v("accent", "218 21% 90%"),
    v("accent-foreground", "213 39% 13%"),
    v("destructive", "359 51% 49%"),
    v("destructive-foreground", "0 0% 100%"),
    v("border", "213 18% 82%"),
    v("input", "213 18% 82%"),
    v("ring", "217.38 58.56% 43.53%"),
    v("radius", "0.5rem"),
  ],
};

const adminShadcnDark: CssBlock = {
  selector: ".dark",
  rows: [
    c("Dark mode — unified Aurora navy canvas (D7): admin shares web's\n       #070B14 navy surfaces (graphite #171E2B dropped). Gold primary\n       accent + cool navy panels; hairline borders, calm contrast steps."),
    v("background", "222 48% 5%"),
    v("foreground", "220 16% 98%"),
    v("card", "220 46% 10%"),
    v("card-foreground", "220 16% 98%"),
    v("popover", "220 46% 10%"),
    v("popover-foreground", "220 16% 98%"),
    v("primary", "38.53 51.17% 58.24%"),
    v("primary-foreground", "222 40% 8%"),
    v("secondary", "220 10% 82%"),
    v("secondary-foreground", "222 40% 8%"),
    v("muted", "221 41% 16%"),
    v("muted-foreground", "215 22% 78%"),
    v("accent", "220 39% 20%"),
    v("accent-foreground", "220 16% 98%"),
    v("destructive", "359 68% 70%"),
    v("destructive-foreground", "222 40% 8%"),
    v("border", "223 45% 16%"),
    v("input", "223 45% 16%"),
    v("ring", "38.53 51.17% 58.24%"),
  ],
};

// ════════════════════════════════════════════════════════════════════
// 3 + 4 · aurora.css `--au-*` primitive model (web + admin)
// ════════════════════════════════════════════════════════════════════

const webAuroraDark: CssBlock = {
  selector: ".lf-aurora",
  rows: [
    c("Default (dark) palette"),
    v("au-ink", "#ECF1F8"),
    v("au-ink-2", "#A8B5C9"),
    v("au-ink-3", "#6E7C92"),
    v("au-ink-4", "#4C586D"),
    blank,
    v("au-base", "#0A0F18"),
    v("au-base-2", "#0E1521"),
    v("au-base-3", "#131C2C"),
    v("au-pane", "rgba(255, 255, 255, 0.03)"),
    v("au-pane-2", "rgba(255, 255, 255, 0.05)"),
    v("au-pane-3", "rgba(255, 255, 255, 0.08)"),
    blank,
    v("au-edge", "rgba(255, 255, 255, 0.10)"),
    v("au-edge-2", "rgba(255, 255, 255, 0.05)"),
    v("au-rule", "rgba(255, 255, 255, 0.06)"),
    v("au-rule-2", "rgba(255, 255, 255, 0.10)"),
    blank,
    v("au-cool", "#CBA45E"),
    v("au-cool-2", "#B0852F"),
    v("au-cool-soft", "rgba(203, 164, 94, 0.14)"),
    c("Legacy name — now holds Gold. Kept so old class names keep compiling;\n     never reintroduce violet here."),
    v("au-violet", "#CBA45E"),
    v("au-violet-soft", "rgba(203, 164, 94, 0.14)"),
    c("Family plan hook — compatibility alias that resolves to Gold."),
    v("au-family", "#CBA45E"),
    v("au-family-soft", "rgba(203, 164, 94, 0.14)"),
    v("au-mint", "#54CB7E"),
    v("au-mint-soft", "rgba(84, 203, 126, 0.14)"),
    v("au-amber", "#E0A85A"),
    { kind: "raw", text: "--au-amber-soft:rgba(224, 168, 90, 0.14);" },
    v("au-coral", "#E25C5C"),
    { kind: "raw", text: "--au-coral-soft:rgba(226, 92, 92, 0.16);" },
    v("au-rose", "#F0A0B8"),
    blank,
    v("au-aurora-1", "rgba(203, 164, 94, 0.18)"),
    v("au-aurora-2", "rgba(203, 164, 94, 0.10)"),
    v("au-aurora-3", "rgba(84, 203, 126, 0.10)"),
    v("au-aurora-4", "rgba(240, 160, 184, 0.08)"),
    blank,
    v("au-row", "44px"),
    v("au-pad", "16px"),
    v("au-gap", "16px"),
    blank,
    raw("position: relative;"),
    raw("letter-spacing: 0;"),
  ],
};

const webAuroraLight: CssBlock = {
  selector: ".light .lf-aurora",
  rows: [
    v("au-ink", "#14202F"),
    v("au-ink-2", "#4A5C75"),
    v("au-ink-3", "#7A8A9F"),
    v("au-ink-4", "#ABB6C5"),
    v("au-base", "#EFEADF"),
    v("au-base-2", "#E7E1D4"),
    v("au-base-3", "#ECE6DA"),
    v("au-pane", "rgba(255, 255, 255, 0.70)"),
    v("au-pane-2", "rgba(255, 255, 255, 0.84)"),
    v("au-pane-3", "rgba(255, 255, 255, 0.92)"),
    v("au-edge", "rgba(255, 255, 255, 0.95)"),
    v("au-edge-2", "rgba(20, 32, 47, 0.06)"),
    v("au-rule", "rgba(20, 32, 47, 0.08)"),
    v("au-rule-2", "rgba(20, 32, 47, 0.14)"),
    blank,
    v("au-cool", "#2E5FB0"),
    v("au-cool-2", "#244C90"),
    v("au-cool-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-violet", "#2E5FB0"),
    v("au-violet-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-family", "#2E5FB0"),
    v("au-family-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-mint", "#0F6B50"),
    v("au-mint-soft", "rgba(15, 107, 80, 0.10)"),
    v("au-amber", "#7A5418"),
    { kind: "raw", text: "--au-amber-soft:rgba(138, 91, 22, 0.10);" },
    v("au-coral", "#A83333"),
    { kind: "raw", text: "--au-coral-soft:rgba(162, 59, 63, 0.10);" },
    blank,
    v("au-aurora-1", "rgba(46, 95, 176, 0.18)"),
    v("au-aurora-2", "rgba(46, 95, 176, 0.10)"),
    v("au-aurora-3", "rgba(15, 107, 80, 0.10)"),
    v("au-aurora-4", "rgba(162, 59, 63, 0.06)"),
  ],
};

const adminAuroraDark: CssBlock = {
  selector: ".adm-aurora",
  rows: [
    c("Default (dark) palette"),
    v("au-ink", "#F2F6FB"),
    v("au-ink-2", "#CBD5E4"),
    v("au-ink-3", "#9AA8BD"),
    v("au-ink-4", "#6E7C92"),
    blank,
    v("au-base", "#070B14"),
    v("au-base-2", "#0E1626"),
    v("au-base-3", "#16203A"),
    c("Glass alphas ~halved per the flat-corporate note."),
    v("au-pane", "rgba(255, 255, 255, 0.04)"),
    v("au-pane-2", "rgba(255, 255, 255, 0.06)"),
    v("au-pane-3", "rgba(255, 255, 255, 0.09)"),
    blank,
    v("au-edge", "rgba(255, 255, 255, 0.12)"),
    v("au-edge-2", "rgba(255, 255, 255, 0.10)"),
    v("au-rule", "rgba(255, 255, 255, 0.10)"),
    v("au-rule-2", "rgba(255, 255, 255, 0.16)"),
    blank,
    v("au-cool", "#CBA45E"),
    v("au-cool-2", "#B0852F"),
    v("au-cool-soft", "rgba(203, 164, 94, 0.20)"),
    v("au-violet", "#CBA45E"),
    v("au-violet-soft", "rgba(203, 164, 94, 0.20)"),
    v("au-family", "#CBA45E"),
    v("au-family-soft", "rgba(203, 164, 94, 0.14)"),
    v("au-mint", "#8BE3A8"),
    v("au-mint-soft", "rgba(84, 203, 126, 0.20)"),
    v("au-amber", "#E0A85A"),
    { kind: "raw", text: "--au-amber-soft:rgba(224, 168, 90, 0.20);" },
    v("au-coral", "#E25C5C"),
    { kind: "raw", text: "--au-coral-soft:rgba(226, 92, 92, 0.22);" },
    v("au-rose", "#F0A0B8"),
    blank,
    v("au-aurora-1", "rgba(203, 164, 94, 0.18)"),
    v("au-aurora-2", "rgba(203, 164, 94, 0.12)"),
    v("au-aurora-3", "rgba(84, 203, 126, 0.10)"),
    v("au-aurora-4", "rgba(240, 160, 184, 0.08)"),
    blank,
    c("── Phase 3 accent + chrome (dark: Gold) ──"),
    v("au-accent", "#CBA45E"),
    v("au-accent-2", "#DCBC7C"),
    v("au-accent-ink", "#0A1626"),
    v("au-accent-soft", "rgba(203, 164, 94, 0.13)"),
    v("au-accent-line", "rgba(203, 164, 94, 0.28)"),
    blank,
    raw("--au-surface:     #0E1626;                   /* solid chrome slab (rail/topbar/drawer/cards) */"),
    raw("--au-field:       #16203A;                   /* solid control fill */"),
    raw("--au-hover:       rgba(255, 255, 255, 0.05); /* neutral hover wash */"),
    raw("--au-track:       #1F2C47;                   /* progress/bar track */"),
    raw("--au-seg-on:      #1F2C47;                   /* active segmented chip */"),
    v("au-seg-shadow", "none"),
    v("au-scrim", "rgba(8, 12, 20, 0.55)"),
    blank,
    c("Status aliases — honey is strictly WARN."),
    v("au-ok", "var(--au-mint)"),
    v("au-ok-soft", "var(--au-mint-soft)"),
    v("au-ok-line", "rgba(84, 203, 126, 0.26)"),
    v("au-warn", "var(--au-amber)"),
    v("au-warn-soft", "var(--au-amber-soft)"),
    v("au-warn-line", "rgba(224, 168, 90, 0.26)"),
    v("au-danger", "var(--au-coral)"),
    v("au-danger-soft", "var(--au-coral-soft)"),
    v("au-danger-line", "rgba(226, 92, 92, 0.26)"),
    blank,
    c("Feathered elevation."),
    v("au-shadow-card", "0 1px 0 rgba(0, 0, 0, 0.25), 0 12px 24px -16px rgba(0, 0, 0, 0.40)"),
    v("au-shadow-drawer", "-34px 0 90px rgba(0, 0, 0, 0.35)"),
    blank,
    v("au-row", "48px"),
    v("au-pad", "18px"),
    v("au-gap", "16px"),
    blank,
    raw("position: relative;"),
    raw("letter-spacing: 0;"),
  ],
};

const adminAuroraLight: CssBlock = {
  selector: "html:not(.dark) .adm-aurora",
  rows: [
    v("au-ink", "#1A2433"),
    v("au-ink-2", "#5A6678"),
    v("au-ink-3", "#93A0B0"),
    v("au-ink-4", "#ABB6C5"),
    v("au-base", "#F4F6F9"),
    v("au-base-2", "#FFFFFF"),
    v("au-base-3", "#EDF1F6"),
    c("Panes go SOLID in light — control fills, table headers, etc."),
    v("au-pane", "#F4F6F9"),
    v("au-pane-2", "#EEF2F7"),
    v("au-pane-3", "#E8EDF4"),
    c("Edges become dark hairlines (no more white inset highlights)."),
    v("au-edge", "rgba(20, 32, 51, 0.10)"),
    v("au-edge-2", "rgba(20, 32, 51, 0.085)"),
    v("au-rule", "rgba(20, 32, 51, 0.085)"),
    v("au-rule-2", "rgba(20, 32, 51, 0.16)"),
    blank,
    v("au-cool", "#2E5FB0"),
    v("au-cool-2", "#244C90"),
    v("au-cool-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-violet", "#2E5FB0"),
    v("au-violet-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-family", "#2E5FB0"),
    v("au-family-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-mint", "#0F6B50"),
    v("au-mint-soft", "rgba(15, 107, 80, 0.10)"),
    v("au-amber", "#7A5418"),
    { kind: "raw", text: "--au-amber-soft:rgba(185, 131, 24, 0.10);" },
    v("au-coral", "#A83333"),
    { kind: "raw", text: "--au-coral-soft:rgba(200, 78, 81, 0.10);" },
    blank,
    c("── Phase 3 corporate accent + chrome (light: #2E5FB0) ──"),
    v("au-accent", "#2E5FB0"),
    v("au-accent-2", "#3D74C8"),
    v("au-accent-ink", "#FFFFFF"),
    v("au-accent-soft", "rgba(46, 95, 176, 0.10)"),
    v("au-accent-line", "rgba(46, 95, 176, 0.30)"),
    blank,
    v("au-surface", "#FFFFFF"),
    v("au-field", "#F4F6F9"),
    v("au-hover", "rgba(20, 32, 51, 0.035)"),
    v("au-track", "#E5E9F0"),
    v("au-seg-on", "#FFFFFF"),
    v("au-seg-shadow", "0 1px 2px rgba(20, 32, 51, 0.12)"),
    v("au-scrim", "rgba(20, 32, 51, 0.26)"),
    blank,
    v("au-ok-line", "rgba(15, 107, 80, 0.28)"),
    v("au-warn-line", "rgba(185, 131, 24, 0.28)"),
    v("au-danger-line", "rgba(200, 78, 81, 0.28)"),
    blank,
    v("au-shadow-card", "0 1px 2px rgba(20, 32, 51, 0.04), 0 1px 0 rgba(20, 32, 51, 0.02)"),
    v("au-shadow-drawer", "-34px 0 90px rgba(20, 32, 51, 0.18)"),
    blank,
    c("Aurora blobs barely visible on corporate paper."),
    v("au-aurora-1", "rgba(46, 95, 176, 0.06)"),
    v("au-aurora-2", "rgba(90, 102, 120, 0.05)"),
    v("au-aurora-3", "rgba(15, 107, 80, 0.04)"),
    v("au-aurora-4", "rgba(46, 95, 176, 0.03)"),
  ],
};

// ════════════════════════════════════════════════════════════════════
// Per-target assembly + render
// ════════════════════════════════════════════════════════════════════

/** A target emit file: layers + the column padding used in the original. */
export interface EmitTarget {
  /** Path relative to repo root. */
  outPath: string;
  layers: CssLayer[];
  pad: number;
  /**
   * `true` when the app CSS `@import`s this partial (unlayered custom
   * properties only). `false` for the shadcn `@layer base` partial, which
   * is inlined in globals.css and only emitted for drift comparison.
   */
  imported: boolean;
}

/**
 * Targets are split into two kinds:
 *
 *  - `imported: true` — written to a partial that the app CSS `@import`s.
 *    These hold ONLY unlayered custom-property blocks (`:root,.dark`,
 *    `.light`, `.lf-aurora`, …). They must NOT contain a `@layer base`
 *    directive: Turbopack runs Tailwind per-CSS-file, and a bare
 *    `@layer base` without a matching `@tailwind base` in the same file
 *    fails to compile.
 *
 *  - `imported: false` — the shadcn HSL `@layer base` block. It stays
 *    INLINE in globals.css (where `@tailwind base` lives, so the layer
 *    pairs correctly and the cascade is byte-identical to before). The
 *    emitter still renders it from the model and the drift test asserts
 *    the inline region matches, so it is single-sourced and guarded
 *    without breaking the Tailwind/Turbopack pipeline.
 */
export const emitTargets: EmitTarget[] = [
  {
    outPath: "apps/web/src/styles/_tokens.generated.css",
    pad: 16,
    imported: true,
    layers: [{ blocks: [webRootDark, webLight] }],
  },
  {
    outPath: "apps/admin/src/app/_tokens.generated.css",
    pad: 16,
    imported: true,
    layers: [{ blocks: [adminRootDark, adminLight] }],
  },
  {
    outPath: "apps/web/src/styles/_aurora-tokens.generated.css",
    pad: 16,
    imported: true,
    layers: [{ blocks: [webAuroraDark, webAuroraLight] }],
  },
  {
    outPath: "apps/admin/src/app/_aurora-tokens.generated.css",
    pad: 16,
    imported: true,
    layers: [{ blocks: [adminAuroraDark, adminAuroraLight] }],
  },
  // Shadcn HSL `@layer base` blocks — emitted for drift comparison against
  // the inline copy in globals.css; NOT imported (see note above).
  {
    outPath: "apps/web/src/styles/_tokens-shadcn.generated.css",
    pad: 16,
    imported: false,
    layers: [
      {
        layer: "base",
        blocks: [
          webShadcnRootDark,
          { selector: "__PLAN__", rows: webShadcnPlanRows },
          webShadcnLight,
        ],
      },
    ],
  },
  {
    outPath: "apps/admin/src/app/_tokens-shadcn.generated.css",
    pad: 16,
    imported: false,
    layers: [{ layer: "base", blocks: [adminShadcnRoot, adminShadcnDark] }],
  },
];

/**
 * Render one target to its final CSS string. The plan-class pseudo-block
 * (`selector === "__PLAN__"`) is emitted as bare lines inside the layer,
 * matching the original `globals.css` shape.
 */
export function renderTarget(target: EmitTarget): string {
  return emitCssVars(target.layers, { pad: target.pad });
}

/**
 * Render JUST the shadcn `@layer base` block body (no generated banner) for
 * a given app. This is the canonical text that globals.css inlines, so the
 * drift test can assert the inline copy still matches the model.
 */
export function renderShadcnLayer(app: "web" | "admin"): string {
  const outPath =
    app === "web"
      ? "apps/web/src/styles/_tokens-shadcn.generated.css"
      : "apps/admin/src/app/_tokens-shadcn.generated.css";
  const target = emitTargets.find((t) => t.outPath === outPath);
  if (!target) throw new Error(`no shadcn target for ${app}`);
  // Strip the banner + the leading blank line that follows it.
  return renderTarget(target).replace(`${GENERATED_BANNER}\n\n`, "").trimEnd();
}

function renderBlock(block: CssBlock, indent: string, pad: number): string {
  const lines: string[] = [];
  // Selector may contain newlines (`:root,\n.dark`). The first line takes
  // the block indent; continuation lines keep their authored indentation.
  const renderedSelector = block.selector
    .split("\n")
    .map((s, i) => (i === 0 ? `${indent}${s}` : s))
    .join("\n");
  lines.push(`${renderedSelector} {`);

  // Align declarations within the block: width is at least `pad`, but grows
  // so the longest `--name:` is still followed by a space (never jammed).
  const longestDecl = block.rows.reduce((max, row) => {
    if (row.kind !== "var") return max;
    return Math.max(max, `--${row.name}:`.length + 1);
  }, 0);
  const width = Math.max(pad, longestDecl);

  for (const row of block.rows) {
    if (row.kind === "blank") {
      lines.push("");
    } else if (row.kind === "comment") {
      lines.push(`${indent}  /* ${row.text} */`);
    } else if (row.kind === "raw") {
      lines.push(`${indent}  ${row.text}`);
    } else {
      const decl = `--${row.name}:`;
      lines.push(`${indent}  ${decl.padEnd(width, " ")}${row.value};`);
    }
  }
  lines.push(`${indent}}`);
  return lines.join("\n");
}

function renderPlanRows(rows: TokenRow[], indent: string): string {
  const lines: string[] = [];
  for (const row of rows) {
    if (row.kind === "blank") {
      lines.push("");
    } else if (row.kind === "comment") {
      lines.push(`${indent}/* ${row.text} */`);
    } else if (row.kind === "raw") {
      lines.push(`${indent}${row.text}`);
    }
  }
  return lines.join("\n");
}
