"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, CheckCircle2, Circle, Plus, X, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import Link from "next/link";
import { LoadingSpinner } from "@/components/shared/loading-state";

interface Task {
  id: string;
  title: string;
  description?: string;
  category: string;
  dueDate: string;
  priority: string;
  completed: boolean;
  isAutoGenerated?: boolean;
}

const priorityVariant: Record<string, "destructive" | "warning" | "info" | "secondary"> = {
  URGENT: "destructive",
  HIGH: "warning",
  MEDIUM: "info",
  LOW: "secondary",
};

const TASK_CATEGORIES = [
  "Address Change", "Utilities", "Insurance", "Financial", "Government",
  "Healthcare", "School", "Moving Day", "Packing", "Cleaning", "Other",
];

export default function MovingTasksPage() {
  const params = useParams();
  const planId = params.id as string;
  const [tasks, setTasks] = useState<Task[]>([]);
  const [filter, setFilter] = useState<"all" | "pending" | "completed">("all");
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [newTask, setNewTask] = useState({
    title: "", description: "", category: "Other", priority: "MEDIUM", dueDate: "",
  });

  useEffect(() => {
    fetch(`/api/moving/${planId}`)
      .then((res) => res.json())
      .then((data) => setTasks(data.plan?.tasks || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [planId]);

  const toggleTask = async (id: string) => {
    const task = tasks.find((t: Task) => t.id === id);
    if (!task) return;
    const newCompleted = !task.completed;
    setTasks((prev: Task[]) =>
      prev.map((t: Task) => (t.id === id ? { ...t, completed: newCompleted } : t))
    );
    await fetch(`/api/tasks/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ completed: newCompleted }),
    }).catch(() => {
      setTasks((prev: Task[]) =>
        prev.map((t: Task) => (t.id === id ? { ...t, completed: !newCompleted } : t))
      );
    });
  };

  const handleAddTask = async () => {
    if (!newTask.title) { toast.error("Title is required"); return; }
    setSaving(true);
    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...newTask,
          movingPlanId: planId,
          dueDate: newTask.dueDate || undefined,
        }),
      });
      if (!res.ok) throw new Error();
      const data = await res.json();
      setTasks((prev) => [...prev, data.task]);
      setNewTask({ title: "", description: "", category: "Other", priority: "MEDIUM", dueDate: "" });
      setShowForm(false);
      toast.success("Task added!");
    } catch {
      toast.error("Failed to add task");
    }
    setSaving(false);
  };

  if (loading) return <LoadingSpinner />;

  const filtered = tasks.filter((t: Task) => {
    if (filter === "pending") return !t.completed;
    if (filter === "completed") return t.completed;
    return true;
  });

  const completedCount = tasks.filter((t: Task) => t.completed).length;
  const progressPct = tasks.length > 0 ? (completedCount / tasks.length) * 100 : 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href={`/moving/${planId}`}>
            <Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4 mr-2" />Back</Button>
          </Link>
          <div>
            <h1 className="text-2xl font-bold">Moving Tasks</h1>
            <p className="text-muted-foreground text-sm">{completedCount}/{tasks.length} completed</p>
          </div>
        </div>
        <Button size="sm" onClick={() => setShowForm(!showForm)}>
          {showForm ? <><X className="h-4 w-4 mr-2" />Cancel</> : <><Plus className="h-4 w-4 mr-2" />Add Task</>}
        </Button>
      </div>

      {/* Add Task Form */}
      {showForm && (
        <Card className="border-primary/30 shadow-lg">
          <CardHeader><CardTitle className="text-lg">Add New Task</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            <div className="space-y-2">
              <Label>Title *</Label>
              <Input placeholder="e.g. Update driver's license" value={newTask.title} onChange={(e) => setNewTask((p) => ({ ...p, title: e.target.value }))} />
            </div>
            <div className="space-y-2">
              <Label>Description</Label>
              <Input placeholder="Optional details..." value={newTask.description} onChange={(e) => setNewTask((p) => ({ ...p, description: e.target.value }))} />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="space-y-2">
                <Label>Category</Label>
                <Select value={newTask.category} onChange={(e) => setNewTask((p) => ({ ...p, category: e.target.value }))}>
                  {TASK_CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Priority</Label>
                <Select value={newTask.priority} onChange={(e) => setNewTask((p) => ({ ...p, priority: e.target.value }))}>
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="URGENT">Urgent</option>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Due Date</Label>
                <Input type="date" value={newTask.dueDate} onChange={(e) => setNewTask((p) => ({ ...p, dueDate: e.target.value }))} />
              </div>
            </div>
            <div className="flex justify-end">
              <Button onClick={handleAddTask} disabled={saving}>
                {saving ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Saving...</> : "Add Task"}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Progress bar */}
      <div className="h-3 bg-muted rounded-full overflow-hidden">
        <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${progressPct}%` }} />
      </div>

      {/* Filter */}
      <div className="flex gap-2">
        {(["all", "pending", "completed"] as const).map((f) => (
          <Button key={f} variant={filter === f ? "default" : "outline"} size="sm" onClick={() => setFilter(f)} className="capitalize">
            {f} {f === "all" ? `(${tasks.length})` : f === "pending" ? `(${tasks.length - completedCount})` : `(${completedCount})`}
          </Button>
        ))}
      </div>

      {/* Task List */}
      <div className="space-y-2">
        {filtered.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-8">No tasks found</p>
        ) : (
          filtered.map((task) => (
            <Card key={task.id} className={`cursor-pointer transition-all ${task.completed ? "opacity-60" : ""}`}>
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <button onClick={() => toggleTask(task.id)} className="mt-0.5 shrink-0">
                    {task.completed ? (
                      <CheckCircle2 className="h-5 w-5 text-success" />
                    ) : (
                      <Circle className="h-5 w-5 text-muted-foreground hover:text-primary" />
                    )}
                  </button>
                  <div className="flex-1 min-w-0">
                    <p className={`font-medium text-sm ${task.completed ? "line-through" : ""}`}>{task.title}</p>
                    {task.description && <p className="text-xs text-muted-foreground mt-0.5">{task.description}</p>}
                    <div className="flex items-center gap-2 mt-2 flex-wrap">
                      <Badge variant={priorityVariant[task.priority]} className="text-[9px]">{task.priority}</Badge>
                      <span className="text-[10px] text-muted-foreground">{task.category}</span>
                      {task.dueDate && <span className="text-[10px] text-muted-foreground">Due {new Date(task.dueDate).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</span>}
                      {task.isAutoGenerated && <Badge variant="outline" className="text-[9px]">Auto</Badge>}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
