"""Generate packages/db/src/data/zcta-centroids.ts from the Census ZCTA Gazetteer.

One-off data generator. Reads the tab-delimited 2023 ZCTA Gazetteer (GEOID +
INTPTLAT + INTPTLONG) and emits a server-only TS module with a compact
newline-delimited string the runtime parses lazily into a ZIP->centroid map.
Re-run only to refresh the dataset; the .ts output is committed.
"""
import io
import os
import sys

src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/zcta/2023_Gaz_zcta_national.txt"
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", "src", "data", "zcta-centroids.ts")

rows = []
with open(src, encoding="utf-8") as f:
    f.readline()  # header
    for line in f:
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 7:
            continue
        geoid = parts[0].strip()
        try:
            lat = round(float(parts[5].strip()), 4)
            lng = round(float(parts[6].strip()), 4)
        except ValueError:
            continue
        if not (geoid.isdigit() and len(geoid) == 5):
            continue
        rows.append("%s,%s,%s" % (geoid, lat, lng))

data = "\n".join(rows)
header = (
    "// AUTO-GENERATED by packages/db/scripts/gen-zcta-centroids.py — do not edit by hand.\n"
    "// Source: US Census Bureau 2023 ZCTA Gazetteer (public domain, no attribution\n"
    "// required): https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/2023_Gaz_zcta_national.zip\n"
    "// One line per 5-digit ZCTA: \"GEOID,INTPTLAT,INTPTLONG\" (centroid lat/lng,\n"
    "// 4-decimal ~11m precision). Parsed lazily into a Map by zip-centroid.ts.\n"
    "/* eslint-disable */\n"
)
ts = header + "export const ZCTA_CENTROIDS_RAW = `" + data + "`;\n"

os.makedirs(os.path.dirname(out), exist_ok=True)
with io.open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write(ts)

print("rows:", len(rows))
print("size KB:", round(os.path.getsize(out) / 1024, 1))
print("first:", rows[0])
print("last:", rows[-1])
