import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { logger } from "@/lib/logger";
import { processPendingAccountDeletionRequests } from "@/lib/account-deletion";
import { guardCronRequest } from "@/lib/cron-guard";
import { LEGAL_CONSENT_EVENT, ONBOARDING_COMPLETED_EVENT } from "@/lib/legal";

/**
 * Data retention cron endpoint.
 * Cleans up old session logs, events, rate limit logs, and email logs
 * to prevent unbounded table growth.
 *
 * Secured with CRON_SECRET header check.
 * Recommended schedule: daily at 3:00 AM UTC.
 */
async function handleCron(request: NextRequest) {
  // Cron-secret check + per-route rate limit. Heavy retention sweep — keep
  // the limit low so a leaked secret can't trigger repeated mass deletes.
  const guard = await guardCronRequest(request, "data-retention", { limit: 2 });
  if (!guard.ok) return guard.response;

  const now = new Date();
  const results: Record<string, number> = {};

  try {
    // Delete UserSession records older than 90 days
    const sessionCutoff = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
    const deletedSessions = await prisma.userSession.deleteMany({
      where: { lastActivity: { lt: sessionCutoff } },
    });
    results.userSessions = deletedSessions.count;

    // Delete UserEvent records older than 90 days
    const eventCutoff = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
    const deletedEvents = await prisma.userEvent.deleteMany({
      where: {
        createdAt: { lt: eventCutoff },
        event: { notIn: [LEGAL_CONSENT_EVENT, ONBOARDING_COMPLETED_EVENT] },
      },
    });
    results.userEvents = deletedEvents.count;

    // Delete RateLimitLog records older than 30 days
    const rateLimitCutoff = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const deletedRateLimits = await prisma.rateLimitLog.deleteMany({
      where: { createdAt: { lt: rateLimitCutoff } },
    });
    results.rateLimitLogs = deletedRateLimits.count;

    // Delete EmailLog records older than 180 days. Match by sentAt for sent
    // rows AND by createdAt for rows that never sent (FAILED/PENDING and
    // dedupe-skipped rows leave sentAt NULL) — otherwise those accumulate
    // forever, defeating the purpose of this sweep.
    const emailCutoff = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
    const deletedEmails = await prisma.emailLog.deleteMany({
      where: {
        OR: [
          { sentAt: { lt: emailCutoff } },
          { sentAt: null, createdAt: { lt: emailCutoff } },
        ],
      },
    });
    results.emailLogs = deletedEmails.count;

    // Purge in-app notifications: expired ones immediately, plus any older than
    // 180 days. The feed is regenerated by the reminder crons; without this the
    // Notification table grows unbounded and slows per-user feed/count queries.
    const notificationCutoff = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
    const deletedNotifications = await prisma.notification.deleteMany({
      where: {
        OR: [
          { expiresAt: { not: null, lt: now } },
          { createdAt: { lt: notificationCutoff } },
        ],
      },
    });
    results.notifications = deletedNotifications.count;

    // ----- Audit / login / queue tables -----
    // These grow unbounded without pruning. Audit trails get a GENEROUS 730-day
    // (2-year) window so investigations and compliance lookbacks aren't starved;
    // login telemetry and the (already-sent) notification queue get shorter
    // windows. None of these models are soft-delete models, so deleteMany on the
    // default `prisma` client is a real hard delete — exactly what we want here.

    // AuditLog — user-facing audit trail. Keep 730 days.
    const auditCutoff = new Date(now.getTime() - 730 * 24 * 60 * 60 * 1000);
    const deletedAuditLogs = await prisma.auditLog.deleteMany({
      where: { createdAt: { lt: auditCutoff } },
    });
    results.auditLogs = deletedAuditLogs.count;

    // AdminAuditLog — admin action trail. Keep 730 days.
    const adminAuditCutoff = new Date(now.getTime() - 730 * 24 * 60 * 60 * 1000);
    const deletedAdminAuditLogs = await prisma.adminAuditLog.deleteMany({
      where: { createdAt: { lt: adminAuditCutoff } },
    });
    results.adminAuditLogs = deletedAdminAuditLogs.count;

    // AdminLoginLog — admin auth telemetry. Keep 365 days.
    const adminLoginCutoff = new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);
    const deletedAdminLoginLogs = await prisma.adminLoginLog.deleteMany({
      where: { createdAt: { lt: adminLoginCutoff } },
    });
    results.adminLoginLogs = deletedAdminLoginLogs.count;

    // UserLoginSession — server-side session/impersonation records. Prune rows
    // that are stale on BOTH timestamps (created AND last seen > 180 days ago)
    // so a long-lived but recently-active session is never pruned out from
    // under the user.
    const userLoginSessionCutoff = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
    const deletedUserLoginSessions = await prisma.userLoginSession.deleteMany({
      where: {
        createdAt: { lt: userLoginSessionCutoff },
        lastActivity: { lt: userLoginSessionCutoff },
      },
    });
    results.userLoginSessions = deletedUserLoginSessions.count;

    // NotificationQueue — only purge rows that have already been delivered
    // (sent = true) and are older than 90 days. Unsent/pending rows are left
    // alone regardless of age so a stuck job is never silently dropped.
    const notificationQueueCutoff = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
    const deletedNotificationQueue = await prisma.notificationQueue.deleteMany({
      where: {
        sent: true,
        createdAt: { lt: notificationQueueCutoff },
      },
    });
    results.notificationQueue = deletedNotificationQueue.count;

    const deletionResults = await processPendingAccountDeletionRequests(25);
    results.accountDeletionRequestsProcessed = deletionResults.length;
    results.accountDeletionRequestsCompleted = deletionResults.filter((result) => result.status === "COMPLETED").length;

    logger.info("Data retention cleanup completed", {
      action: "DATA_RETENTION",
      ...results,
    });

    return NextResponse.json({ success: true, cleaned: results });
  } catch (error) {
    logger.error("Data retention cleanup failed", {
      action: "DATA_RETENTION",
      error: String(error),
    });
    return NextResponse.json({ error: "Cleanup failed" }, { status: 500 });
  }
}

export async function GET(request: NextRequest) {
  return handleCron(request);
}

export async function POST(request: NextRequest) {
  return handleCron(request);
}
