export {
  type AddressAutocompletePrediction,
  type AddressAutocompleteResult,
  type AddressAutocompleteSearchResponse,
  type AddressAutocompleteDetailsResponse,
  type AddressAutocompleteFormFields,
  type AddressAutocompleteSelectionFields,
  type AddressAutocompleteSelectionConflict,
  type AddressAutocompleteSelectionConflictKind,
  createAddressAutocompleteSessionToken,
  clearAddressAutocompleteMetadata,
  applyAddressAutocompleteResult,
  getAddressAutocompleteSelectionConflict,
  formatAddressAutocompleteSelectionConflict,
} from "../../../../packages/shared/src/address-autocomplete";
